### ISSUE TITLE
schema version?

### ISSUE THREAD

**Issue by JasonSwindle** [jsonresume/resume-schema#104]
Howdy,

We should use [Semantic Versioning](http://semver.org/), and have that defined in the JSON.  That way, when the parser hits that, it knows what fields should be defined.

```json
  "schemaVersion": {
    "semver": "0.0.1" 
  },
```

What do you think?

Thanks,
_Jason Swindle_

**Comment by stp-ip** [comment]
This is not yet in the schema. The actual schema is versioned, but the json for each resume does not reflect or store any version. So a field such as the proposed:
  "schemaVersion": {
    "semver": "0.0.1" 
  },
Is still needed

**Comment by olivif** [comment]
dupe of #49 ?

**Comment by aloisdg** [comment]
Yep. You can close this thread as duplicate.

**Comment by olivif** [comment]
:+1:
