### ISSUE TITLE
projects in work

### ISSUE THREAD

**Issue by priyolahiri** [jsonresume/resume-schema#11]
In my opinion, every work should have a project sub array, detailing:
1. Duration
2. Skills
3. Responsibilities
4. Description

**Comment by stp-ip** [comment]
I would say that the subhierarchy "projects" should be included for work, education and volunteer stuff. Not just for work.

**Comment by aloisdg** [comment]
Related to #38

**Comment by phumke** [comment]
I like the structure, but I'm not sure about 'highlights'.  This seems like 'project' work is rehashed here without proper association.  Maybe each 'project' within a section should have a 'highlight' boolean.

**Comment by stp-ip** [comment]
Highlights might move into 2 places. Once on the root level for work, so one can showcase smaller highlights or overall highlights for the general work item and once for each project under the work item.
Then you can for example showcase highlights of different clients/projects, but at the same time highlight that all projects contributed to a 50% reducing in water usage as an example.

Hope that clears the ideas up a bit.

**Comment by MikelArnaiz** [comment]
Hi, I ended up on `jsonresume`on my research of a tool to show in a graphical way the skills/known technologies/stack, and the total time worked on those over the years.

I was considering creating my own theme to achieve that but I would need something like a `projects: []` field in the schema.

I agree with @priyolahiri  on his proposed fields and I'd add:

- `url` (string), for publicly available projects.
- `images` (string[]) to mimic a porfolio.
-  `tech` / `stack` or more genenal `skills ` (string[])  to name the those used technologies in the project

**Comment by thomasdavis** [comment]
I'm cleaning up the repo for `1.0.0` release, after watching the schema for over half a decade, I don't believe this amendment is request enough to warrant inclusion. 

It could be implemented through a supplementary package or additions to the `meta` top level property.
