### ISSUE TITLE
geotag location in work

### ISSUE THREAD

**Issue by priyolahiri** [jsonresume/resume-schema#12]
every work should have an optional lat, lng. this would give me a map of areas worked, and also ties in experience duration with locations which can help companies offer jobs by location relevance and comfort factor with the location.

**Comment by mboudreau** [comment]
I definitely agree with having lat/lon within location, and I think @wdoekes example is probably the easiest and best way to implement it.

**Comment by mboudreau** [comment]
On second thought, I've been doing some work around geolocation and such, and there's a few standards that can work:

```
"location": { 
    "lat": 41.12,
    "lon": -71.34
  }

"location": "41.12,-71.34"

"location": [ -71.34, 41.12 ]
```

I like the last one, it's fairly easy to use and implement, makes sense and doesn't need 2 properties, just one.

**Comment by aloisdg** [comment]
@mboudreau I think we should avoid to use an abbreviation. Do you have any source for a standard about geotag?

**Comment by aloisdg** [comment]
Also, if we can avoid the use of adresses I would love it. Addresses are jokes. Sincerely.

**Comment by stp-ip** [comment]
I agree latitude and longitude should be first class citizens, but try sending documents to a GPS location... Not going to get delivered most of the time. So address should still be another first class citizen.

Back to the suggestions. I like the last approach, but on a second thought having the specific fields named reduces the mental work people/devs have to do, when interacting with the standard. That shouldn't be the sole focus, but needs to be considered.

**Comment by aloisdg** [comment]
I think we should follow the `Point` schema of [GeoJson](http://geojson.org/):
```json
{
    "coordinates": [125.6, 10.1]
}
```

It is @mboudreau last suggestion.

**Comment by mboudreau** [comment]
@stp-ip I agree, address is still very important for me.  

I did consider the mental work needed, but the fact is, the geo location normally needs to be fed into a function or API, which often times uses this format.  For example, I'm currently trying to index JSON Resume into ElasticSearch and they accept a document with the geolocation format in an array format.

I don't think the mental work is a big factor since very rarely will the dev ever need to access just one, or print off both.  It's normally something that's just fed into a map or into another system like google maps, which has an API that interacts like this:

```
https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452
```

Which using the format I've suggested, is a simple join if you're doing strings:

```
var url = "https://maps.googleapis.com/maps/api/geocode/json?latlng=" + resume.basics.location.coordinates.join(',');
```

Or, if you're using an HTTP library, most of them has a place for params:

```
var request = require('https');
request({
    url: "https://maps.googleapis.com/maps/api/geocode/json",
    params: {
        latlng: resume.basics.location.coordinates.join(',')
    }
});
```

**Comment by stp-ip** [comment]
Thanks for addressing my concern. I agree and see that it might be not as bad as previously thought. Especially considering, that we might add more tooling around the standard, which might help theme devs etc. to use specific formats.

**Comment by stp-ip** [comment]
Proposal:

Add lat/long as ```coordinates```following the ```Point``` schema of [GeoJson.](http://geojson.org/) to work, school, etc.

```
{
    "coordinates": [125.6, 10.1]
}
```

**Comment by aloisdg** [comment]
@stp-ip I think [I agree with you](https://github.com/jsonresume/resume-schema/issues/12#issuecomment-204418109) ;)

**Comment by olivif** [comment]
+1

**Comment by stp-ip** [comment]
Ok final decission for implementation for now.

* add coordinates as optional field for all location items.
* make address optional
* add documentation about latlon and address issues

```
{
    "coordinates": [125.6, 10.1]
}
```

**Comment by skinnedpanda** [comment]
Could it be an idea to use Google's plus codes when defining the address? It'll simplify the schema; and cover any address types worldwide.
https://github.com/google/open-location-code/

**Comment by jacobbogers** [comment]
HI folks, just taking a looksy, I like the idea of this project

**Comment by thomasdavis** [comment]
After much thought, I don't think this schema request is useful for the larger use case. 

Although the ability to analyse/report on resume data is ideal, most people merely want to display their location. 

The Google open-location-code sounds like the best way forward in the future though.
