### ISSUE TITLE
A Consistent Rule for "studyType" in Education

### ISSUE THREAD

**Issue by JaredCubilla** [jsonresume/resume-schema#125]
I've noticed that in the sample [Richard Hendriks resume](http://themes.jsonresume.org/theme/flat), the studyType was "Bachelor", while in [@rolandnsharp's resume](http://registry.jsonresume.org/rolandsharp?theme=flat), the studyType was "bachelor's degree". Could we fix this inconsistency and have a rule for this?

**Comment by aloisdg** [comment]
Any news around this issue? I am asking myself the same question right now.

**Comment by olivif** [comment]
given we are trying to build a standard, massive +1 for this :)

**Comment by stp-ip** [comment]
I think studytype is too varied to have predefined types. But I would love to be convinced otherwise.

**Comment by chrisdotcode** [comment]
I'm with @stp-ip. Considering languages, regions, etc., it doesn't seem easily possible.

**Comment by aloisdg** [comment]
[Wikipedia's topic](https://en.wikipedia.org/wiki/Academic_degree) around this subject. Yep it is a mess. We need a standard for this ;)

**Comment by chrisdotcode** [comment]
Is this even *possible* to standardize? I'm all for free-form, but if you'd to even attempt to tackle pretty much the entire world at once, I'm right behind you. ...Not *directly* behind you, but behind you :)

**Comment by aloisdg** [comment]
> Is this even possible to standardize? 

Listen to your heart!

> free-form

Only solution for now.

**Comment by chrisdotcode** [comment]
Alright, so since it's our only solution for the moment, I'm going to close this issue to reduce clutter. Just recomment, and I'll re-open.
