### ISSUE TITLE
Some personally identifiable information missing. Can I add them?

### ISSUE THREAD

**Issue by gee-forr** [jsonresume/resume-schema#13]
Hi all,

I love this concept, thank you!!! For this schema to work in a South African context, there are a few things missing. South African employment requires street addresses as well as (and this might freak you out): Race.

This is because we are still in the midst of Black Economic Empowerment, and Employment Equity post apartheid.

If you don't mind, I'd like to add these fields as optional parts to the schema.

Let me know, and I'll issue a PR.

**Comment by stp-ip** [comment]
Additionally I would love optional fields such as:
"birthdate", "birthplace"

**Comment by aloisdg** [comment]
For the subject of race, I will link this [conversation](https://github.com/jsonresume/resume-schema/issues/41#issuecomment-107251551) (cc @DandyDev).

**Comment by stp-ip** [comment]
@aloisdg as per #193 A warning as description is added and the more personal information is located in a special object. We could add another warning, which themes could pick up more easily probably, but haven't thought of one.

**Comment by opensourcegrrrl** [comment]
@gee-forr From a US perspective (I don't know if SSN is used in other countries), a SSN is a highly protected number. Therefore, absolutely -1 on prompting the CV writer to include their SSN:

{
type: 'SSN',
value: '123456-7890'
}

For any non-security-clearance position, that information is provided to the employer after a resume/CV is provided, and often only after an offer has been signed.

**Comment by opensourcegrrrl** [comment]
Also, I have never provided a passport number on a resume. It what places and/or situations is this a requirement?

**Comment by smalik** [comment]
Some of this stuff is illegal to ask for in the U.S.

**Comment by gee-forr** [comment]
@opensourcegrrrl thanks for the clarification... I was merely using SSN as an example. In ZA, we require an ID number, or passport number as part of an application. I was under the assumption that an SSN was equivalent to that.

**Comment by gee-forr** [comment]
@smalik - yeah - I totally get that. However, in ZA, it's normal to ask for this information.

**Comment by opensourcegrrrl** [comment]
This is a great argument for localization. :)

**Comment by wayneamurphy** [comment]
-∞ for SSN as a required field, as others have suggested it is not allowed to accept non-public information like that in North America.

I agree about the need for I18N focus, but I will also ask the question about when a potential needs to know something?
For places that want to know the race, or some other characteristic like gender identification (aka other than the traditional 2 choices), or military experience - do they need to know that eventually, or would you be immediately filtered out if not specified on the resume up front?

**Comment by thomasdavis** [comment]
The project has evolved to be ambiguous when considering localization and internalization. 

Everything is largely contingent on themes, and everything else can be supplemented via new packages and the top level `meta` property.
