### ISSUE TITLE
Does the schema allow for meta or display information?

### ISSUE THREAD

**Issue by colindean** [jsonresume/resume-schema#133]
I have a lot of positions and a lot of volunteer work, but there are only certain ones that I'd want to show for certain aspects of my life. E.g., if I'm applying to a tech job, then I probably only want my tech jobs to show up on the resume. If I'm applying to a non-profit, then they probably only really care about my non-profit work and perhaps whatever it is I'm doing *right now* full-time.

What I think I'd like to do is be able to add a `meta` section of some kind, e.g.:

```
"work": [
    {
      "company": "Tech Company X",
      "position": "CEO/President",
      "startDate": "2013-12-01",
      "_meta": {
        "groups": ["tech", "current"]
      }
    },
    {
      "company": "Non-Profit Y",
      "position": "President",
      "startDate": "2012-12-01",
      "_meta": {
        "groups": ["non-profit"]
      }
    },
    {
      "company": "Non-Profit Y",
      "position": "Secretary",
      "startDate": "2011-12-01",
      "endDate": "2012-12-01",
      "_meta": {
        "groups": ["non-profit"]
      }
    },
   {
      "company": "Inconsequential Non-Profit Z",
      "position": "Inconsequential position",
      "startDate": "2010-12-01",
      "endDate": "2011-12-01",
      "_meta": {
        "groups": ["non-profit"],
        "display":"only-on-complete-history",
      }
     },
     {
      "company": "Tech Company B",
      "position": "Doer of Great Things",
      "startDate": "2011-12-01",
      "endDate": "2013-12-01",
      "_meta": {
        "groups": ["tech"]
      }
    }
     {
      "company": "Prominent Non-Profit Y",
      "position": "Doer of Great Things",
      "startDate": "2006-12-01",
      "endDate": "2009-12-01",
      "_meta": {
        "groups": ["non-profit"]
      }
    }
  ],
```

I think my example makes sense. Essentially, I have many **aspects** of my life, and I'd like for a standards-compliant way to group them. Because my grouping may be arbitrary, or have other logic, it might be nice to throw it into a `_meta` bucket that acts as a bit of a namespaced area. 

Or this proposed solution may not be the best way to proceed in a JSON Schema fashion. In an XML resume format, I'd expect to be able to do something like `<meta:groups><meta:group>tech</meta:group><meta:group>non-profit</meta:group></meta:groups>`, but I don't know how best to reflect that in a JSON Schema world.

**Comment by stp-ip** [comment]
I would say the easiest way would be to use labels. They are already in use with some other parts.
One could easily define that there can be hidden labels such as "_hidden_label".
This would not introduce a new idea, but enable public labels and hidden ones for more fine grained control. what the specific tools make out of that, should not be a data storage design discussion as far as my opinion goes.

**Comment by olivif** [comment]
+1 for having one json master and being able to export different versions based on metadata

So I take it this is possible today? Could someone please summarize the possible ways to achieve this?

**Comment by stp-ip** [comment]
Not possible today, but hopefully possible with the introduction of more keywords and some metadata info. Still being discussed in how many areas keywords are added and what the format for metadata for hiding and showing based on different areas will be.

**Comment by stp-ip** [comment]
I think we agreed on having meta data within a metadata section described here: #204.

This could be used for tagging, export rules and display information.

Closing for now. If one disagrees about the closing of this issues, please reopen.

**Comment by marc-bouvier** [comment]
I think a way to do today might be to have a main `resume.json` that somehow includes some custom metadata. 

We can "fork" several new json resumes by applying some filtering based on those metadata from the `resume.json` file.
I believe this kind of filtering can be done in a few lines with tools like [`jq`](https://stedolan.github.io/jq/).

Then, we may publish (publicly of privately) both "forked" `resume.json` files. 
Then, we can generate some html for both of them.

```mermaid
flowchart TD

    resume.json["resume.json (single source of truth)"]
    resume.json-- transform with jq script--> volunteer/resume.json
    volunteer/resume.json -- generate --> volunteer/resume.html

    subgraph public [Public repository]
        volunteer/resume.json
        volunteer/resume.html
    end

    resume.json -- transform with jq script --> professional/resume.json
    professional/resume.json -- generate --> professional/resume.html

    subgraph private [Private repository]
        professional/resume.json
        professional/resume.html
    end   
```
