### ISSUE TITLE
Support for Team under work

### ISSUE THREAD

**Issue by shirhatti** [jsonresume/resume-schema#137]
Can we discuss adding support for a `team`/`organization` attribute under employment?
In companies with diverse holdlings, specifying the team lends credibility to your area of expertise

**Comment by olivif** [comment]
I would vote for using position for this. An argument for using division would be to avoid duplication between the entries but after a quick look at the schema I don't think that would be an issue, most fields should be unique to the position. Also, there is a semantical argument to be made for the fact that roles at the same companies but in different divisions are essentially different positions.

**Comment by stp-ip** [comment]
For now we seem to have moved to using role instead of position to be more consistent.

**Comment by olivif** [comment]
@stp-ip I don't see a role in the schema currently, but I see position. Is this coming up?

**Comment by stp-ip** [comment]
@olivif 
> Projects and events have roles (perhaps rename "position" in work to "role" to be consistent).

As discussed in: https://github.com/jsonresume/resume-schema/issues/201#issuecomment-157852603

**Comment by olivif** [comment]
gotcha. thanks!

**Comment by chrisdotcode** [comment]
Yup. We're renaming to role.

**Comment by shaedrich** [comment]
Well, "team" sounds more like "department" than "role"/"position" to me 🤔
