### ISSUE TITLE
Events, projects and non professional experience 

### ISSUE THREAD

**Issue by lilobase** [jsonresume/resume-schema#138]
Hello,

I make three additions to the current schema : 

Events : 
https://github.com/jsonresume/resume-schema/pull/122
(can be related to : https://github.com/jsonresume/resume-schema/issues/103)
The idea seem to be not so popular, but there is a try. And because I organize some event, I want to show them in my resumé. 

Projects : 
https://github.com/jsonresume/resume-schema/pull/123
To resolve issue like : https://github.com/jsonresume/resume-schema/issues/112

Non professional experience: 
https://github.com/jsonresume/resume-schema/pull/123
Seems to be a duplication with existing volunteer section, but for me volunteer is too related to the non-profit organization, that why I choose the additionnal experience label.

**Comment by natemacinnes** [comment]
+1

**Comment by xueye** [comment]
+1 on projects, at least; it would be very helpful to show non-work related things we're proud of.

**Comment by constantx** [comment]
`events` sounds like it could be part of `project` already, since it’s what one can participate/worked on ;)

**Comment by stp-ip** [comment]
@constantx I would say that event is more like a speaking event. If you organize an event, it would probably be more in the area of project.
Furthermore I would probably agree that volunteering section is a bit too closed down, but I would not add a completely new non professional exeprience section, but rename or modify the volunteering one.

**Comment by olivif** [comment]
I think #2 is covered by projects top level section and #3 is covered by projects in the volunteering section. 

Also, if I understand correctly, the events scenario is covered by projects as well, if we are talking about events that you organized, like mentioned by @lilobase in the original proposition. 

@stp-ip you mentioned events that you attend/speak at. Is that a new one? :smile:

**Comment by olivif** [comment]
actually I just found #20, sounds like that's the place to be for the remaining "events you attend" topic. I will close this one.
