### ISSUE TITLE
Add a Patents section

### ISSUE THREAD

**Issue by ronc** [jsonresume/resume-schema#14]
Add a section for patents granted, similar to the awards section.

```
patents: [{
    patentNum: string,
    issueDate: string,
    title: string,
    abstract: string,
}], 
```

**Comment by stp-ip** [comment]
+1 for the patents proposition with the addition of "state"

**Comment by olivif** [comment]
+1 . agree with @alexbarclay , definitely need a state field as a lot of patents.

**Comment by chrisdotcode** [comment]
Patents? Why would this be necessary? Everything one ever does should be released in the public domain.


...Just kidding. Let's aggregate all legal IP ownership 'things' (`copyrights`, `trademarks`, etc), and make one category for them if we can.

**Comment by stp-ip** [comment]
I think we should add a generic legal section with something like the following pseudo section:

$legal-category: [{
    name: string,
    description: string,
    website: url, <- (website seems wrong here, for identifiers/videos/slides etc. we could say resource.)
    type: enum, <- (patent, trademark, copyright, ?)
    applicationDate: $date,
    grantDate: $date,
}],

**Comment by aloisdg** [comment]
The project section can be use for this,can't it?

**Comment by stp-ip** [comment]
Can yes, but should it. As it is perhaps a huge asset to have a patent it might not be great to have it in your misc projects section.
As this section provides information about legally binding assets, I would argue that it might be worth separating it.

**Comment by aloisdg** [comment]
I agree to use it later. I think we should move this to the next version.

**Comment by stp-ip** [comment]
Ok leaving it as v1 for now, but we might push it to the next version during another revisit.

**Comment by stp-ip** [comment]
I would say lets get something tangible in the schema and iterate on that.

For now I would suggest something similar to:

```
legal: [{
    name: string,
    description: string,
    source: url + label, (see #256)
    type: string, (examples: patent, trademark, copyright)
    applicationDate: $date,
    grantDate: $date,
}]
```

**Comment by aloisdg** [comment]
Good!

**Comment by wayneamurphy** [comment]
I'll say that since you are awarded a patent, I would think "awards" seems like an appropriate place.
That's where I put mine :-)

**Comment by thomasdavis** [comment]
Most themes don't support patents, for now patents can live in the `meta` property for those who require it. They will also need to fork themes and add the rendering ability for patents or push for the author to update their themes.

**Comment by heitorPB** [comment]
@thomasdavis, would you reopen this or accept the pull request that adds the `legal` section so that someone could add that to the themes? It is a bit off to not accept an addition to the schema because the themes don't support something that is not in there.

I don't know much about html, and I'd like to help to get this approved. But to add it to a theme, it must first be in the schema, right?
