### ISSUE TITLE
start/endDates with only YYYY-MM should be valid

### ISSUE THREAD

**Issue by dbkaplun** [jsonresume/resume-schema#142]

**Comment by DandyDev** [comment]
We need a PR for this, right? To use a different date type? @thomasdavis are we ok on this?

**Comment by stp-ip** [comment]
As we are using ISO8601 for v1.0.0, unspecific dates such as 2015, 2015-01 should be valid too.

**Comment by evanplaice** [comment]
Fixed in [v.0.1.1](https://github.com/jsonresume/resume-schema/releases/tag/v0.1.1)
