### ISSUE TITLE
Rename "languages.language" to "languages.name"

### ISSUE THREAD

**Issue by mwaclawek** [jsonresume/resume-schema#145]
For consistency, we should rename `languages.language` to `languages.name` and drop the redundancy.

We have that schema for `awards`, `publications`, `skills` and `interests` already.

We don't have `awards.award`, `publications.publication`, etc. there.

Same for `references.reference` which could be `references.text`, `references.content` or `references.body`.

Minor issue but a subtle improvement in my opinion.

**Comment by DandyDev** [comment]
As said, I like this change, but we need more comments on this before we can merge the PR. @thomasdavis ?

**Comment by mchelen** [comment]
Is there any downside to this change?

**Comment by opensourcegrrrl** [comment]
All I see are +1s.

**Comment by olivif** [comment]
+1

**Comment by chrisdotcode** [comment]
Sounds good.

**Comment by olivif** [comment]
+ folks @stp-ip @thomasdavis @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's go.

**Comment by stp-ip** [comment]
Sounds like #149 can be merged. I'll be proactive here and do that. Please revert, if there should still be an issue.

**Comment by olivif** [comment]
thanks @stp-ip ! :smile:

**Comment by aloisdg** [comment]
Already changed in SharpResume :)

**Comment by billwanjohi** [comment]
While this change was merged to master in 2015 and (#149) and changed on the website in early 2016 (https://github.com/jsonresume/resume-website/pull/27), the master branch looks to have been abandoned shortly thereafter, neither the 0.0.0 tag nor the 1.0.0 branch has the changes, and the old format is all that works for me. This discrepancy is very confusing.

**Comment by stp-ip** [comment]
The master branch is still the one used for production.
