### ISSUE TITLE
Not everyone uses GPA

### ISSUE THREAD

**Issue by ThomWright** [jsonresume/resume-schema#146]
For example:
[British undergraduate degree classification](https://en.wikipedia.org/wiki/British_undergraduate_degree_classification)
and
[Academic grading in the United Kingdom](https://en.wikipedia.org/wiki/Academic_grading_in_the_United_Kingdom)

Could we perhaps have something more along the lines of:

```
"gradeType": "GPA",
"grade": "4.0"
```

This allows templates to indicate which type of grading system is being used. E.g.

![GPA example](https://cloud.githubusercontent.com/assets/1861842/4344325/eb8210e0-4089-11e4-9887-e6d6d07fbfa5.png)

I'm open to alternative suggestions :)

**Comment by DandyDev** [comment]
+1 for having `grade` instead of `GPA`

**Comment by mistakenot** [comment]
+1 UK degree here, having grade or something more generic would make more sense from an international POV.

**Comment by stp-ip** [comment]
"grade": "1.3"  
"grade_scale_best": "1.0"  
"grade_scale_worst": "5.0"  
could be more machine readable and user friendly.

**Comment by olivif** [comment]
For the UK I'm not sure you would have a number necessarily. I think it's a lot more common to have the [classification](https://en.wikipedia.org/wiki/British_undergraduate_degree_classification) of your degree 

`"classification": "First class"`
`"classification": "Upper Second-Class"`
`"classification": "2.2"`

**Comment by aloisdg** [comment]
I am not sure about this. My school is using GPA, but it is not a norm. Also, who cares about GPA after leaving school? Nobody care in France as far as I know.

**Comment by stp-ip** [comment]
If we revisit this after v1. We should remove the current GPA usage. It seems wrong to acknowledge, that it is not enough, but leave it in.

I still think the most generic and machine readable solution would be:
"score": "1.3"  
"score_best": "1.0"  
"score_worst": "5.0"

**Comment by aloisdg** [comment]
@stp-ip I really think a score without a median is not worth it. I am still against for now.

**Comment by stp-ip** [comment]
OK so we agree to revisit a solution.

Remove the GPA or not? I would say remove it for now from the schema, but allow additional fields to make the pre-v1 GPA field compatible?

**Comment by aloisdg** [comment]
@stp-ip I am ok to remove it, but most people here seem for using it.

**Comment by Johnstone-Tech** [comment]
What is the staus on this issue?

**Comment by Frontrider** [comment]
As of now, I can't use it after an update. It seems to be failing because we do not have GPA. That is a bad standard to have.

**Comment by DandyDev** [comment]
Discussed in #288, first proposal in #328, fixed in #391
