### ISSUE TITLE
What about one flexible/generic field to rule them all?

### ISSUE THREAD

**Issue by lfilho** [jsonresume/resume-schema#151]
Hi there. I'm seeing many request for this and that field, to suit custom wishes and different professional backgrounds. And while I'm with you that the schema should be concise and consistent, I'm thinking whether it would be a fair solution to have a flexible, generic field in the spec, then anyone that could not find your wishes fulfilled in the current schema, could just use this generic field to fit their needs.

I don't know, something like:
```
"custom": {
    "type": "array",
    "name": "Your section name here",
    "description": "Specify any section you want your resumé to have but is not prsent in the rest of the schema",
    "additionalItems": true,
    "items": {
        ...
    }
}
```

What do you think?

**Comment by lfilho** [comment]
Bump?

**Comment by olivif** [comment]
Hmm interesting idea. On one hand I love the flexibility of this, but on the other hand I believe in building a standard, and some consistency across resumes. In my mind if we do a good job, the v1 schema should enable most scenarios.

**Comment by aloisdg** [comment]
It feels strange to have this on schema as @olivif said. Someone has an example of a scheme doing this? Also it may be weird for templates to use it. I think we shouldn't overthink this for the v1 and see for a `next` version.

**Comment by stp-ip** [comment]
I am with @olivif and @aloisdg on this. Having a specific ```custom``` section would most likely reduce upstream discussions and reduce the need for a generic resume standard. The only thing I would be open too, is that one would be allowed to append a new section, but 100% against a section called ```custom```.

**Comment by chrisdotcode** [comment]
This exists! It's called `meta`, and anybody can do anything they want to it :grin:
- - -
(I don't see how this proposed `custom` field would be any different from `meta`: if I am incorrect, feel free to re-open).

**Comment by olivif** [comment]
@chrisdotcode I think there is a big difference. The meta section is for metadata only. What @lfilho was proposing is the ability to add new sections entirely. In my mind metadata should not allow people to create their own sections, that would defeat the point of the standardization. 

I am OK with keeping this closed, just wanted to point out the distinction 😄

**Comment by chrisdotcode** [comment]
@olivif: Hrm... Maybe we should rename metadata, then? Metadata is supposed to be an all-purpose generic and arbitrary object store for anyone to put any additional data into, including extending the schema in ways an organization sees fit. For example:

```json
{  "meta": {
  "chrisdotcode": {
    "foo": "bar"
    }
}
}
```

If `metadata` doesn't convey that, then, perhaps we should rename the field to be more all-encompassing.

**Comment by olivif** [comment]
Hmmm. Based on the name my impression was that is was only to be used for metadata. In my mind the use case here was to allow companies to for instance add a userId that is internal to the org, but not to be used for fully fledged sections. 

I guess we have discussed a lot of the uses that we would have for the metadata field, like version, canonical, etc. But not the extensibility story on how we recommend people use it.

**Comment by stp-ip** [comment]
In the discussion the intention of meta was mainly for tool generated or additional data, which is not related to the person directly. Everything else should be done in the actual schema and if not possible, it should be discussed upstream to be included.

**Comment by olivif** [comment]
@stp-ip my thoughts exactly :)
