### ISSUE TITLE
Specifying focus for education (free text field?)

### ISSUE THREAD

**Issue by PragTob** [jsonresume/resume-schema#152]
Hi there,

It'd be nice to have a free text field (or something else) much like the summary of other fields for education. For instance, a focus in my bachelor's were IT-Security, Object-Oriented Design and Agile software development. This is very relevant to future employers - other people from my university might have the focus business processes and operating systems.

Thanks + cheers,
Tobi

**Comment by 2dvisio** [comment]
Should not this be called Major?

**Comment by PeterDaveHello** [comment]
:+1: @olivif
