### ISSUE TITLE
Additional fields for publications

### ISSUE THREAD

**Issue by mrbiber** [jsonresume/resume-schema#156]
For resumes with an academic component it would be great if publications would have the following (optional) fields:

- publication (name of the journal or volume the piece has appeared in)
- pages 
- issue
- [doi](http://www.doi.org/)

> "publications": [
>   {
>      "name": "A new discovery",
>      "journal": "Journal of Discoveries"
>      "issue": "3(1)"
>      "pages": "100-120",
>      "doi": "1.2.3.4.5",
>      "releaseDate": "2014-10-01",
>      "website": "http://...",
>      "summary": "...."
>    }
>  ]

**Comment by olivif** [comment]
bibJSON will probably cover this, if we end up going for it. #194

**Comment by chrisdotcode** [comment]
(thanks @olivif)
