### ISSUE TITLE
Add GeoJSON or lat/lng to Location

### ISSUE THREAD

**Issue by nolim1t** [jsonresume/resume-schema#157]
Seeing we have address/city/country may as well add lat/lng or a GeoJSON to Location. 

I know you could probably derive it from the GMaps API but saves on API calls if you could just specify this. Also not relying on external APIs is a plus too.

**Comment by DandyDev** [comment]
I think this is redundant information, and as such should not be _jsonresume_. As you mentioned, it can easily be derived through something like the GMaps API, and as far as I'm concerned, this is the job of whatever tool is interpreting your resume.json

**Comment by olivif** [comment]
we have agreed to switch to the address schema provided by #209, which I think should cover the intention of this issue :smile: feel free to re-open if I missed anything.

**Comment by aloisdg** [comment]
@nolim1t

In my secret utopia, address and the mess they represent don't exist and we only use logic, mathematics, concrete, amazing geocoordinates. Address, you sucks.

Sincerly,

@aloisdg.
