### ISSUE TITLE
Document required fields 

### ISSUE THREAD

**Issue by BrandonOCasey** [jsonresume/resume-schema#158]
It would be really helpful if we knew what was optional, what was required, what every field should/can look like and what it cannot look like. Right now I have a lot of things that I do not want to include/fill out but I am unsure if I can or should.

**Comment by jtwebman** [comment]
The schema tells you that. Nothing is required for the most part but you can't leave them blank.

**Comment by olivif** [comment]
hey @BrandonOCasey, @jtwebman is right, if you look at the [schema](https://github.com/jsonresume/resume-schema/blob/master/schema.json) you can see what type every field is. I don't think anything is required per say. 

Closing for now, feel free to ping us if you have any ideas on how we can improve the docs to make this clearer. Everything should be going through the CLI though, so let's continue the conversation there if needed :smile:

**Comment by chrisdotcode** [comment]
Re-opening as a reminder to document which fields are and aren't required (if we don't already).

**Comment by olivif** [comment]
I think the larger question here is what is the bootstrap experience for a new resume user? Do we provide a CLI method which will help you write your first draft (with required fields), think npm init?

**Comment by chrisdotcode** [comment]
Well, there are two categories of user: developer and non-developer. We currently provide a resume init, but as we've talked about, we might need to re-write the cli tool.

...However, it seems now we're talking about something different, so I'm going to close this up for now.
