### ISSUE TITLE
Allow multiple degrees at one institution

### ISSUE THREAD

**Issue by BrandonOCasey** [jsonresume/resume-schema#160]
Example

``` JSON
"education": [{
	"institution": "College A",
	"degrees": [{
		"area": "Web",
		"type": "Associates",
		"grade": "3.99",
		"startDate": "2014-01-01",
		"endDate": "2014-01-01",
                "courses": [
                ]
	}, {
		"area": "Games",
		"type": "Bachelors",
		"grade": "3.99",
		"startDate": "2014-01-01",
		"endDate": "2014-01-01",
                "courses": [
                ]
	}]
}]
```

**Comment by olivif** [comment]
by looking at the current schema, I see the design is for every item in the education section to be a degree, so the scenario that you mentioned would be supported by having something like 

    "education": [
	    { 
	    "institution": "College A", 
	    "area": "Web", 
	    "studyType": "Associates"
	    },
	    { 
	    "institution": "College A", 
	    "area": "Games", 
	    "studyType": "Bachelor"
	    },
    ] 

Personally, I would prefer this as opposed to having one item in the education section contain multiple degrees as it's more flexible.

**Comment by stp-ip** [comment]
I agree that a degree should be just duplicated with the same institution. In the opiniated draft #193 for v1.0.0 one institution can have multiple exams and multiple courses.

**Comment by olivif** [comment]
any other thoughts? 

@chrisdotcode @thomasdavis @PeterDaveHello

**Comment by stp-ip** [comment]
I would say same case as #91. It's already possible via multiple institutions and most likely is broad enough. Multiple degrees at one institution just complicate the schema without adding much additional info or value in my opinion.

**Comment by aloisdg** [comment]
I am against this proposition too (no arguments to add).

**Comment by stp-ip** [comment]
Will close as rejected for now. If there are good arguments against this decision please reopen.
