### ISSUE TITLE
Optional "skill keywords" per "work" or "work project"

### ISSUE THREAD

**Issue by nikolay** [jsonresume/resume-schema#162]
"Skill keywords" per "work project" are dependent of https://github.com/jsonresume/resume-schema/issues/161

I've interviewed hundreds of people and the last things I want to see is a global list of skills without any info on where (at what job) those skills were applied. It would be nice to be able to optionally specify which skills were applied at a job or project for more structured resume data and the ability to estimate recently and the time for which that skill had been applied.

**Comment by dannief** [comment]
+1

**Comment by mudassir0909** [comment]
+1

**Comment by sfrdmn** [comment]
+1

I've personally just added a 'keywords' key with an array of keywords to each work experience entry.

**Comment by petersandor** [comment]
+1

**Comment by stp-ip** [comment]
Just adding "label" for work/project/education/volunteer stuff would work for me.

**Comment by olivif** [comment]
we will cover this in the new issue.
