### ISSUE TITLE
Add an array field for summary of qualification or career highlights

### ISSUE THREAD

**Issue by dannief** [jsonresume/resume-schema#163]
This is similar to the summary field and this issue relates to issues #141 and #47.

In many resumes, especially one for technical positions, there is section that summarizes the candidate's experience or qualifications in a bullet-ed list. This would be different from the summary, which is usually a short sentence or two summing up the candidates qualifications and why they should be hired. (Though I see the usefulness of allowing multiple paragraphs a la #47)

I did a search on Google to find some samples. 

[This](http://sharongraham.ca/wp-content/uploads/Resume-GRAHAM-Thornton-1.jpg) resume shows the use of a summary section (currently in the schema) and a career highlights section (which I am proposing). [This](http://spot.pcc.edu/comptech/images/ressample9.gif) and [this](http://workbloom.com/resume/resume-sample-example-template-image/software-programmer.gif) also show examples of a bullet-ed list of summary of qualifications

The section could be called highlights

    {
        highlights: [
           "5 years proven track record of doing some awesome thing",
           "Invented a really useful tool to do something awesome",
          "Excellent communication skills in 5 languages"
        ]
    }

**Comment by olivif** [comment]
interesting idea @dannief, I think this content should definitely be in a resume in some form, but I'm not sure about having a separate section for it. if it was my resume, I would probably make sure these are bullets in the relevant work/education/projects sections and would stand out at a quick glance. 

i'm more in favour of grouping things by category rather than having a section which contains info about multiple categories of things.

**Comment by stp-ip** [comment]
As the discussion stands right now. We might have achievements within the different sections such as ```work, education etc.``` and additionally have a global ```achievements``` section instead of the awards section. So probably one has to move his nobelprice into achievements.

**Comment by chrisdotcode** [comment]
(answered by @stp-ip)
