### ISSUE TITLE
6 Month Milestone

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#164]
We're half way through our first year and a new round of schema updates will be happening, stay tuned!

**Comment by DandyDev** [comment]
Looking forward to them! There are a lot of issues and PRs open which seemed to have reached consensus, so you might wanna have a look at those (I tagged you in a couple of them).

**Comment by thomasdavis** [comment]
Yep sweet. I wonder if we should go a Google hangout to talk about direction and current issues.

**Comment by DandyDev** [comment]
I'm free from work tomorrow, so I could do a hangout then. We probably have to deal with a timezone difference here. I'm in _CET_. Who do you want to include in the Hangout? The core + standards team?

**Comment by opensourcegrrrl** [comment]
CET here too.

**Comment by thomasdavis** [comment]
Let's schedule for next week, will get a google calendar going.

**Comment by thomasdavis** [comment]
Also mention agenda items you would like here;

- Talk about the ethics of the organization's hosted database (People have asked for a search feature etc)

**Comment by jtwebman** [comment]
I would love to help out.

**Comment by olivif** [comment]
old thread, closing.
