### ISSUE TITLE
Add projects/activities to education

### ISSUE THREAD

**Issue by bluetomatoes** [jsonresume/resume-schema#166]
similar to [this](https://github.com/jsonresume/resume-schema/issues/38).
I personally am using JSON Resume for a high school profile, where the extra activities you do and outside projects matter to colleges or people offering internships. Any thought to add a projects and/or activities array to the education block, similar to courses?

**Comment by jtwebman** [comment]
+1 I like adding this!

**Comment by JaredCubilla** [comment]
+1

**Comment by natemacinnes** [comment]
+1

**Comment by igorkulman** [comment]
+1

**Comment by kevinbheda** [comment]
+1

**Comment by 2almalki** [comment]
agreed, It would be very nice to have!

Thanks

**Comment by rogue780** [comment]
I'm pretty sure this project is abandoned at this point.

**Comment by DandyDev** [comment]
Seems like it. @thomasdavis what are the plans for json-resume?

**Comment by stp-ip** [comment]
Seems similar to #11 just that projects should be a sub hierarchy for work, education and volunteer stuff.

**Comment by olivif** [comment]
I've included the proposition for projects on the education section in the new issue. I will close this one.
