### ISSUE TITLE
For template designers and perhaps to inform the schema, consider automated resume parsers

### ISSUE THREAD

**Issue by dilijev** [jsonresume/resume-schema#167]
I just found this website that suggests common headings for a resume so that HR systems that are manually searching through resumes are more easily able to find the appropriate information in a resume.

http://blog.cvlift.com/2014/10/resume-must-haves-and-good-to-haves-to.html

**Comment by jtwebman** [comment]
It would be nice to add some that are not covered like certifications.

**Comment by olivif** [comment]
I think the work that we are trying to do here is to define the way we want the schema to be, i.e. proposing a standard for people to follow. We should of course be informed in the choices we make, but the way I see it the automated parsers should align with our schema, once we get v1 out there and get some usage :smile: 

cc some folks to chime in here @stp-ip @thomasdavis @aloisdg

**Comment by aloisdg** [comment]
@dilijev Your link is dead. Neither archive.org nor googlecache can show it too.

---------

> HR systems that are manually searching through resumes

In my own secret utopia, HR know how to use SQL or any programming language. They will care about data to find people. A pretty CV, shouldn't win over a less pretty CV for an interview.

I am a carpenter, a fisherman or a developer. I don't want to learn how to lost time with word. I don't want to get a degree in design to make a personal CV.

Sincerly,

@aloisdg

**Comment by dilijev** [comment]
*shrug* this is an old issue. I didn't expect that link to go down, but it's not my site. I guess I should have included the points as text here. Feel free to close this issue.

**Comment by olivif** [comment]
@dilijev no problem! thank you for your contribution :smile: it's been a bit quiet here for a while so we are trying to get better at responding to issues. feel free to check out the new ideas for v1.0.0 though, if you are still interested in contributing.

**Comment by aloisdg** [comment]
@dilijev Thank you for you contribution by the way. Even if the website is closed, feel free to ad your point here or to browse different issues. Comments are always good to take.

**Comment by olivif** [comment]
@aloisdg seems like we are in sync today!

**Comment by dilijev** [comment]
Sure. I've been planning on building an interactive resume on my website, and I was looking into prior work on resume data formats.
