### ISSUE TITLE
add dissertation to education 

### ISSUE THREAD

**Issue by sirmmo** [jsonresume/resume-schema#168]
sometimes the dissertation work is very important, so adding it could be worth it.

**Comment by olivif** [comment]
what is the decision on this? I agree that having a dissertation/thesis field would be valuable, I'm also wondering if it makes sense to somehow merge this with the projects conversation (#201) as it might just be a project of a specific type. Also, not sure if this makes sense, but you might want to have multiple dissertations, for instance if you're doing a joint degree or you have multiple projects throughout your masters/phd. 

+ @chrisdotcode

**Comment by stp-ip** [comment]
I think this would fall into the publication section. It's not linked with the education per se, but this enables much more generic resumes and still provide valuable structure for thesis etc.

**Comment by chrisdotcode** [comment]
I agree with @stp-ip on this.

In my personal opinion, I would want my publications tied to *me*, as opposed to the university anyway. It's *my* work.

**Comment by olivif** [comment]
agreed, publications makes a lot more sense than projects, and not having it tied to the educations section :) I see publications are already supported, what do we do with this issue then?

**Comment by chrisdotcode** [comment]
I suppose I'll close for now.
