### ISSUE TITLE
Tagging of elements in work, volunteering, education, skills, awards, interests

### ISSUE THREAD

**Issue by sirmmo** [jsonresume/resume-schema#170]
it would be interesting to tag those elements in order to be able to filter out some elements to export a better fitting resume more easily

**Comment by jtwebman** [comment]
The schema does allow you to add any extra fields you want.

**Comment by stp-ip** [comment]
There is sort of a consensus to move tags into the metadata section. This decouples this "display" related data from the actual resume data.

Closing it in favor of the full discussion in #203
