### ISSUE TITLE
Add Support for badges

### ISSUE THREAD

**Issue by satyarths** [jsonresume/resume-schema#173]
Can support be added for badges like the Java certification and others.Sorry cant think of any other badges right now.Will edit and add soon.

**Comment by jtwebman** [comment]
Like an image url on the awards section?

**Comment by droidekas** [comment]
Yes.That would work at the most basic level.

**Comment by stp-ip** [comment]
I think the support for badges needs to be done on the theme side. We are most likely adding a ```source``` url type to a section designated to awards, certification or so. Will keep it open to track the actual ability to add badges.

**Comment by wayneamurphy** [comment]
I would say it is related to #177 , that it is a good idea but be in a more generic "achievement" section.

but I'm also really tempted to say "badges? we don't need no stinkin' badges" :-)
https://en.wikipedia.org/wiki/Stinking_badges

**Comment by evanplaice** [comment]
There is already an awards section and (hopefully) certifications will be added at a later date. Visual effects (ex logos, badges, icons) are strictly a templating concern.
