### ISSUE TITLE
Multiple websites at a single company

### ISSUE THREAD

**Issue by chrisgame** [jsonresume/resume-schema#174]
I know this has been discussed before for the basics section. But wouldn't it be better to have a websites  array under each work object? I have worked on multiple websites in my current role.

If not what do you think is the best way to represent this in the json structure?

**Comment by constantx** [comment]
I’d try breaking down each url to its own separate project if they have different goals :) Otherwise, if they’re all for the same goal, I think it’s not as helpful to list multiple of them anyway?

Maybe you can elaborate on your example?

**Comment by jtwebman** [comment]
I think it is more for what is the primary website. Not to show off what you have worked on. I would use publications to show off work if you wanted.

**Comment by olivif** [comment]
I would agree with @jtwebman , I would use a different category for showing off the websites you worked on (probably projects or some variation tbd #201) and keep the website in the work section for people to find out more about the company itself.

**Comment by stp-ip** [comment]
Depending on the outcome of a few discussions including, if we want projects within the work section, it could be possible, that a project under the section work has it's own url. Probably needs the outcome of #201 first as @olivif suggested.

**Comment by stp-ip** [comment]
I think with the coming addition of projects to some core sections, this can easily be done and does not warrant complicating the schema with website arrays. Example how it might work: https://github.com/jsonresume/resume-schema/issues/201#issuecomment-157872094

Please reopen, if this is not satisfactory.
