### ISSUE TITLE
Company description

### ISSUE THREAD

**Issue by matiassingers** [jsonresume/resume-schema#176]
It's very common to have a one-line description of the company and what they do:

**Company:** Google
**Description:** _Google is the leading search engine ..._

`companyDescription` could work for this property, since `description` would probably be confused with `summary`.

**Comment by opensourcegrrrl** [comment]
+1

**Comment by JaredCubilla** [comment]
+1

**Comment by thomasmktong** [comment]
+1

**Comment by olivif** [comment]
Could this be the first line in the work summary if needed? Personally, I am not a fan of a new field. It's not something I have in my CV currently either so maybe I am missing the use case.

**Comment by stp-ip** [comment]
I think it might be reasonable as we have a ```description``` field for various sections. I would keep ```description``` so.

The reasoning behind adding something like that would be:
For people hiring for a gardening position it would be valuable to know, that "gardapp" as a company was working in the gardening space etc.
Not that useful for bigger companies, but quite useful for smaller or mid-sized shops.

**Comment by olivif** [comment]
@stp-ip but in that example, wouldn't Gardner be the position held and wouldn't there be a "did some gardening" in the work summary? Basically what I am asking is, would the info in that field be redundant? :smile:

**Comment by aloisdg** [comment]
I am not against as an optional field.

**Comment by stp-ip** [comment]
It could be redundant, but also add a bit of an overview and value earlier.
So it might be more interesting to look for gardening companies on the resume and what the projects were, than to look at a restaurant, were the position might be gardening too, but it would not have been that varied.

Question is does it bring more value into it than clutter?
Using the +1s as a starting point there seems to be interest.

**Comment by aloisdg** [comment]
We have enough stuff for the v1. Lets send this to the a `next` version.

**Comment by stp-ip** [comment]
I would generally agree, but look at it again when finishing up v1. I assume that the description field there would feel more consistent with other sections.

**Comment by chrisdotcode** [comment]
Well, I think this a company description field is important enough to go in v1.0.0.

Think about this use case: A non-developer uses a theme, and prints their resume out and gives it to someone in meatspace. Whoever they gave it to might have never heard of those companies. A short brief description helps a lot, especially as @stp-ip says, other sections have them.

**Comment by aloisdg** [comment]
@chrisdotcode so +1 for consistence?

**Comment by stp-ip** [comment]
I think we agree and can look for a first iteration of an implementation.

**Comment by stp-ip** [comment]
Current proposal to implement:

* add ```companyDescription``` as fields for section ```work```

**Comment by stp-ip** [comment]
Done in #261
