### ISSUE TITLE
Work authorizations

### ISSUE THREAD

**Issue by telekid** [jsonresume/resume-schema#179]
Many companies will only hire foreign workers if those workers already have a work authorization. It is therefore vitally important that workers with authorizations are able to advertize that to potential employers.

``` json
"workAuthorizations": [{
  "nation": "The United States",
  "authorization": "H1B",
  "expires": "2016-1-1"
}]
```

**Comment by MyBoon** [comment]
+1

**Comment by opensourcegrrrl** [comment]
The "expires" value needs to allow for non-numeric values. For example, my residency and work permit in Germany is "Unbefristet".

**Comment by MyBoon** [comment]
*Unbefristet* means *permanent* right?
If so, I will suggest to put the expires field as optional (or the value to null?).

I can see other examples like @opensourcegrrrl... green card in the US is one of them.

**Comment by opensourcegrrrl** [comment]
It is valuable information to include terms such as _unbefristet_ or _permanent_ to note specific that there is indeed no expiration date.

**Comment by olivif** [comment]
this would fit into the dispositions object that @stp-ip is proposing in #205

**Comment by wayneamurphy** [comment]
Agree it is similar to #205.
How does it work for some visa or other foreign workers, isn't the visa company specific - so if they switch companies somebody would still have to do some paperwork? I would think that should included.

**Comment by thomasdavis** [comment]
It makes a lot of sense. We are trying to release a `v1` so I'm going to close this for now and hope that more debate will happen at some time. I do personally believe you can explain your authorizations in your cover letter.
