### ISSUE TITLE
Support yyyy-season date format

### ISSUE THREAD

**Issue by telekid** [jsonresume/resume-schema#180]
I've noticed that many people use seasons to describe their career history. A user might say that they started working at a company in the Fall of 2015, for example. 

Would it be helpful to build this into the schema? Does anyone have a suggestion for how we might go about doing this? It's a tricky problem, since seasons come with their own localization headaches, plus their start- and end-dates often change from year to year.

It's obviously very easy to render a YYYY-MM-DD date as YYYY-Season, but I'm having trouble thinking about how to do the opposite – that is, if we allow users to input a date as YYYY-Season, how do we store that?

Adding a "season": field feels a bit silly.

**Comment by RobertMortimer** [comment]
From the schema the field is a date type ("format": "date"). Putting non date information into this field will compromise the ability to sort and other bulk operations.

**Comment by DandyDev** [comment]
I'm against this. It hurts machine-readability, and deviates from a known standard: dates.

**Comment by publysher** [comment]
There is a machine-readable proposal for ISO 8601-compatible seasonal dates: http://www.loc.gov/standards/datetime/pre-submission.html#season 

Furthermore, not sure if this should be part of this specific issue: what exactly are the requirements for the 'date' format? It is not part of the JSON Schema specification, and the themes on jsonresume.org only seem to work with yyyy-mm-dd dates.

**Comment by MyBoon** [comment]
agreed with @RobertMortimer @DandyDev @publysher.

**Comment by aloisdg** [comment]
agreed to be against season (for now).

**Comment by chrisdotcode** [comment]
@publysher The requirement (going forward) of a `date` is that it is to be a valid [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string.

**Comment by chrisdotcode** [comment]
As @KOLANICH [says](https://github.com/jsonresume/resume-schema/issues/198#issuecomment-157035842),

> "spring`2015" will be Sept, Oct, Nov in countries in the southern hemisphere. Or "summer`2015" will include May in Britain but won't in Russia. If you mean session in educational institutions it also will have another boundaries.

Therefore, the representation of seasonal dates is ambiguous. Rejecting.

**Comment by stp-ip** [comment]
Addition: If one wants a representation of seasons it would be frontend only and not supported via the schema or data itself as far as the consensus goes.
