### ISSUE TITLE
add an internship field

### ISSUE THREAD

**Issue by doodzik** [jsonresume/resume-schema#181]
The work field doesn't cover internships properly.
Your position isn't being an intern, but rather you do an internship in a position.

**Comment by MyBoon** [comment]
Even if I agree with you, I'll think that the *position* field is enough for this.

```js
position: "Software Engineering Intern"
```

A [lot of companies](https://www.linkedin.com/job/software-engineering-intern-jobs/) are using this type of designation.

**Comment by doodzik** [comment]
This looks fine.
