### ISSUE TITLE
Improve schema validation error messages 

### ISSUE THREAD

**Issue by philippnagel** [jsonresume/resume-schema#182]
When trying to publish I get the aforementioned error. What is expected? 

http://jsonlint.com/ judges my file as valid .json. Any hints?

**Comment by syjulian** [comment]
I am getting the same error too

**Comment by trent-boyd** [comment]
When I got this error, it was because my `startDate` and `endDate` weren't in the proper format. It expects it to be in the `YYYY-MM-DD` format.

Seems you can get around this by running `resume publish --force`. It'll check the JSON syntax only.

**Comment by olivif** [comment]
seems like a CLI issue. is this still happening? sounds like we might need a better error message at least :smile:

**Comment by aloisdg** [comment]
Definitely a CLI problem.

**Comment by olivif** [comment]
I have filed this on the CLI repo, it's probably something that we will need to support across both schema and cli. Probably need to surface the errors better on the schema side and handle them appropriately on the CLI. I will keep this issue as a reminder on the schema side.

**Comment by aloisdg** [comment]
:+1:

**Comment by chrisdotcode** [comment]
Well, we're in the process of fixing this all, so I'm going to close this for now. If anyone disagrees, or has any additional information, just comment, and I'll reopen.
