### ISSUE TITLE
Allow import from or implement Citation Style Language/citeproc-json for publications 

### ISSUE THREAD

**Issue by cameronneylon** [jsonresume/resume-schema#183]
I came across the jsonresume project while noodling around the idea of a "CV style language" for academic CVs. These often need to be in PDF form to specific formats. There is an existing widely used toolchain for citation styling in academic setting, [citation style language](http://citationstyles.org/), with an associated schema and a range of json interchange formats supported.

While the intent behind CSL and jsonresume is a little different it would be great both to bring these projects together and to utilise the existing tool set for managing and formatting citations.

**Comment by KOLANICH** [comment]
I think this issue should be in the repo of the tool, because the resume doc shouldn't include styling information.

**Comment by stp-ip** [comment]
I agree, that is most likely a /resume-cli issue, if we would wanna support something like that.

**Comment by chrisdotcode** [comment]
That is correct. However, the suggestion of using a citation style language is a schema issue.

**Comment by KOLANICH** [comment]
Why? Citation style is not about storing the information, it is about showing it to consumer. Any citation style format can be used and the schema of jsonresume doesn't depend on it.

**Comment by chrisdotcode** [comment]
In that case, I think I might have misunderstood, then.

**Comment by olivif** [comment]
Maybe I am missing something here, but I don't understand how this fits into the resume part. Is "citation styling in academic setting" something needed in a resume? Be it schema or cli or style.

**Comment by stp-ip** [comment]
I'm closing this for now, as with the current information we have, it should be recreated in [resume-cli](https://github.com/jsonresume/resume-cli) or doesn't apply to the resume standard.

Please reopen with more information, if we misunderstood the intend.
