### ISSUE TITLE
Add a 'summary' to education (like for work)

### ISSUE THREAD

**Issue by 2dvisio** [jsonresume/resume-schema#185]
Most of the time, especially in the academic/reasearch field, it makes sense to have a description/statement that describes what you have learned/done/found at the specific institution.

I am thinking about dissertations/thesis for MSc/MD/PhD and so on.

**Comment by aloisdg** [comment]
@2dvisio Thank you for the proposition. We look to add it in the v1.

**Comment by phumke** [comment]
I like the idea.  To be consistent with a couple of the other sections, thoughts naming it "description" instead of "summary"?

**Comment by aloisdg** [comment]
@phumke yes. cc @stp-ip

**Comment by olivif** [comment]
+1

**Comment by stp-ip** [comment]
I think we can agree on having some fields within the main sections as a base: ```name```, ```description```, ```website```, ```$dates```, ```highlights``` and perhaps ```keywords```.
I formed this into a separate issue: #223
