### ISSUE TITLE
A C# implementation of resume-schema

### ISSUE THREAD

**Issue by aloisdg** [jsonresume/resume-schema#186]
Hello,

First sorry if I am a bit off topic.
I created a Portable Class Library to handle the resume-schema in C#.
I called this project [SharpResume](https://github.com/aloisdg/SharpResume).

I would love any feedback on my work. Keep in mind that the project is quite young. I started it this weekend.

Cheers,

**Comment by thomasdavis** [comment]
This is awesome, going to dive in later!

**Comment by aloisdg** [comment]
@thomasdavis Thanks! Do you know if they are any projects in another language?

**Comment by chrisdotcode** [comment]
@aloisdg We could eventually have a list of parsers for the schema in the README of this project.

Until then, I'm going to close this to reduce some issue clutter. Just remind me about this later :)

**Comment by aloisdg** [comment]
Sure :+1:

**Comment by hacksalot** [comment]
Excellent work @aloisdg. I've forked a copy and with your permission would like to integrate this with one of our back-end systems over at FluentCV. Will email you privately -- thanks.

**Comment by aloisdg** [comment]
@hacksalot Glad you like it. :)
