### ISSUE TITLE
New version of the schema

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#187]
When we started the project we said we would have slow release times to allow to the ecosystem to grow. There has been plenty of active discussion over the past year so I will be going through the issues in the next month and cleaning things up.

Keep up the good work!

**Comment by MyBoon** [comment]
Thanks for your work @thomasdavis :)

**Comment by stp-ip** [comment]
I am working on a preliminary draft #193 to make it easier to see the suggestions as a whole and make it easier to discuss the different sections.
There is still a bit of work left and I will try to finish it up today.
Still missing:
* [ ] work (+projects)
* [ ] add additional information to work and project sections
* [ ] volunteer -> experiences
* [ ] make experiences more abstract
  * [ ] possibility to integrate abroad experiences
  * [ ] possibility to integrate event orga
  * [ ] possibility to integrate projects
  * [ ] possibility to integrate non-profit
* [ ] add additional information to experiences section
* [ ] add certification
* [ ] authorization (greencard, etc.)

**Comment by opensourcegrrrl** [comment]
A huge PR is hard to approve. +1 for smaller PRs.

**Comment by stp-ip** [comment]
@opensourcegrrrl was more a way of showcasing what it could look like. Or better a summary of the already done discussion and ideas formed into a schema.
Not specifically a PR to be merged, but perhaps to discuss the spec and afterwards either split it up or built on top of it.

**Comment by opensourcegrrrl** [comment]
w00t

**Comment by stp-ip** [comment]
Any update on the new version @thomasdavis or how one could help?

**Comment by chrisdotcode** [comment]
I am likewise volunteering to help.

**Comment by olivif** [comment]
v1.0.0 work on-going now. let's do this! :smile:
