### ISSUE TITLE
Validator callback should use continuation-passing style

### ISSUE THREAD

**Issue by matmar10** [jsonresume/resume-schema#189]
Overview
====

CPS (continuation passing style) is the default in Nodejs. It is what is expected by default, everywhere. Breaking this convention will cause unnecessary confusion with developers seeking to use this library.

Steps to reproduce
====

```
var resumeSchema  = require('resume-schema');
resumeSchema.validate({name: "Thomas"}, function (err, result) {
    if (err) {
        console.error('Resume was not valid:', err);
        return;
    }
    // use the result
});
```

Expected behavior
====

- Error passed in the first argument, if any
- Result(s) passed in the second argument

Actual behavior
====

- Error is passed in the second argument
- Result is passed in the first argument

**Comment by chrisdotcode** [comment]
Resolved in #190.
