### ISSUE TITLE
Abroad experiences/experiences

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#192]
There are already various suggestions for experiences, but they seem to be more similar to volunteering work (just with a less non-profit spin) #123.
What I am still looking for is abroad experience. Which is not really some project or education (not per se), but student exchanges, work+travel or something. Not really for showcasing the work/project done, but the experience and probably the value for the language level.

**Comment by aloisdg** [comment]
How will you represent this on a standard resume?

**Comment by stp-ip** [comment]
I would represent that as "abroad experience" with a small summary about the benefit for me for my language level or work ethic or whatever. Not sure how it would fit in the the schema so.
As most of the non-professional experiences and even the volunteering stuff talks about companies/projects. One could use the company field to define "Abroad Experience" or something, but that seems quite wrong.
Hope that makes clear, what I think is missing.

**Comment by francescoes** [comment]
To be relevant for a cv an abroad experience is generally education or work experience. 

It is possible to add your abroad experience there. Even Linkedin doesn't have such a field. In my opinione it is not needed.

**Comment by stp-ip** [comment]
@francescoes it just seems a bit hard to integrate it into education etc. Will try to merge them in my latest draft. (aka will remove experiences and merge into education or projects) #193 
Thanks for your input.

**Comment by francescoes** [comment]
You're welcome. Big changes are not needed in the schema and having a backwards compatibility is important, in your way all the themes that people developed are rubbish. 
The schema should be improved, not remade 

if location and summary will be included in education and work I don't see any problem:

```
  "institution": "University of Portsmouth",
    "area": "Computer Science",
    "studyType": "Exchange BSc ",
    "startDate": "2014-09-20",
    "endDate": "2015-06-30",
    "location": {
      "city": "Portsmouth",
      "countryCode": "EN",
      "region": "England"
    },
    "gpa": "100/100",
    "summary": "The erasmus was a great experience..... bla bla bla"
    "courses": ["Databases",  "Object Oriented Programming", "Web Development", "Marketing"]
  }],
```

**Comment by olivif** [comment]
hmm interesting idea @stp-ip . I can see where you are coming from, I can think of a few examples of people who have very diverse cultural experiences and why you would want to get that across in a resume. 

i'm not sure about having a separate category for it though, as it seems like it would be a bag of different types of things where the only connection between them is the fact that they were done in a particular country/language. I would also suggest including things like Erasmus, work and travel as part of the regular education/work categories, but maybe making sure the locations/languages are emphasised enough to get the message across.

**Comment by chrisdotcode** [comment]
I agree with @olivif.

The only difference between "hacking here in the US" and "hacking over there in Spain" is the language - which, as she suggests can be noted in other fields.

**Comment by stp-ip** [comment]
I moved to my drafted suggestion to include abroad experiences either in the ```education``` section for language learning or most likely into ```projects``` and use highlights/achievements within this project to add an emphasize on the cultural and language experience.

**Comment by chrisdotcode** [comment]
Sounds good.

**Comment by olivif** [comment]
awesome!

**Comment by aloisdg** [comment]
Nice

**Comment by olivif** [comment]
Seems like we agree to include the abroad experiences into other sections such as `education`, `work` or `projects`. Closing.
