### ISSUE TITLE
Languages skill levels

### ISSUE THREAD

**Issue by KOLANICH** [jsonresume/resume-schema#195]
Add to the specification the results of well-known tests and metrics. To do it
1 make `languages`  an object
2 the key must be a 2 letter language code
3 every language must be an array of metric results, every metric result is an object with fields representing results.
4 for expiring tests the date of pass is required
for example
```json
{
...
 "languages":{
   "en":{
    "CEFR":{
     "listening":"c1",
     "reading":"c1",
     ...
    }
  }
 }
}
```

**Comment by aloisdg** [comment]
There is already a [discussion for this](https://github.com/jsonresume/resume-schema/issues/34). I think, you can move your message to #34 and close this issue. I recommend you to read the whole discussion. By the way, thank you for your input and I agree with you ;)
