### ISSUE TITLE
Add credentials to references

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#2]
Employers would like to be able to contact and do due diligence on references sometimes, but of course a candidate might want to make referrals available upon request etc.

**Comment by DandyDev** [comment]
+1 on making reference contact information private.

**Comment by opensourcegrrrl** [comment]
+1 on making reference contact information private.

**Comment by MyBoon** [comment]
+1 on making reference contact information private.

**Comment by olivif** [comment]
So to summarize, we agreed on: 
1. references and testimonials are handled in the same category
2. reference contact information should be private 


What we haven't agreed on:
3. what the category is called (references, testimonials or other)
4. whether description should be renamed to relationship 

for 3 I would vote for `references`
for 4 I am on board with `relationship`

@chrisdotcode should I tag this as v1? does every proposed modification/new feature go into v1 automatically, regardless of whether we go with the change or not? or do we wait to make a decision and then tag as v1 if it gets approved? :smile: 

+folks @stp-ip @PeterDaveHello @aloisdg

**Comment by aloisdg** [comment]
Everything looks good for me.

**Comment by stp-ip** [comment]
The question is how should we prevent the contact details of references to be private. When there is data it might leak. So either we are comfortable with the possibility of misuse/leakage or we should prevent personal data from !someone! else to be added.
I think Name, Position, Company, Date would be acceptable everything else is data, which might not be  valid anymore or is too private to publicly make available.

Addition:
* Undecided concerning the category.
* Relationship is something I am not sure about. Not sure how much more value a reference is for things such as ```customer```, ```boss```, ```collegue``` etc.

I would say adding the v1 milestone to the issues we want to have solved for v1 right away and then it can be solved within the v1 milestone.

**Comment by chrisdotcode** [comment]
@olivif I'd say use your discretion: if it's a feature we can realistically put in v1.0.0 in a good timeframe, and it's reasonable, let's add it (and don't forget to update the master v1.0.0 issue). Otherwise, it can sit around for a bit longer.

As for this issue, we need to solidify what fields we want first (by providing an example), before we decide on whether or not they should be private. As @stp-ip said, if someone wants that data to be private, just omit that field - not that we need to eliminate the field entirely.

My example from skimming this thread (but mostly my own personal opinion is):

`reference: {
name: "Chris Blake",
phone: "555-555-5555",
email: "chris@example.com",
relationship: "Benevolent Dictator for Life",
additionalInformation: "He once threw a rock and took out a ship"
}`

Feel free to agree/disagree, but please provide examples.

**Comment by stp-ip** [comment]
My opinion was more in the direction of:
We should not make it easy to do something bad by making it easy to publish -other- people's private data.
Therefore I still vote for the info being private by default on exports instead of leaving it to the user to omit it.

Concerning the fields I still have to think about that.

**Comment by chrisdotcode** [comment]
If someone gives you their private data, they are already totally trusting you with it. If the user knows their resume is going to be publically listed, why are we protecting them from themselves by making information they put in themselves "private by default"?

**Comment by stp-ip** [comment]
I think we should not make the assumption, that this private data was trusted to you to be published (at least not publicly). Therefore I think we should make the effort to reduce private data from leaking aka. from being published by mistake.

I agree that the user puts reference information in there to be consumed, but I don't agree that the other people's info is meant to be publicly available.

As an example:
Rabbit worked at Google and got a reference from Larry Page, with a private phone number.
He mistakenly published that phone number via an export to html and published it openly on the web.
A search engine comes along and saves it permanently into it's index/cache.
Larry is now at a huge disadvantage.

Sure this could happen even, when we default to it being private, but at least we tried.

As we are trying to push a standard, we should have sensible defaults, which reduces worst case scenarios.

**Comment by chrisdotcode** [comment]
So why would references be in the resume in the first place if you put them in, for them not to be consumed?

Saying that reveals my true thoughts about the matter: I personally think references should be removed entirely. I didn't use the field anyway for pretty much that reason, and references vary depending on what for, and what job/application anyway.

I think removing the field solves the issue entirely.

**Comment by stp-ip** [comment]
I have no opinion on references and would probably say, that reference data should be interchanged individually as this data might change etc.
But if there are references, then I still argue my privacy point.

References can be consumed, they should just not be easily published publicly.

Let's hear some other views, but removing them seems like a good solution. I dislike having other people's information in my resume.

**Comment by chrisdotcode** [comment]
Didn't someone discuss an extension/plugin system? If we decide we want those, references (and other features some want and some don't) can go there, and the main schema can be kept nice and tidy.

If we *do* go for a plugin schema, we'll have to make sure that a resume.json with additional fields/values/etc. only parses the standard schema fields, and doesn't complain about those additional fields and/or those other fields can be put in the metadata.

**Comment by hc-12** [comment]
I think references should be private as default with an option to explicitly expose references through command line:

`resume export resume.pdf --include-references`

or something to that affect.

You probably need some sort of meta data tag to indicate that this is private information.

**Comment by stp-ip** [comment]
Thanks @hc-12 for your help and interest.

I still think that all references should be private by default and need to be explicitly made public similar to what hc-12 suggests.

As with other meta data this could be done in the ```meta``` section.
I think having the references and extended user information as non public by default is a good starting point. They can be made public via a field within the ```meta.$good_description``` section or a flag could be set on an individual cli command basis as hc-12 suggested.

**Comment by stp-ip** [comment]
Revisiting this:

The main concern for data about other people being public is still there. Additionally with the usage of the new meta section it feels wrong to have other peoples data within your own resume.
In my opinion the resume itself should feature your data, your projects, your work history. This would include references as they are comments about your work, but the actual data (address, phone, mail etc.) of the people referencing, should be separated from that. 

I propose to have a meta data section for contact information about your references. This is also changing data and could perhaps be automated by a tool later on or automated from a platform provider.
We need to wait for a decision on the subsection for the meta data section. Will add more information, when this is done.

**Comment by stp-ip** [comment]
Current (not complete agreement) proposal:

Have references with no private data within the schema in the ```references``` section.
Extended private data (contact, address etc.) for references might be added within the metadata section under ```meta.schema.references```
Make/publish meta.schema.references only with additional cli flag: (--include-private-reference-data or such)

The actual data schema of the private reference data still needs to be added below:
...

**Comment by briankotch-invisionapp** [comment]
What about tagging the reference so it doesn't get exported? I can see good value in marking information private and not fit for export - might not want linked in recruiters snooping contact info or something along those lines. But there's specific audiences I'd want to export reference information for, like the resume I am sending to jobs.


I'm playing around with a golang utility building off of the json resume spec. I'm kicking around ways to control which information to export where. I'm definitely going to look into the schema, but it'd be awesome to be able to mark ANY field on the resume with a tag like "private" or "developer" or "sales" -etc

**Comment by stp-ip** [comment]
For filtering you can look at: https://github.com/jsonresume/resume-schema/issues/203#issuecomment-161626244 and the discussion in this issue in general.

**Comment by stp-ip** [comment]
Also thought about rewriting some stuff in golang. Maybe making it easy to build themes via hugo and add jsonresume as data source. Time is just a limited ressource :(

**Comment by chrisdotcode** [comment]
I'm going to close this now because JSON Resume has highly likely obsoleted this in some manner in the interim. If some of what was original discussed is still relevant, then please feel more than welcome to create a new issue/PR that's more relevant to where JSON Resume is now.

Thanks, all!
