### ISSUE TITLE
Adding conferences/presentations/talks

### ISSUE THREAD

**Issue by alexeyraspopov** [jsonresume/resume-schema#20]
As a speaker on local conferences I want to describe my experience in resume. Something like:

``` json
"talks": [{
  "conference": string,
  "date": string,
  "title": string,
  "link": string // e.g. link to video
}]
```

Example:

``` json
"talks": [{
  "conference": "JSConf EU 2013",
  "date": "2013-xx-xx",
  "title": "Stop Breaking the Web",
  "link": "https://www.youtube.com/watch?v=OSEXpsVcTxI"
}]
```

I think this section can be useful.

**Comment by stp-ip** [comment]
Definitely a must have. I am all for the use of event. Perhaps we should differenciate between event website and video url.
```
"talks": [{
  "event": string,
  "website": string, // e.g. link to event website
  "date": string,
  "title": string,
  "slides": string // e.g. link to slides
  "recording": string // e.g. link to video/recording
  }]
```

**Comment by stp-ip** [comment]
So for now it seems the consensus in other threads was to merge events and talks into projects.
Going to close this for now. Might be revisited in further iterations.
