### ISSUE TITLE
Upgrade z-schema

### ISSUE THREAD

**Issue by PeterDaveHello** [jsonresume/resume-schema#202]
According to z-schema's readme, the new version(v3.x) is much faster than the 2.x, and v2.x is somehow a little bit out dated and old.

**Comment by olivif** [comment]
@PeterDaveHello any idea what the implications of this would be for the code? any api updates to `z-schema` that would need changing some `resume-schema` code or is this just a version bump and test pass to make sure nothing is broken? :smile:

**Comment by chrisdotcode** [comment]
Seems like the later, @olivif .

**Comment by PeterDaveHello** [comment]
I haven't take a look at it yet, pass the test is important, and should becare if there is breaking changes. @olivif would you like to join jsonresume organization? I saw you been active in this project!

**Comment by chrisdotcode** [comment]
@PeterDaveHello Don't forget about @stp-ip

**Comment by olivif** [comment]
@PeterDaveHello that would be amazing, thanks for the invite! I try to be active as time permits, I really belive in what we are trying to do here and it would be amazing to be part of it (officially) :smile:

**Comment by olivif** [comment]
@chrisdotcode, yeah I was hoping it was that. Should we make this PR needed?

**Comment by PeterDaveHello** [comment]
@olivif I invited you. @chrisdotcode I can invite @stp-ip also if he want to join. :+1:

**Comment by olivif** [comment]
thanks @PeterDaveHello, much appreciated! :smile:

**Comment by stp-ip** [comment]
@PeterDaveHello I would love to join, would make it possible to reduce the work for @chrisdotcode closing issues others point out.

**Comment by chrisdotcode** [comment]
The reason I haven't been as active with code changes as of late is because I've been a bit busy - this should change after the holiday season. Nevertheless, it will become a lot easier with you guys helping out :)

**Comment by PeterDaveHello** [comment]
Okay I invited you @stp-ip, welcome to aboard.

**Comment by chrisdotcode** [comment]
Hey @stp-ip and @olivif, just as a note, let's finalize all resume-schema issues + features *first*, before changing anything else, because all other projects are dependent on the schema. So if we were to change the cli first, and then make a change to the schema afterwards, we'd have to adjust the cli again, in order to implement the new change.

**Comment by PeterDaveHello** [comment]
Hey @olivif & @stp-ip do you have a twitter account?

**Comment by olivif** [comment]
@chrisdotcode that makes sense. 

@PeterDaveHello yeah, I'm over [here](https://twitter.com/olly2204).

**Comment by chrisdotcode** [comment]
Hey, @PeterDaveHello, if you're sending out gitter invites, I "misplaced" mine. My twitter is [@chrisdotcode](https://twitter.com/chrisdotcode).

**Comment by stp-ip** [comment]
I am [@stp_ip](https://twitter.com/stp_ip)

**Comment by stp-ip** [comment]
Done with #279 and #265.
