### ISSUE TITLE
Add disposition data

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#205]
I find the idea of having disposition data similar the one used in FRESH should be discussed.

```
    "disposition": {
      "type": "object",
      "additionalProperties": true,
      "properties": {

        "travel": {
          "type": "integer",
          "description": "Percentage of time willing to travel (0 to 100)."
        },

        "authorization": {
          "type": "string",
          "description": "Work authorization: citizen, work visa, etc."
        },

        "commitment": {
          "type": "array",
          "additionalItems": false,
          "description": "Types of work commitment desired: contract, perm, seasonal, etc.",
          "items": {
            "type": "string",
            "description": "One of: contract, permanent, part-time, seasonal, full-time."
          }
        },

        "remote": {
          "type": "boolean",
          "description": "Open to remote employment opportunities."
        },

        "relocation": {
          "type": "object",
          "additionalProperties": true,
          "properties": {

            "willing": {
              "type": ["string","boolean"],
              "description": "Willingness to relocate."
            },

            "destinations": {
              "type": "array",
              "description": "Preferred destinations for relocation",
              "additionalItems": false,
              "items": {
                "type": "string",
                "description": "City or area of relocation."
              }
            }
          }
        }
      }
    },
```

source: https://github.com/fluentdesk/FRESCA/blob/master/schema/fresh-resume-schema.json#L57 
Willingness to travel, remote work ability/only, relocation etc.

Not sure if that's generic enough, but should be discussed at least.

**Comment by aloisdg** [comment]
As a french dev living in India looking for remote work, I second this!

**Comment by olivif** [comment]
Sounds like a good idea @stp-ip. Would definitely avoid some of the awkward relocation conversations I've had way too late in the job application game.

**Comment by chrisdotcode** [comment]
So what is a "disposition" in this context?

**Comment by stp-ip** [comment]
@chrisdotcode the applicants relocation preferences. If he would be willing to relocate and where to.

**Comment by chrisdotcode** [comment]
The first step will solidifying *all* of the fields that go in the `disposition` section, if we decide to include it.

The suggested so far are: `travel`, `authorization`, `commitment`, `remote`, `relocation`, and `destinations`. Let's keep in mind also that not every resume will have, need or want a disposition entry and spec out accordingly.

**Comment by chrisdotcode** [comment]
Closing because JSON Resume has highly likely obsoleted this in some manner in the past 5 years. If some of what was original discussed is still relevant, then please feel more than welcome to create a new issue/PR that's more relevant to where JSON Resume is now.

Thanks all!
