### ISSUE TITLE
Enable `resume-schema` to be loaded as a NPM script

### ISSUE THREAD

**Issue by evanplaice** [jsonresume/resume-schema#206]
## Specification:

*Requirements:*
- [ ] a CLI wrapper that can launches from `./bin`
- [ ] specify a `bin` command in package.json so the validator can be run as a NPM script

Add the following script...
```
./bin/resume-schema.js
```

Run the script from...
```npm run resume-schema validate [path]```

*Reasoning:*
When `resume-schema` is included as a dependency, this change will expose the capabilities of `resume-schema` to be run from a NPM script.

For further info on how NPM scripts are implemented/used see [Running scripts with npm](http://www.jayway.com/2014/03/28/running-scripts-with-npm/).

Possible future extensions...
- ```resume-schema init``` - create a new resume.json file from the command line

**Comment by olivif** [comment]
hey @evanplaice, interesting idea with the live editor! :smile: 

so, basically you want to be able to use resume-schema programmatically? If I am not mistaken I believe this is already supported and used in json-resume - have a look at [test.js](https://github.com/jsonresume/resume-cli/blob/455608ebd2ef0bcaafaf850214db16f172064490/lib/test.js).

**Comment by evanplaice** [comment]
@olivif Sort of. Make it accessible from the command line.

Here's an example workflow:
- I create a new GH repo to host my resume
- `npm init` - to get a basic package.json setup
- `npm install --save resume-schema` to add the schema as a dependency
- `npm run resume-schema init` to setup a basic resume.json scaffold
- edit the resume.json
- `npm run resume-schema validate ./myresume.json` to validate the structure

To speed up the process I could add a npm script that hardcodes the command used to validate, so future validations can be done with `npm run validate`

The resume-cli project is more of a fully featured tool to generate different formats from a resume.json file. This addition may be beneficial to that project but the focus here is strictly limited to creation/validation of the json file.

It's not uncommon for Node scripts to also include a CLI component. Doing so allows users to chain commands together to automate processes that would otherwise need to be handled manually. For instance, the resume output could be setup as an automated build process that's nothing more than a chain of scripts.

**Comment by hacksalot** [comment]
Yeah or the reverse, for Node CLIs to include a script API.

```javascript
// package.json
{
  "name": "my-resume-tool",
  /* ... */
  "main": "path/to/api.js",
  "bin": {
    "cli1": "path/to/cli1.js",
    "cli2": "path/to/cli2.js"
  }
}

// elsewhere
var api = require('my-resume-tool');
```

**Comment by chrisdotcode** [comment]
So @olivif said best, this is a feature for the cli, and goes hand-in-hand with the future addition features like `add work`, `validate`, etc.

The schema is nothing more than the schema, and the validator for such. All actually functionality goes in the `resume-cli`.

Thanks for the contributions!

**Comment by olivif** [comment]
thanks @chrisdotcode!

@evanplaice yes, your workflow sounds like exactly the kind of thing resume-cli should be doing :smile: The way I think of it is, we have a bunch of components (schema being one of them) and they all come together in the CLI, which is the *public API* if you will.

**Comment by evanplaice** [comment]
:+1:
