### ISSUE TITLE
Nickname / acronym: JARS

### ISSUE THREAD

**Issue by hacksalot** [jsonresume/resume-schema#207]
**J**SON **R**esume **S**chema = **JRS** by default, but there's some justification for introducing a vowel that isn't represented by a word if it makes the acronym [more memorable, sonorous, or pronounceable](https://en.wikipedia.org/wiki/Lenition). **JARS** feels a bit stronger than **JRS** or **JaRS**, is easier to pronounce than "Jay Are Ess" or "JSON Resume", and has that connotation of containerness. It would also ease language around the JSON Resume format whenever the word "resume" would be redundant. Compare:

      > Submit your LinkedIn or JSON Resume-format resume to our HR department...

      > Submit your LinkedIn- or JARS-format resume to our HR department...

Left to their own devices, writers will end up using **JRS** anyway, so why not buy a vowel and gently steer people toward the more familiar and pronounce-able of the two acronyms?

(Sorry if this is the wrong place for this -- more of an identity issue than a schema issue.)

**Comment by aloisdg** [comment]
I think we should only use Resume. Today it is in json, but tomorrow we can port it in another format (if this new format is better). For now, I don't really care about the name. For me, JsonResume is fine.

**Comment by hacksalot** [comment]
Agreed but I think if it's more than one word (=JSON Resume Schema) people will acronym it anyway. I'm not married to the JRS/JARS acronym but it would be nice to have an officially sanctioned shorthand..

**Comment by KOLANICH** [comment]
I think we should leave it as `JSON Resume`.
>Submit your LinkedIn or JSON Resume to our HR department...

**Comment by hacksalot** [comment]
I agree it should always be spelled out (`JSON Resume`) for anything official. What about the default JRS without the A? Officially-sanctioned acronym or..?

**Comment by chrisdotcode** [comment]
I don't believe there should be an "official" acronym.

As for a name change, I'm fine with either leaving it as "JSON Resume" per @KOLANICH , or "Resume" (because we're not *technically* married to JSON) per @aloisdg.

If we want to leave "JSON" off, "Resume" might be too generic, and we might need to rebrand anyway.

**Comment by hacksalot** [comment]
I opened this issue more to get some clarification around the acronym, not to suggest a name change, but I think @aloisdg and @KOLANICH both have a point. "JSON Resume" ties the standard to a specific format and introduces a word (JSON) that mainstream audiences won't understand or want to understand, but I also don't think you can just drop the "JSON" leaving "RESUME". If there's any rebrand, IMO it should be a lateral move to a name that's more approachable by non-techies, but it's a bit late in the game to do that on a whim. I'm fine with closing this issue if nobody has any objections. Thanks all~
