### ISSUE TITLE
Change location type from object to http://json-schema.org/address# 

### ISSUE THREAD

**Issue by olivif** [jsonresume/resume-schema#209]
I was going through open PRs and found an interesting suggestion from @madskristensen  - PR #113 

He is suggesting changing the type of location from `object` to [`address`](http://json-schema.org/address#). 

This would probably be a bit more standardized, as opposed to creating our own type of location. Any thoughts? :smile:

**Comment by stp-ip** [comment]
I am not sure where it was proposed initially, but for the next release I think we agreed upon using the json schema for ```address```. So +1. The PR itself won't probably suffice as the location needs to be added to all subsections anyway: #63

**Comment by olivif** [comment]
@stp-ip , excellent! I was not aware. That is true, PR #113 also has failing tests so it's probably a larger change. I will close #113 for now and mark #63 as PR needed, so we do it all in one go.

**Comment by chrisdotcode** [comment]
Hey guys, don't forget to tag issues like this with `v1.0.0`, and link them in the master `v1.0.0` issue.

**Comment by olivif** [comment]
@chrisdotcode will do :smile:

**Comment by chrisdotcode** [comment]
Closing, cf. https://github.com/jsonresume/resume-schema/pull/240#issuecomment-653958512.
