### ISSUE TITLE
Add a Contribution Guidelines file.

### ISSUE THREAD

**Issue by aloisdg** [jsonresume/resume-schema#211]
Hello,

JSONResume doesnt have a [Contributing.md](https://github.com/blog/1184-contributing-guidelines) file.

> It explains how a participant should do things like format code, test fixes, and submit patches.

Time to think about adding one!

The [original idea](https://github.com/jsonresume/resume-schema/issues/46#issuecomment-167148215) came from @olivif on this issue ( #46 )

**Comment by olivif** [comment]
@aloisdg great to see the ball rolling on this :smile:

**Comment by olivif** [comment]
should this also include details about the committee and past contributions? Like mentioned by @thomasdavis in #22

**Comment by aloisdg** [comment]
I don't think so. I don't recall seeing this in others CONTRIBUTING.md. Also, you can find [contributors](https://github.com/jsonresume/resume-schema/graphs/contributors) and [members](https://github.com/jsonresume/resume-schema/network/members).

**Comment by stp-ip** [comment]
Yeah I would leave CONTRIBUTING.md for one purpose and if need be a CONTRIBUTORS.md file.

**Comment by thomasdavis** [comment]
Definitely need a contributing.md file! We can use the website and Github activity pages to display contributors. There are a lot of new faces around here so I will update the homepage soon.

**Comment by phumke** [comment]
+1 on this!  I've been watching the progress, you guys have been doing great, and would love to know how to contribute some as well.

**Comment by aloisdg** [comment]
@phumke keep following and commenting the project. It is the first step to contribute!

**Comment by olivif** [comment]
good work @aloisdg :smile:

**Comment by aloisdg** [comment]
Thank you :smile:
