### ISSUE TITLE
Standards committee and contribution list

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#22]
Hey guys,

For those of you helping out with debating the specification we would like to start building an official standards committee and also make publicly known those who have contributed minor recommendations.

**Comment by stp-ip** [comment]
Currently we have 20 team members having some elevated rights. Would we see these as the standard committee?
Right now mostly @chrisdotcode @aloisdg @opensourcegrrrl @thomasdavis @olivif are "deciding" on issues.
The method right now is a consensus approach and if no consensus is reached we push back the issue to revisit later or provide examples/arguments to get to consensus.

Question is should we move to a more formal approach?

**Comment by olivif** [comment]
might be a good idea to have a sync meeting every now and then, to decide on the higher level things. we should also sync with other contributors on cli and website, to make sure we are aligned.

**Comment by thomasdavis** [comment]
Has anyone recently had a good experience with any distributed team meeting planners? I've been struggling to organize times. Will just setup a public google calendar if there are no better suggestions.

**Comment by aloisdg** [comment]
I think more input from template maker and non-dev user would be a great bonus.

**Comment by olivif** [comment]
@thomasdavis [doodle](http://doodle.com/) is quite good.

**Comment by aloisdg** [comment]
@olivif doodle is enough but very simple.

@thomasdavis If you want to arrange an oral meeting, I may not be here. My french accent is strong and I am living in India (different timezone). If I can I will come.

**Comment by opensourcegrrrl** [comment]
+1 for doodle

**Comment by thomasdavis** [comment]
In the interim, https://gitter.im/jsonresume/public should be a good place to start impromptu chats.

**Comment by chrisdotcode** [comment]
(Auto-manually closing just because this is so old. @thomasdavis (or anyone else) if it needs re-open, just let me know.)
