### ISSUE TITLE
Request: Basics additions

### ISSUE THREAD

**Issue by dionysius** [jsonresume/resume-schema#221]
In my use case it's mandatory to have fields like:

* date of birth (so they now how old you are)
* civil status (single, married, ...)
* nationality (care: multiple possible)
* mobility (driving licence [category xyz], train season ticket, ...)

and element "profiles" is a bit clunky at most... if you want to link a gitlab account, there's no gitlab icon. twitter, github... etc are well supported. maybe add an icon link element to that object for flexibility? or a font-awesome code, which should give enough flexibility.

for the generality make all this fields optional, not everyone can or want to fill out all these informations.

**Comment by aloisdg** [comment]
More personals fields are coming in v1! See #41 for more informations.

**Comment by stp-ip** [comment]
First icons are theme based and related to design not data. Therefore I would vote against having an icon link inside the resume schema. One could easily add that to the theme used.
And as @aloisdg just said, more fields are coming in v1 #41.
Will add your specifics about mobility there.

**Comment by aloisdg** [comment]
> First icons are theme based and related to design not data. Therefore I would vote against having an icon link inside the resume schema. One could easily add that to the theme used.

:+1:

**Comment by dionysius** [comment]
Wow, didn't saw #41 - my fault!

Yes, they are optional in the most designs - just wanted to mention it explictly

**Comment by aloisdg** [comment]
@dionysius No problem ! :)
