### ISSUE TITLE
Allowing multiple locations

### ISSUE THREAD

**Issue by aloisdg** [jsonresume/resume-schema#222]
Hello,

I was reading an indian resume when I saw two address : present and permanent,
I am living/traveling this year in India and I will come back to France in 5 month. I would love to use two address too. How resume-schema would support this? An array? A container object?

Cheers,

**Comment by olivif** [comment]
That's a good catch @aloisdg! This is also applicable to people studying abroad whose permanent address is in their home country. 

The options I see are 
1. having 2 separate location objects: current and permanent, one/both of which could be null
2. having a container object which has both locations 
3. having an array as you suggest

Thinking from the schema perspective, either work for me. Thinking from the theme creators / usability perspective, probably 1 or 2 because 3 is more error prone. 

Changing title slightly to focus more on intent as opposed to implementation.

**Comment by stp-ip** [comment]
I would vote for 1.

**Comment by aloisdg** [comment]
I think we could take 1 for v1 and let people add feedback for a v1.1.

**Comment by stp-ip** [comment]
So we would go with 2 objects referencing an address as in #113 called ```location``` and ```location.permanent```.

**Comment by thomasdavis** [comment]
+1 for 1)

It will be a very optional property and those who use will have to hassle theme developers to support it =D

Keeping in mind I would really love to build out theme utility libs this year such that it is not cumbersome for theme developers to support these edge cases.

**Comment by aloisdg** [comment]
We have a consensus on the first proposition. Let's go for this one.

```json
"basics": {
  ...
  "currentLocation": {
      "address": "2712 Broadway St",
      "postalCode": "CA 94115",
      "city": "San Francisco",
      "countryCode": "US",
      "region": "California"
    },
  "permanentLocation": {
      "address": "2712 Broadway St",
      "postalCode": "CA 94115",
      "city": "San Francisco",
      "countryCode": "US",
      "region": "California"
    },
  ...
}
```

**Comment by thomasdavis** [comment]
@aloisdg I think we should stick with `location` as the default property. Because it is backwards compatible and `permanentLocation` won't be used too often.

Such that it would be `location` and `permanentLocation`, where `permanentLocation` could also potentially be called `residence`

**Comment by aloisdg** [comment]
Agreed. We keep `location`. `residence` is better then `permanentLocation` but it can be confusing. It will have to be written in the scheme description of the field.

**Comment by thomasdavis** [comment]
Yeah `residence` was a pretty bad suggestion, would love one word if we could.

**Comment by stp-ip** [comment]
+1 for location and permanentLocation
-1 for residence as it's harder to grasp for non English speakers and the meaning is not as definite.

**Comment by aloisdg** [comment]
In another hand, I find `location` and `permanentLocation` is a bit confusing too.

A one-word solution would be the 2) proposition, but we loose the compatibility.

```json
"basics": {
  ...
  "location": {
      "current" : {
        "address": "2712 Broadway St",
        "postalCode": "CA 94115",
        "city": "San Francisco",
        "countryCode": "US",
        "region": "California"
    },
    "permanent": {
        "address": "2712 Broadway St",
        "postalCode": "CA 94115",
        "city": "San Francisco",
        "countryCode": "US",
        "region": "California"
    }
  },
  ...
}
```

**Comment by olivif** [comment]
from a semantics and consistency perspective, I like @aloisdg's last suggestion. given we are moving up to a major version and themes will most likely need a re-work anyway, seems reasonable to break backcompat for the sake of clarity and consistency :smile:

**Comment by stp-ip** [comment]
+1 for basics.location.current and basics.location.permanent

**Comment by aloisdg** [comment]
We are moving from v0.x.x to v1.x.x, by semver definition, we are breaking compatibility. 

![cu6-c8twiaanqqp_opt](https://cloud.githubusercontent.com/assets/3449303/13203646/94eedf22-d8e2-11e5-9d5d-68a03bb311b3.png)

Also, if we can avoid to break it, it is better.

**Comment by olivif** [comment]
agreed @aloisdg!

**Comment by phumke** [comment]
Another name for permanent could be domicile.

**Comment by aloisdg** [comment]
@phumke `domicile`... still confusing, isn't? It can be a current or permanent domicile.

**Comment by phumke** [comment]
I don't believe so, my understanding is that domicile is the legal term for the location where you stay indefinitely and plan to return to after temporary residence elsewhere.  I believe you can only have one at any given time.  My legal knowledge is weak, so it'd be worth getting verification on that before deciding.

**Comment by thomasdavis** [comment]
Anyway we can keep the properties at the top level of basics?

```js
basics: {
  location: {
    current: { // This nesting will rarely be used
    } 
  }
}
```

It does still seem like a small group of people who will need this. Even those who are in this situation, might not even care to include it on their resumes. 

And at this point I would almost suggest adding it to a free-for-all bucket which has been discussed in other issues.

**Comment by stp-ip** [comment]
If we include the nesting in the standard than it will be used. I think the nesting provides the cleanest solution.
I dislike moving permanent into a free-for-all bucket. That being said, I think a free-for-all bucket is bad to implement in the standard anyway. (besides non data related stuff such as metadata).

**Comment by thomasdavis** [comment]
But 99.99% of people won't need the property thus they will just have this unnecessary indentation.

**Comment by phumke** [comment]
Most of the time this complexity will be hidden behind the theme anyway, so I don't think it'd hurt to include it for the cases where people might use it.

**Comment by thomasdavis** [comment]
This is true, but a lot of other resume standards have little to no developer traction because the specification is way to cumbersome.

Another alternative is to make location an optional `object` or `array of objects`

```
  "location": [{
    "address": "2712 Broadway St",
    "postalCode": "CA 94115",
    "city": "San Francisco",
    "countryCode": "US",
    "region": "California",
    "type": 'current'
  },
 {
    "address": "2712 Broadway St",
    "postalCode": "CA 94115",
    "city": "San Francisco",
    "countryCode": "US",
    "region": "California",
    "type": 'current'
  }
],
```

**Comment by phumke** [comment]
Good point, I don't want the standard to be too burdensome on people.  I like the optional array of objects.  Using type/category makes these objects feel consistent with the project object too.

**Comment by aloisdg** [comment]
> The options I see are
> 1. having 2 separate location objects: current and permanent, one/both of which could be null
> 2. having a container object which has both locations
> 3. having an array as you suggest

 We start with 3), then move to 1), then go for 2) and here we achieve to come back to 3). Achievement unlocked :wink: 

Why an array? Is it possible to have more than two locations?

> But 99.99% of people won't need the property thus they will just have this unnecessary indentation.

Why is it a problem? We are not talking about a huge depth here. Also I think remote work and [digital nomads](https://www.reddit.com/r/digitalnomad) are the future. We are going to see a lot more of them.

**Comment by thomasdavis** [comment]
> Why is it a problem? We are not talking about a huge depth here. Also I think remote work and digital nomads are going to increase. We are going to see a lot more of them.

We will always be making compromises at every step of the way and increased complexity has exponential effects on the technical debt of the ecosystem.

Every part of the ecosystem now might check to see if location exists, so they might write something like;

```
if (typeof basics.location.current === 'undefined'
```
Ops the user forgot to include the location property entirely so the above code will throw a `can't get current of undefined`

So now everyone has to go and make

```
if(basics.location && typeof basics.location.current ==='undefined') {
```

Now what if all they had was a permanentLocation but not a current location, the template logic gets even trickier. Developers have to be put far ahead of anyone else at this point.

**Comment by thomasdavis** [comment]
It is mostly a debate about granularity, `name` for example could have been `firstName`, `lastName`, `preferredName`, `traditionalName` but we went with `name` because of ease of implementation.

You could make the same argument that the developer could have took care of all the edge cases of a persons name as long as the standard covered it. But then I fear there would be no developers =D

**Comment by thomasdavis** [comment]
Innovation through constraints happens a lot too.

Let's say we don't have a `permenantLocation` at all. People can get pretty creative, they might include it in their `summary`. Or we might figure out a `notes` attribute is what we were looking for. Maybe they just include it in the email when they upload their resume.

**Comment by aloisdg** [comment]
@thomasdavis I don't know for JS, but in C# you can use [null-conditional operator](https://msdn.microsoft.com/en-us/library/dn986595.aspx) (exist in Swift too) or even LINQ. In functional languages, you can use an Option monad.

**Comment by thomasdavis** [comment]
Yeah sweet. More just commenting on the fact that there is extra code to support a very small edge case which can be solved in other ways.

**Comment by sixside** [comment]
chiming in via /r/digitalnomad/

Most digital nomads that I know have two addresses

1. a mailingAddress where they will receive all of the typical snail mail. This address is fairly permanent and doesn't change that often.
2. a currentAddress wherever they are in the world at that moment. IMHO, this probably changes too frequently to constantly be updating the JSON every 1-3 months (the usual length of any given countries visa allowance).

Given the fact that best practices regarding resumes suggest you tweak your resume for each job you're applying for you could probably get by with 2 addresses in the spec:

1. mailingAddress (see above)
2. displayAddress - this is what displays in a given resume output. If I'm applying for a job in Budapest, I'll edit my JSON file to include a Budapest address to make the employer feel warm and fuzzy about me as a candidate and not pass me over just because I'm currently in Tasmania.

**Comment by phumke** [comment]
I think if we use an array we shouldn't define a precedence of location types.  This keeps the logic simpler: Just check that the location is not undefined and iterate through the list.  It the user wants certain locations displayed or hidden then they can use the metafiltering to include/exclude different mailing types when generating the resume.

**Comment by olivif** [comment]
I am still against the array and pro `location.current` and `location.permanent`. 

I think from a semantics perspective this expresses the intention most clearly. As long as the objects are named correctly, the field cannot be misused. Both by users and theme writers. I can see the array going wrong in so many ways. You fill in the fields in the wrong order. There's no (implicit) documentation to tell you which one is which. Let's say you're in between jobs (and countries) so you don't have a current address, but you have a permanent one - empty/null object for the first item in the array? Similarly on the theme side.

**Comment by aloisdg** [comment]
> You fill in the fields in the wrong order.

No ordered set in basic, plain json I guess.

> pro location.current and location.permanent

So you are for 2) too.

**Comment by aloisdg** [comment]
@sixside So you are supporting a binome of adresses. If this proposition is kept, we will add your consideration about mailing in the documentation.

**Comment by stp-ip** [comment]
My vote is still on for having 2 definite address sections. One permanent and one current. Way easier and cleaner in my opinion. And should cover almost all cases.

Not decided on having a sub hierarchie and on naming the sections.

**Comment by wayneamurphy** [comment]
I can see a desire for this, but I'd agree there needs to be clarification.
How does the person know when the "Present" address stops?
Even if you added a "Present-Until" end date, it doesn't guarantee that after the date is now back at their permanent location.
Resumes are often snapshot documents, your phone and email address are what you are using right now. The skills are current (you might have learned something 10 years ago, but that is not what you are promoting right now).

I can see for a student or other working might be at a temporary residence, but paper resumes don't really have multiple addresses.
If anything I would suggest an address_note field, which would say in text you are here for the summer then back in CityB after a given month.

**Comment by thomasdavis** [comment]
Unfortunately, I think this suggestion makes a lot of implementation too difficult. 

The externalities of your situation can be explained by email or cover letter.
