### ISSUE TITLE
Consistent base fields for core sections

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#223]
- `name` (instead of  `company` etc.)
- `description` (instead of `summary` etc.)
- `website` (instead of `url` etc.)
- `$dates`
- `highlights` <-- needs decision
- `keywords` <-- needs decision
- `location`

**Comment by phumke** [comment]
+1

**Comment by oupala** [comment]
+1 for adding location to work experiences, education and volunteer, at least.

**Comment by stp-ip** [comment]
Closing in favor of #256

Trying to finally get some headway.
