### ISSUE TITLE
Consistent naming of url types

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#224]
For the main sections the field should be named `website` including personal website, company website, project website etc.

For links to more resource like things such as slides, videos, identifiers, downloadables, I would suggest `source`.

Update: Moving to the suggestion from @aloisdg

**Comment by aloisdg** [comment]
I would prefer a simple `source`.

**Comment by aloisdg** [comment]
related to #144

**Comment by olivif** [comment]
Renamed title slightly. `website` and `source` sound good to me!

**Comment by phumke** [comment]
+1 to @aloisdg - just source sounds good

**Comment by thomasdavis** [comment]
Could someone paste a larger example with `source` being used, a tiny bit confused.

**Comment by stp-ip** [comment]
@thomasdavis 
On the go so a larger example has to wait, but the reasoning is that website is great for showcasing a website, but it might be the wrong word for a link to downloading a publication, or a link to the slides of a presentation etc.

```Source``` therefore could be used for these additional resources provided via a url, which are not a ```website```.
As we move into more generic territory with for example publication probably also applying to talks given, having a ```slides``` or ```video``` field for urls, is not the best idea, therefore we could add either one ```source``` field, or perhaps a ```sources``` array with ```url``` and ```label```.

Hope that makes the reasoning behind this issue more apparent.

**Comment by stp-ip** [comment]
So the proposition:
* ```website``` for the actual websites.
* ```source``` with a ```URL``` and a ```label``` field for things such as videos, slides etc. (one source for now - maybe array later?)
* ```image``` either URL or base64 encoded for logo, image or ?showcasing?. See #233

**Comment by olivif** [comment]
+1 for `website` and `source`

for `image`, I would stick with URL for now.

**Comment by aloisdg** [comment]
I find it a bit cluttering to get source and website but I can understand the use. I am not against.

**Comment by stp-ip** [comment]
New proposal:
* ```website``` for actual websites [using URL as type]
* ```source``` with a ```URL``` and a ```label``` field for things such as videos, slides, images for showcasing etc.
* ```image/logo``` for company logos or project logos [using URL as type]

**Comment by aloisdg** [comment]
@stp-ip I still find this to heavy

**Comment by stp-ip** [comment]
Ok simplifying and trying to work with this:

* ```website``` for actual websites
* ```source``` with a ```URL``` and a ```label``` field
* ```image``` for all images (company and profile)

**Comment by stp-ip** [comment]
Closing in favor of #256

Trying to finally get some headway.

**Comment by stp-ip** [comment]
During the PR to make the current schema conform to the specific url types it seems to make more sense to just use ```url``` for slides, videos and websites.

We might leave it at url for websites and profiles for now and revisit an array of urls called ```resources``` for publications, references or projects (slides, videos, mockups etc.)

**Comment by aloisdg** [comment]
Agreed
