### ISSUE TITLE
Proposed metadata section usage (meta issue)

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#225]
Overview of possible uses of the `metadata` section.
- #28
- #49 
- #203 
- #47

**Comment by evanplaice** [comment]
- #28 URLs are already integrated as `meta.canonical`
- #49 revision history is what source control is good for, why re-invent the wheel
- #203 same goes for tagging
- #47 formatting/parsing is a template-specific concern

**Comment by thomasdavis** [comment]
`meta` enabled
