### ISSUE TITLE
Overview of currently suggested core sections and their subsections

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#227]
`basics` (personal data)
`basics.details` (more detailed personal data, suggested as additionalInfo)
`work` -
`work.project` -
`education` -
`education.courses` -
`education.exams` -
`projects` -
`projects.project` - hobby projects, volunteering, school projects, talks given/attended etc. (needs flag for non-profit/volunteering)
~~`events/talks`~~
`achievements` (nobelprize, other awards)
`certification` (certified brewer)
`publications` -
`legal` (for patents, copyright, branding rights)
`skills` -
`languages` -
`interests` (interests and hobbies)
`references` -
`meta` -
`meta.version` - current version of resume data
`meta.canonical` - canonical url referencing the location of the most recent resume data
`meta.lastModified` - last modified Date in the format **YYYY-MM-DDThh:mm:ss**
`meta.schema` - standardized meta data
`meta.schema.references` - contact information for references **should not be published**
`meta.schema.filters` - filters for exporting etc.
`meta.schema.localization` - strings overwriting basic fields using name as identifier
`meta.enhancedText` - (post-v1 only)
`meta.tooling.$tool` - not standardized section for automated tooling data

**Comment by olivif** [comment]
> education.project  <-- Why did we wanna have a project subsection here again?

For things like thesis or larger school work projects. 

>
> events  <-- stand alone needed?

Probably not if you ask me. Events you organized should be covered by projects. Events you went to are, well, perhaps a bit too much detail if you ask me. 

>
> protection  (for patents, copyright, branding rights) <-- needs a name change

intellectual property? ownership?

**Comment by aloisdg** [comment]
+1 for removing volunteering work. It should go in the project section. Organization? "aloisdg". It fits with GitHub way to do it.

> education.project <-- Why did we wanna have a project subsection here again?

Remove this. Example: I made an awesome IsATriangle program as a school project. I should added in the project section with organization set as "Berkley".

> achievements (nobelprize, other awards) + certification (certified brewer)

Can we merge this?

> events

It could go to project too...

**Comment by stp-ip** [comment]
> > education.project  <-- Why did we wanna have a project subsection here again?

> For things like thesis or larger school work projects. 

I think larger school work projects should either be work (if it's payed) or done in projects.
mixing education and projects seems unclean and makes the schema more complex.

>> events  <-- stand alone needed?

> Probably not if you ask me. Events you organized should be covered by projects. Events you went to are, well, perhaps a bit too much detail if you ask me. 

I mostly agree. Talks one gave could go into publications with type talk/presentation. We could add slide, video url fields to publication to make it easier.

>> protection  (for patents, copyright, branding rights) <-- needs a name change

> intellectual property? ownership?

undecided, would ownership describe all possible legal protection mechanisms?

**Comment by stp-ip** [comment]
+1 for removing volunteering work. It should go in the project section. Organization? "aloisdg". It fits with GitHub way to do it.

>> education.project <-- Why did we wanna have a project subsection here again?

> Remove this. Example: I made an awesome IsATriangle program as a school project. I should added in the project section with organization set as "Berkley".

I agree.

>> achievements (nobelprize, other awards) + certification (certified brewer)

> Can we merge this?

We discussed that and couldn't really agree on merging this. Achievements are not so similar to certification. For now I think the separation is needed. At least until one comes up with a good merge strategy.

>> events

> It could go to project too...

I agree as written in my last comment.

>> work + work.project -

> Should move to project too.

I have to disagree. A project within work can be a specific website for designers, a client for consultants or other projects within one work item to be showcased. It's nice to show the length and details of these projects and be able to showcase via urls etc.

**Comment by stp-ip** [comment]
Just as an additional note:

Publications need to be extended to be able to merge events into it.
- > slide, video urls as an example.

Projects need to be extended with a field for type of project to be able to merge volunteering into it. Either an enum or just a true/false flag for non-profit. Question is how would we do contributions to jsonresume as an example. It's basically non-profit, but I would probably set non-profit to false.

**Comment by thomasdavis** [comment]
Great work and logical conclusions, closing because of large scope.
