### ISSUE TITLE
Write examples and documentation about the usage of various sections

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#228]
During the discussion we had a lot of reasoning, such as where to merge things and how to make things generic. As an end user these decision might not seem as straight forward and therefore we should document examples and where they end up in the resume.
- events organized non-profit -> projects.project
- school attended -> education
- school project -> projects.project
- work project -> work.project
- talk done -> publication
- abroad experience -> achievements

etc.

**Comment by aloisdg** [comment]
@stp-ip I think it should be done for v1, not after.

**Comment by stp-ip** [comment]
;)

**Comment by aloisdg** [comment]
@stp-ip Can we open the wiki and let collaborator write in it directly and freely?

**Comment by stp-ip** [comment]
Can you write here: https://github.com/jsonresume/resume-schema/wiki/Section-Documentation

**Comment by aloisdg** [comment]
@stp-ip Yes I can

**Comment by thomasdavis** [comment]
Yep, this will be great.

**Comment by aloisdg** [comment]
Honestly I don't remember most of the discussion. We will have to digg.

**Comment by stp-ip** [comment]
For now wiki seems fine and I appreciate everyone helping in getting more docs in.
I'll think about how to structure docs within the repo so we can have each PR also add documentation.
