### ISSUE TITLE
Copyright field in the schema

### ISSUE THREAD

**Issue by drkarl** [jsonresume/resume-schema#229]
Hi, Every time I want to update my CV I get blocked by the appeareance, since adding content always messes the formatting up in Word and when I want to renew the look I always spend a lot of time trying to find a Word template that I like and then the slow process to copy and rearrange all the information to the new template. So I had been thinking for a while that it would be great to decouple the data and the look and feel of the CV / résumé, then I saw HackMyResume in Hacker News, and I love it!! So congrats on the great job.

Now the actual issue. It is actually a feature request. It would be great to have an optional field for a copyright license (where you specify one of the many open source licenses or have a link to your own custom license).

The reason for this is that there are many unscrupulous recruiters that do a lot of bad practices on candidates' CVs. Some interesting articles on the subject:

http://www.stdlib.net/~colmmacc/2005/05/17/copyright-your-cv/

http://www.corcodilos.com/blog/317/let-the-resume-wars-begin

http://freelancing.stackexchange.com/questions/287/what-steps-can-i-take-to-protect-my-reputation-if-my-cv-is-plagiarised

Also: http://www.brandonsavage.net/why-recruiters-are-bad-for-your-career/

**Comment by chrisdotcode** [comment]
Interesting. I'm interested in this, but I think we should save it for post-v1.

**Comment by aloisdg** [comment]
I agree to use it for v1 or post-v1.

I think we should use the [license field](https://docs.npmjs.com/files/package.json#license) from npm.

**Comment by drkarl** [comment]
The npm license field should probably work well for this, although I think it would be quite useful to allow a url to point to the license (both a remote, `https://mydomain.com/LICENSE` url and a local `./LICENSE`

**Comment by stp-ip** [comment]
I think this could be easily done in the meta section as an object such as meta.basics.licensing.

We should have a license object containing the source of the LICENSE, a LICENSE "title" (perhaps even enums?) and a short LICENSE description. 

So I would vote v1.

**Comment by drkarl** [comment]
@stp-ip enums would allow to specify known license types, like APACHE, MIT, GPL, LGPL, BSD... but there should also be a CUSTOM to allow specifying a custom license.

**Comment by aloisdg** [comment]
@stp-ip I dont think an enum is a good choice here. There are too many values.

**Comment by stp-ip** [comment]
@aloisdg what about having the main licenses as enum and in addition use a custom one? Probably more complexity than worth it.

**Comment by aloisdg** [comment]
@stp-ip IMHO, an enum is great if you can enumerate all choices. I dont see the benefit of a custom field in an enum. Btw, the npm license allows custom entry.

**Comment by thomasdavis** [comment]
A copyright field would most likely not be used often, JSON Resume errs on the side of minimal properties. `copyright` would have to be supported in the custom fields section.

**Comment by thomasdavis** [comment]
Might start closing Revist tags, just to clear issues up. But `Revisit` will mean that closed issues will be revisited and tagged appropriately.

**Comment by stp-ip** [comment]
Copyright might be huge for people in creative industries. Definitely has to be revisited. I agree that we should clean up the issues for v1. Get to a MVP for v1 and then publish an alpha version before we revisit the remaining revisit-issues.
