### ISSUE TITLE
Certifications array field

### ISSUE THREAD

**Issue by drkarl** [jsonresume/resume-schema#230]
I was thinking that maybe it would be worth to have a separate Certifications array field instead of including the certifications along with college degrees.

**Comment by stp-ip** [comment]
We discussed the addition in #177 and it was added to the overview of v1 in #227.

Therefore I'm going to close this with the hint: "please search for your ideas first and then add your ideas, suggestion, if an issue already exists"

**Comment by drkarl** [comment]
Fair enough

**Comment by aloisdg** [comment]
@stp-ip as written in the contributing file ;)
