### ISSUE TITLE
[Education] Should have optional Month

### ISSUE THREAD

**Issue by triplekdev** [jsonresume/resume-schema#232]
Hi, I would like to add if possible to make the Month as a optional for this section. Not in general schema if allowed, but for maybe in resume-cli validations?

**Comment by stp-ip** [comment]
Not sure what you want to suggest here. There already is a start and end date field, which can be exact to the day. This will be available in v1 too.

**Comment by triplekdev** [comment]
I mean, allow to display only YYYY format. say 2001-2004

**Comment by stp-ip** [comment]
The theme can show only the year. The data itself is more specific, but might be handled via a date library to ease theme developers and other tooling providers.
If you want to specify 2001 just use 2001-01-01, which is the process the helper utility would use.
I'm going to close this as I think it might be solved.
