### ISSUE TITLE
Logo for companies

### ISSUE THREAD

**Issue by drkarl** [jsonresume/resume-schema#233]
It would also be good to have an optional field for an image with the logo of the company in the work experience section, also maybe in volunteership and the institution in the education section.

**Comment by aloisdg** [comment]
Good idea. Could be included in v1 easily.

Naive implementation:

    {
        "imageSource": "http://toto.com/logo.png"
    }

Higher implementation:


    {
        "image": {
        "source": "http://toto.com/logo.png", 
        "stretch": "fill"
        }
    }

Where stretch is an enum: "Uniform", "Uniform-to-fill", "Fill", "None". It can be useful for themes maker.

**Comment by stp-ip** [comment]
I would go with "image": "http://example.com/logo.png" and "image": "$base64_encoded_image_data"for v1 and more advanced stuff could be discussed in detail post-v1.

**Comment by JD-Robbs** [comment]
The same could be useful in other areas as well - `certification`, `education` and `award` come to mind (but could also be achieved via an `additionalProperties` workaround, where available).

**Comment by olivif** [comment]
+1 on having a source/url for v1. 

@aloisdg I disagree with the stretch enum, isn't that a visualization detail? :smile: 

@JD-Robbs true, you can use additionalProperties for the time being, but if we want to support it for v1 I propose we do it right and include it in all the sections where we think it's needed.

**Comment by aloisdg** [comment]
@olivif yes but some companies are going to cringe if we touch there logo. The default is going to be uniform of course and I am find to keep only this. We would see if there is a demand from theme maker. For now, I think it will just add more noises. Keep it simple, stupid.  :)

**Comment by stp-ip** [comment]
Decision:
Add a new field to most of the main sections called ```image```.
It can hold a url to an image or provide one via base64 encoding.
Will add this to the #224 to get all URL related things tracked in the same issue.

**Comment by olivif** [comment]
+1 @stp-ip 

Have we decided which sections we will add this on?

**Comment by stp-ip** [comment]
I would say it makes sense for every section there could be a website for.

**Comment by chrisdotcode** [comment]
-1 from me. Images aren't inherently important to a resume. It's metadata about a company I worked for - not information about me when I was working at that company.

**Comment by stp-ip** [comment]
What about a distinction of resume specific data and data essential or optional for a better presentation. The specific data should live in the general schema and the presentation data could be done inside a meta section. Something like: meta.presentation etc. Similar to filters and so on.
That way tools have a standard way to save presentation data into the resume for faster/better presentation, without cluttering up the main schema. We could keep a strict "SLA" on the general schema and let the meta section be changeable for the beginning. If a tool wants to rely on some data, it can namespace their own inside the meta section.

That's just a few thoughts written down. Hope they make sense.

**Comment by chrisdotcode** [comment]
I'm in favor of a method like that, @stp-ip. I'm really a fan of dumping a lot of "by convention" stuff in `meta`, but leaving the essentials (that can be used by non-devs, too, ultimately) in the actual schema. Separation of concerns and all that.

**Comment by thomasdavis** [comment]
-1 For the same reasons as @chrisdotcode, the schemas goal is always to be the least confusing resume spec for developers to get their hands on.

That being said if a lot of JSON resume developers request that they think it is of the utmost importance to have logo data then we can progress.

<tangent>
A lot of people visiting this repo will be doing so when job searching, they will be missing something they wanted and request it. After getting a job they will move on and forget about it while the schema becomes bloated.

I think we should base demand off technology also, it is all well and good for 40 people to say that it is a good idea, but if no one implements anything what so ever to do with the property, it is mostly useless.

</tangent>

@stp-ip I like those ideas, I will tag some theme developers to come comment

**Comment by mudassir0909** [comment]
I think this should be theme developer's responsibility. We can use this amazing free api by clearbit to fetch a logo of an organization based on the url, plus it is always updated no need to maintain when a company changes it's logo

Open the following links & see for yourself

https://logo.clearbit.com/uber.com
https://logo.clearbit.com/google.com
https://logo.clearbit.com/diligencevault.com

**Comment by chrisdotcode** [comment]
@olivif and @aloisdg, feedback?

**Comment by olivif** [comment]
I have very strong feelings about not introducing actual image data into the schema. So -1 on base64 encoded data.

I would prefer keeping this presentation data out of the schema completely, I like the idea of meta.presentation but only as a "post-processing" step done in some other layer other than the base schema.

**Comment by chrisdotcode** [comment]
Okay, so it seems the majority agree with the field going in `meta`, in which case, the community can/will decide on the best convention (e.g. `meta.image`). But if it's not going to be added as a main schema field, I think that that resolves the issue in this case, so I'm going to close this to reduce issue clutter. If there's any additional commentary/ideas, just comment, and we'll reopen :)

**Comment by stp-ip** [comment]
No need to reopen yet, but just wanted to add:

I still feel that even so we try to make meta not as strict, we should try to add a bit of structure to it. If we can introduce meta.presentation or something that makes sense, we would reduce clutter from the beginning. Or as I said in another issue, maybe we should keep meta.X for metadata from the schema itself and use meta.tools.X for actual namespaces and community/tool provided data. If it makes sense, we could push this or the specific namespace into the meta.X section and have it inside the schema (or at least defined).

**Comment by thomasdavis** [comment]
@stp-ip Understandable. Will write more later but it sounds like we need something like `modules`

**Comment by chrisdotcode** [comment]
> I still feel that even so we try to make meta not as strict, we should try to add a bit of structure to it.

`meta` is all about conventions: that is, anything *can* be in meta, but I surmise that, over time, theme authors and the community will come up with de facto places to put things. So conventionally speaking, I predict that meta will have some fairly standard locations to put certain things, but as a matter of the specification, we're better off specifying `meta` as "do anything you want", otherwise we'd have to regulate `meta` as well (and unregulated fields was the whole point of `meta` in the first place).
