### ISSUE TITLE
Certifications section

### ISSUE THREAD

**Issue by kneeki** [jsonresume/resume-schema#235]
I'm looking to add a list of certifications to my resume, but getting lost in the process. Searching here returns many people wanting to add `certifications` to the schema as far back as 2014 or so. As far as I can tell this hasn't been done? Anyone who knows better, mind pointing me to the right direction?

edit:
Here's a list of those issues opened regarding certifications: #32, #103, #167, #177, and #230. Within those issues, some people are suggesting adding another entry into education and listing each cert as a course. Is that the standard workaround?

**Comment by chrisdotcode** [comment]
We're gonna tackle this post-v1.

**Comment by rpsadarangani** [comment]
Is there any update on this feature

**Comment by stp-ip** [comment]
@rpsadarangani not yet. We are working on a few things coming up.

**Comment by stp-ip** [comment]
If you have any specific schema suggestions on how you would like the certifications sections to look, feel free to write something up here.

**Comment by rpsadarangani** [comment]
Will it be fine if I send a Pull Request with the needed Schema.

**Comment by stp-ip** [comment]
We are always greatful for any Pull Request submitted, but it might not make it into the schema. We try to have it generic and usable for a lot of various resumes and therefore it might not match our requirements/vision. Just wanted to make sure you know that.

**Comment by thomasdavis** [comment]
Merged certs in https://github.com/jsonresume/resume-schema/pull/340
