### ISSUE TITLE
How to move the standard to v1 faster, make more progress etc.

### ISSUE THREAD

**Issue by mboudreau** [jsonresume/resume-schema#236]
I'm concerned.

We've started this new project at work and I wanted to use a standard already in place that would make things easier to share within and outside of our company, but the more I'm using the standard, the more I'm finding that it's incomplete and lacking for some basic outcomes.  I've created a few tickets around some of them, even created a PR for the validator, but nobody seems to be very active in doing anything or making decisions.  There's a lot of talk around these subjects, sure, but progress is slow.

Then there's some lacking features that would make this standard better, simple things like a better name property convention, because not all people have a singular name, or they might go by a preferred one, or they have might a title, like Dr, PhD or P.Eng.  

There's a lack of gender which I know someone would say that it's to remove the possibility of discrimination, but that lack of information is a problem when trying to hire someone where their gender is an important part of the equation, like for instance, a TSA agent that's female to perform strip searches to other females or someone to conduct testicular cancer screenings or to see if a company is gender equal by comparing numbers.  I'm okay with making the property optional when it's not needed, but you'd be surprised how often is it.

In this day and age, there's a lot of people that only have their mobile as a phone number, but that doesn't mean that there can't be several different phone number with the ability to order them by call importance or the ability to label them.

There's also no way to know the availability of the candidate if they're available immediately or 3 months from now (contract), which can be important for people searching for a date range of availability or urgency.

Location is another issue that doesn't currently have lat/lon coordinates in places and that each work or education history doesn't have that very same location object needed to filter by them, which is important for international roles which need certain certification/schooling in a particular region or the ability to work in a particular country.

Lastly, the ability to add extra metadata related to the person in a way that makes sense, but isn't part of the 'resume' per say, things like a custom ID or last updated timestamp (which could be part of the schema).  There's a current issue around this which said to add a new section called 'meta' where all the metadata can be placed, but this doesn't work well when you want to add metadata to the first work history item that's in an array from a front-end perspective since I would be iterating over 2 arrays to get all of the information.  I'd rather had 'meta' be used as a reserved property which can be added to any other objects to add additional information on that object.

Okay, that's enough of my rant.  Moving forward from here, I'm going to create a fork of the schema and use it as our standard within our company while keeping company specific data in meta properties.  I'd be more than willing to do a PR when we're at a point that we're happy with it, but I have my doubts that it will be considering that nobody seems to be maintaining the PRs, including one that I created a month ago to change the validator to use a promise instead of a callback.

**Comment by aloisdg** [comment]
Lots of good point here.

> I'm going to create a fork of the schema and use it as our standard within our company while keeping company specific data in meta properties. 

I think it is the best solution. There is no direction, no clear goal. The result is chaotic. They are great team behind the project, but we are sparse and busy. Nobody works full time here.

>  I'd be more than willing to do a PR when we're at a point that we're happy with it

And I would love to see it too. Please add a link to your fork at the end of the message when you fork will start.

JSONResume solve an important and great problem. We want it. We need it.

**Comment by stp-ip** [comment]
Hey just a quick response, before I can dive into the specific issues.

There are new contributors around and we are doing our best to get the progress picking up. As we are moving towards v1 the discussions definitely took priority and we should be able to create PRs from this base in the coming weeks/months and finally push out an alpha v1.
That being said we value incoming PRs especially based on the various issue discussions we had.
The current count of PRs are mainly their for reference and will be closed, when they are superseded with PRs based on the mentioned discussions.

Your PR was recognized on my end, but it's not my area of expertise. I should have acknowledged that I think it should go in. Sorry for that. If noone of the other contributors steps in, I'll dive further into the validation stuff and review it accordingly.

As I said a more detailed response will be done next week, when I am back in my office.

One last thing: Thanks to all contributors and people helping in discussions and submitting PRs. Let's push for alpha v1 and get the standard out into the world ;)

**Comment by mboudreau** [comment]
@stp-ip Awesome, that's great to hear and I hope that I can actively contribute to make this a reality.

@aloisdg fork can be found [here](https://github.com/PageUpPeopleOrg/resume-schema).  I haven't started work on it just yet as I have a deadline to meet first, but I will soon to try to include as much of the capabilities that we need from it and see what people think.

Cheers.

**Comment by MarkBiesheuvel** [comment]
I would like to contributing as well.

I believe this is a great project and I've followed it a bit on GitHub to see if it progresses any further. There is some discussion going on, but I am not sure what is need right now. What are some things I could do to help this project get to version 1?

**Comment by stp-ip** [comment]
@mboudreau we'll definitely watch proposed solutions in your fork.

@MarkBiesheuvel Thanks for jumping in. Contributions are always welcome. The onboarding is not perfect yet as some discussions are rather lengthy. Will try to clean that up.

As a starting point:
First read the [contributing docs](https://github.com/jsonresume/resume-schema/blob/v1.0.0/CONTRIBUTING.md) and then look at open issues, which can be made into a PR for example: A minimal starting point for #204 could be doable. This change could be used for #28 as a first usage PR for the meta section.

I will try to get the labels cleaned on the issues so PRs and contributions are easier (ETA: starting next week). Aka having "easy" "PR needed" "decission needed" "postponed" etc. on the various issues so we can move into actualizing the discussions.

**Comment by olivif** [comment]
thanks everyone for your interest and for bearing with us here. we're inherited a lot of on-going issues and PRs which we have been trying to clean up for a while now. I've just gone through the PRs and cleaned everything up, we only have 4 on-going now which are all fresh and I believe should be merged in. 

I'll help out @stp-ip on the issues next.

**Comment by chrisdotcode** [comment]
I'll have a *lot* more time in the coming days/weeks/months to help out again, and so my manpower will also be added to triaging bugs, feature brainstorming, and hacking. (Hi everyone :))

**Comment by chrisdotcode** [comment]
I'm going to close this issue for the moment; if there is any disagreement, just comment and I'll re-open.
