### ISSUE TITLE
For work history separate employer and workedFor

### ISSUE THREAD

**Issue by rolandnsharp** [jsonresume/resume-schema#24]
@tracker1 
Given that many have worked in contractor roles, where you are working at/for one company (Microsoft), but employed by another (Volt), it would be nice to see this as part of the specification... I think it's a big oversight in most resume systems.

**Comment by stp-ip** [comment]
-> #11

**Comment by stp-ip** [comment]
I think we can close this as we are most likely moving to have ```projects``` as subsection of ```work```, which makes consulting work easy to showcase and reflect.

**Comment by aloisdg** [comment]
Agree.
