### ISSUE TITLE
Ability to tag skills for each job, might also consider to add cardinal score 1-5

### ISSUE THREAD

**Issue by eleijonmarck** [jsonresume/resume-schema#245]
I would love to be able to add tags to each job I have had.

For each tag I have in my resume I would like to say if I am a 1 - 5 in that skill.

Software Developer @ Something
* ***Java***

FrontEnd @ Frontthing
* ***JavaScript***

---
Skills
* ***Java*** 4
* ***JavaScript*** 3

**Comment by aloisdg** [comment]
Hello @eleijonmarck, glad you are looking for a way to do this! We would love too. We plan to add it in the next release of resume-schema. You can see the [current proposal](https://github.com/jsonresume/resume-schema/issues/16#issuecomment-219698224). Feel free to read the whole discussion before commenting ;)

**Comment by eleijonmarck** [comment]
Ahh wow! Sorry for that. Just looked through the issues. I apologize @aloisdg

**Comment by aloisdg** [comment]
@eleijonmarck No need for an apology. It is great to see different people think about the same idea. It shows that the idea is useful. :smile:
