### ISSUE TITLE
Extracurriculars/Activities for education

### ISSUE THREAD

**Issue by tylergets** [jsonresume/resume-schema#246]
If you're involved with clubs/extracurriculars at school, its very common to include these on your resume. Thoughts?

**Comment by stp-ip** [comment]
The proposed idea for the next version is to have a general projects section, with subprojects. Each project can be associated with an organisation/area (here school) and the subprojects could be the different extracurriculars/clubs. Does that make sense?

More infos are available in this issue: https://github.com/jsonresume/resume-schema/issues/226

**Comment by stp-ip** [comment]
Should be able with the proposed ```projects``` section. Closing as no relevant additional suggestions or requests are available.
