### ISSUE TITLE
Add certification section

### ISSUE THREAD

**Issue by vdavi** [jsonresume/resume-schema#248]
I'm working with a major freelancer / contractor organization and have presented this standard. It's not holding up well without a certification section.

Strongly recommending the addition of a certification section.

**Comment by stp-ip** [comment]
We are doing our best to include something for certificates in the upcoming verion. Unfortunately the top contributors are currently a bit time constrained, but that will change during the summer.

**Comment by nelg** [comment]
+1

**Comment by thomasdavis** [comment]
We could probably lock in a schema change without a full blown version release. Will look into this and get back to you.

**Comment by therin** [comment]
would be awesome to have this added to schema...

**Comment by aloisdg** [comment]
Related to #177

**Comment by dmkuznetsov** [comment]
any updates?

**Comment by aloisdg** [comment]
@dmkuznetsov No as far as I know. Feel free to contribute :)

**Comment by thomasdavis** [comment]
Commented in #177, we are bringing in certifications for V1
