### ISSUE TITLE
publications should have identifiers

### ISSUE THREAD

**Issue by rolandnsharp** [jsonresume/resume-schema#25]
@tmaier

like DOI, ISBN or another number.

name: string
publisher: string
releaseDate: string
website: string
identifiers:
- type: doi
  identifier: string // e.g.10.1000/182
- type: isbn
  identifier: string // e.g. 978-3-16-148410-0

**Comment by stp-ip** [comment]
+1

**Comment by thomasdavis** [comment]
Until there is a universal identifier in the publishing world, a resume is better off in general displaying just sufficient information.
