### ISSUE TITLE
add link to fields

### ISSUE THREAD

**Issue by oupala** [jsonresume/resume-schema#250]
It would be great to be able to link some fields.

For example, nowadays, skills are set by the following

``` json
  "skills": [
    {
      "name": "tools",
      "level": "Master",
      "keywords": [
        "git",
        "wiki"
      ]
    }
  ]
```

I'd like to be able to set them as links:

``` json
  "skills": [
    {
      "name": "tools",
      "level": "Master",
      "keywords": [
        "[git](http://fr.wikipedia.org/wiki/Git)",
        "[wiki](http://fr.wikipedia.org/wiki/Wiki)"
      ]
    }
  ]
```

or in a separate field:

``` json
  "skills": [
    {
      "name": "tools",
      "level": "Master",
      "keywords": [
        {
           "name": "git",
           "url": "http://fr.wikipedia.org/wiki/Git"
        },
        {
           "name": "wiki",
           "url": "http://fr.wikipedia.org/wiki/Wiki"
        }
      ]
    }
  ]
```

This has been discussed here: mudassir0909/jsonresume-theme-elegant#81

**Comment by stp-ip** [comment]
Thanks for proposing, we had a similar idea with making it possible to substitute plaintext fields with markdown.

**Comment by KOLANICH** [comment]
I don't think it is a nice idea to support links and other markdown in category fields like tags. Tbe behavior should be implementation defined. Tags have semantics being tags, machine readable semantic meaningful identifiers which are not needed to be cleaned from crap. Tags are not links to external resources, and every resource decides itself what click on tags should do. In most cases it triggers search, in some cases it shows word definition. Tags is just the way to say to the website "this document is about %tagname%, please, use this information".

**Comment by James-Firth** [comment]
I like the second idea of having the url as a separate key, otherwise you force all readers/renderers to understand the markdown syntax as well.

**Comment by stp-ip** [comment]
So the current state or plan is to either provide a ```url``` field, if deemed necessary within the schema or use the proposed meta.enhancedText section, which might overwrite fields with a markdown based variant.

Gonna close this as it can be tracked within the #204
