### ISSUE TITLE
Can't resume publish (own url)

### ISSUE THREAD

**Issue by willnwhite** [jsonresume/resume-schema#251]
I'm doing `resume publish`.

![screenshot 2016-09-16 13 40 42](https://cloud.githubusercontent.com/assets/8081877/18586193/4d647c0a-7c13-11e6-9025-4c92362dc41e.png)

Choosing this (have own url) or just "Publish to your account".

![screenshot 2016-09-16 13 42 40](https://cloud.githubusercontent.com/assets/8081877/18586216/78b234f6-7c13-11e6-9ea1-86fdc6d8459f.png)

Getting this.

**Comment by aloisdg** [comment]
it is a cli problem. Try `login` first.

**Comment by stp-ip** [comment]
Closing. @aloisdg already said it's a cli issue.
