### ISSUE TITLE
Education Honors

### ISSUE THREAD

**Issue by FranciscoG** [jsonresume/resume-schema#255]
in the education part of the schema there is no section to add honors like "magna cum laude" 

``` json
"education": [{
    "institution": "University",
    "area": "Software Development",
    "studyType": "Bachelor",
    "startDate": "2011-01-01",
    "endDate": "2013-01-01",
    "gpa": "4.0",
    "courses": [
      "DB1101 - Basic SQL"
    ]
  }],
```

Recommendation based on the following [Harvard recommendations](http://hls.harvard.edu/dept/opia/job-search-toolkit/resume-layout-guidance/):

Add `"honors"` and `"activities"` to `"education"` section
honors = single string
activities = array of strings

``` json
...
    "honors" : "Magna Cum Laude",  
    "activities" : ["Mentorship Program", "Debate club"].
...
```

**Comment by aloisdg** [comment]
I am not against. Is ii an enum?

**Comment by FranciscoG** [comment]
I think so, seems to be only 3 honors distinctions that are common

- gpa for cum laude - 3.5 to 3.7; 
- gpa for magna cum laude - 3.8 to 3.9; 
- gpa for summa cum laude - 4.0+. 

found those GPA estimates on [this site](http://www.academicapparel.com/caps/cum-laude.html)

**Comment by aloisdg** [comment]
It depends. [Some countries differ](https://en.wikipedia.org/wiki/Latin_honors#Use_of_Latin_honors_around_the_world).

**Comment by FranciscoG** [comment]
true,  then I would just leave it open as a string instead

**Comment by aloisdg** [comment]
Also, I think that this field should be optional like the GPA.

**Comment by FranciscoG** [comment]
agreed, definitely optional

**Comment by stp-ip** [comment]
Sounds reasonable to consider adding it.

**Comment by villasv** [comment]
I'd also like to have such field, and keep it a string instead of Enum. Some military institutions have arbitrary honors for students.

**Comment by stp-ip** [comment]
Contributions are always welcome.

I think for now it seems reasonable to start with just adding honors:
```
    "honors" : "Magna Cum Laude"
```
No Enum, optional and free string field under the education section.

Activities seems to be handled by the new projects section now.

**Comment by thomasdavis** [comment]
Bring it in, PR needed.

**Comment by thomasdavis** [comment]
Upon reflection, I disagree with myself above. 

Honors can be communicated in other ways.
