### ISSUE TITLE
Define required fields

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#260]
Should be done after the schema stabilizes.

**Comment by aloisdg** [comment]
I dont remember if we already talk about it. I think so. Well, when the schema stabilizes and this list is done, I think we should show this as JSONResume. This schema should be simple and clutterless. Everything else are extensions we could add into it.

**Comment by stp-ip** [comment]
The most interesting case was the additional information section for personal information. It should be defined, but not required as this might be illegal in some parts of the world.

**Comment by KOLANICH** [comment]
IMHO all the fields must be optional.

**Comment by stp-ip** [comment]
@KOLANICH So a resume with only the schema version should be valid. Not sure I completely agree, but I see the reasoning.

**Comment by thomasdavis** [comment]
I'm on the side of optional too. Evidently it seems resumes/cvs are the most debatable things ever, let's make our job easier and keep the constraints minimal.

**Comment by evanplaice** [comment]
@thomasdavis Optional everything makes it more difficult to define templates

For example, if work requires `name` then you can conditionally render work to be `company(, position)` where the position is optional. If both are optional you have to cover 3 cases.

`(company, position)`

`(company)`

`(position)`

This applies to all header fields (ex `project.name`, `project.entity`, `project.type`)

**Comment by evanplaice** [comment]
Alternative proposal: Make everything optional

Ex: some countries apparently require your date of birth and photo on a CV. In the US, including either is strongly discouraged b/c anti-discrimination laws on the basis of age or race are a thing.

I have read through every issue on this repo. The vast majority of suggested changes to the schema won't happen despite being good for individual use cases.

Leaving the option for users to custom tailor their own resume helps support all of those users whose specific needs fall through the cracks and encourages experimentation.

**Comment by thomasdavis** [comment]
Agreed with @evanplaice. 

Themes and `meta` can take care of individual preference for now.
