### ISSUE TITLE
Use resources for additional urls within publication, projects etc.

### ISSUE THREAD

**Issue by stp-ip** [jsonresume/resume-schema#263]
Add ```resources``` as url array to provide the possibility to add more than one link to a project.

The proposal would be something along the lines of:
```
...
"resources": [{
  "url": "example.com/my-awesome-slides/",
  "label": "slides"
  },
  {
    "url": "example.com/my-awesome-talk-as-video/",
    "label": "video"
  }
]
...
```

**Comment by aloisdg** [comment]
`label`  is fine

**Comment by stp-ip** [comment]
Updated -> ```label```

**Comment by thomasdavis** [comment]
Looks great, let's do it.

**Comment by SharePointOscar** [comment]
Hi!  I was looking over the schema and gave a little more thought as to how many times recruiters or other folks ask the same question "What projects did you use x skill?"  Also, there are always multiple projects one works on for a given contract or full time role. 

Would it make sense to add the **Projects[]** section? @efarr added that section on his [project](https://github.com/efarr/visual-resume/blob/master/src/sample-resume.jsonl)  I feel it makes sense to add it to the standard schema, thoughts?

Here is a snippet
` ``json 
{
      "company": "EagleEye Analytics",
      "position": "VP of Engineering",
      "website": "http://eeanalytics.com",
      "startDate": "2014-01-06",
      "summary": "Lead development and IT operations. EagleEye delivers advanced machine learning based predictive analytics to the insurance industry as a service (SaaS).",
      "highlights": [
        "Modernized tech stack from Silverlight, WCF, ADO.NET and TFS to HTML5, WebAPI, MVC, Entity Framework, Git, TeamCity, and Octopus Deploy.",
        "Reduced monthly IT spend by 40%.",
        "Reduced system errors by 75% in first six months.",
        "More than doubled development team output.",
        "Delivered major new release users and sales team rave about. Sales presentations moved from all PowerPoint to all software demo."
      ],
      "projects": [
        {
          "name": "Build Talon Analytics Dashboard",
          "startDate": "2014-07-15",
          "languages": ["C#", "JavaScript"],
          "tools": ["D3", "HTML5", "WebAPI", "ASP.NET MVC", "Entity Framework", "Google Maps"],
          "capacities": ["Manager", "Architect", "Developer"]
        },
        {
          "name": "Maintain and Enhance Talon Analytics Workbench",
          "languages": ["C#"],
          "tools": ["WCF", "ASP.NET", "D3", "Entity Framework"],
          "capacities": ["Manager"]
        }
      ]
    }
```

**Comment by thomasdavis** [comment]
I apologize for my previous agreeance, the variability doesn't suit the audience.
