### ISSUE TITLE
Rename Label

### ISSUE THREAD

**Issue by pomy** [jsonresume/resume-schema#273]
Can we rename 'VOLUNTEER WORK' heading to 'PROJECTS' for themes? - if yes, then how?
Thanks

**Comment by pomy** [comment]
I tried to change label from index.js file of jsonresume-theme-elegantprofile but this change doesn't work.

**Comment by stp-ip** [comment]
This is something to be done on the theme level and not on the schema level. Closing this.

If I misunderstood, please reopen.
