### ISSUE TITLE
How to create multi-lingual versions of a resume?

### ISSUE THREAD

**Issue by stephen-kruger** [jsonresume/resume-schema#274]
It seems the "description" field in the schema does not support any language specifiers.
Would it be possible to include lang/locale information to allow authoring of a multi-lingual resume?

"description" : [
  "en-US" : "my colorful resume",
  "en-UK" : "my colourful resume"
]

**Comment by stp-ip** [comment]
There is a proposal to add multilingual features via the meta data section. Basically one provides a base resume and then overwrites various fields with a new language. #35

**Comment by fballiano** [comment]
yep, this should be closed as duplicate of #35
