### ISSUE TITLE
Could be nice to have an exemple of the different level for the skills and normalize it

### ISSUE THREAD

**Issue by bussiere** [jsonresume/resume-schema#275]
Here are the part that bug me : 

```
          "level": {
            "type": "string",
            "description": "e.g. Master"

```

Could be nice to standardize  : 

          "level": {
            "type": "string",
            "description": "e.g. Master / Intermediate / Beginner "

**Comment by aloisdg** [comment]
Hello bussiere!

A lot of us agree with you. We have an issue about it. Feel free to step by #16 and share your thoughts.

I think this issue is a duplicate. Can we close it? ( cc @stp-ip )

Cheers

**Comment by bussiere** [comment]
yes close it or delete it :)
