### ISSUE TITLE
Normalisation and  Convention of category like skills.

### ISSUE THREAD

**Issue by bussiere** [jsonresume/resume-schema#276]
May it could be nice to have some convention for group of data ?

Like for skills : 

```
  "skills": [
    {
      "name": "Web Development",
      "level": "Master",
      "keywords": [
        "HTML",
        "CSS",
        "Javascript"
      ]
    },
     {
      "name": "Programming",
      "level": "Master",
      "keywords": [
        "Python",
      ]
    }
```

And what it should contains ?

Just to make the parsing simpler ?

**Comment by stp-ip** [comment]
Could you explain in more detail, what the change would be and the value you see besides simpler parsing (on the machine side I assume)?

**Comment by bussiere** [comment]
@stp-ip not a change in the code , but a normalisation in the data text nd organisation.

If i want to parse a lot of resume in json, it could be nice that each one have the same normalisation.

Like all the programming langage in a Programming named Skill.

For django do i put it in Programming or do i make a Web Framework skill ?

To normalise the data organisation like making a readme with example to propose a normalisation.

That if someone want to parse all the resume he is sure that they all follow the same logic for the data organisation.

Not changing the code of the json resume but propose a data normalisation on where to put what.

**Comment by stp-ip** [comment]
Ok now I get the whole proposal.
This needs a bit more thought as we past discussion always resulted in normalization would not be generic enough for now and we are going with open fields for now.

If you have a specific proposal, feel free to write something up. For now the suggestion is logged and we'll see how we might incorporate that into v1.

Thanks for your contribution.

**Comment by thomasdavis** [comment]
@bussiere An app that implements JSON Resume can take care of this. It would be impossible for us to enforce homogeneity. Imagine we try do this in English, JS, Javascript, ES6, which one? Then multiply that by 100 for every language in the world.

**Comment by evanplaice** [comment]
I agree 100%. This scale is hardly taken serious in a dev context. Not to mention, many industries use their own grading scales.

If the desire is to have a cool looking progress-bar, or other visual effect to indicate skill; then the specifics and logic for that can be encapsulated in the template. This isn't a schema-specific issue.

**Comment by thomasdavis** [comment]
As above, the more granularity, the less practicality. 

Abstract packages that can prove large use should influence a schematic decision like this,
