### ISSUE TITLE
References

### ISSUE THREAD

**Issue by briankotch-invisionapp** [jsonresume/resume-schema#281]
This seems limited:
 
"references": [{
    "name": "Jane Doe",
    "reference": "Reference..."
  }]

Could we add more information to the references section? 
Something like:

 "references": [{
    "name": "Jane Doe",
    "relationship:"manager",
    "company":"Acme Industries",
    "email":"jane.doe@acme.com",
    "phone":"555-555-1212",
  }]

**Comment by stp-ip** [comment]
There is a longer discussion available here: https://github.com/jsonresume/resume-schema/issues/2

We do accept PRs.

**Comment by stp-ip** [comment]
Would close as duplicate, if you think otherwise, please reopen.

**Comment by briankotch-invisionapp** [comment]
👍
