### ISSUE TITLE
Being able to specify default theme in resume.json

### ISSUE THREAD

**Issue by yxliang01** [jsonresume/resume-schema#283]
I can see this would be useful. By default theme, it means it can be overridden by `--theme` argument to the cli.

Thanks

**Comment by aloisdg** [comment]
I don't think a theme should be in the resume itself or as a meta tag. We could also use another file like a `.resume` with all config settings.

**Comment by evanplaice** [comment]
You can add arbitrary fields to the `meta` section. Maybe this could be integrated with `resume-cli` in the future.

I'm going to close for now, if you'd still like it added open an issue on `resume-cli.
