### ISSUE TITLE
Single Phone Numbers may be too strong a constraint

### ISSUE THREAD

**Issue by claudeduguay** [jsonresume/resume-schema#285]
It's pretty common now for folks to have either a Cell and Home number or Cell and Work, or all three. I suspect basics.phone should be a list.

**Comment by aloisdg** [comment]
Also some people don't like to be call before or after a specific hour.

**Comment by stp-ip** [comment]
Proposal:

* phone as list/array
* add call hours (stored with timezone)

**Comment by NewAlexandria** [comment]
This is a resume - who lists their work number? Or anymore, who gives their home number?

Availability time is interesting.  Useful for discriminating between 'before and after dayjob' people, and 'I have daytime availability' people.  Still probably hard to use this field without a calendar integration.

**Comment by stp-ip** [comment]
One example for listing their work number would be internal job applications in huge corporations. But it might just be local and international numbers and that alone would warant the suggestion for a list of numbers I would say.

Haven't looked at discriminatory aspects of adding call hours. Question is. Is it better to be called off guard and not specify hours or specify them and not get called at all. Might be the same result and if your new employer doesn't respect boundaries it might not be the right one in the case one can choose.

**Comment by wayneamurphy** [comment]
I'm flip-flopping when reading this. Good idea, but wait it's true why include more than one number?
Overall this project seems to be for various people, not just people in the tech sector.
So even a kid whose parents split up and they live at different houses different days of the week - they'd have multiple phone numbers, but hopefully if one house gets called somebody would pass along the message to the other house.
So I'd say it is a good suggestion, but not essential.
If anything, the idea of preferred contact method, and a timezone for phone calling seems best.

**Comment by thomasdavis** [comment]
Considering the discussion, as per `basics.name`, a persons phone is highly contingent on location, cultural and personal preference. 

Trying to support all for data integrity is essentially incompatible with simply rendering a number the person can be called upon in context.
