### ISSUE TITLE
Add mark and weight to courses

### ISSUE THREAD

**Issue by collimarco** [jsonresume/resume-schema#286]
I would like to use resume-schema for my CV. I'm from Italy and the schema misses two important properties for courses (inside education):

- **mark** (e.g. `9 / 10`, `30 cum laude / 30`)
- **weight** (e.g. `12 CFU`, see https://en.wikipedia.org/wiki/European_Credit_Transfer_and_Accumulation_System)

**Comment by stp-ip** [comment]
We are currently looking into a better system for grading and skill levels. Thanks for giving another resource to look into.

**Comment by DandyDev** [comment]
Discussed in #288, first proposal in #328, fixed in #391
