### ISSUE TITLE
Add Marking Scales for non-USA Courses.

### ISSUE THREAD

**Issue by GeorgeWL** [jsonresume/resume-schema#288]
GPA is meaningless for any countries outside of the USA.

The system of grading for Courses outside of the USA is very different from the USA standard of GPA and the A-B-C-D-E-F equivalent.

![image](https://user-images.githubusercontent.com/5931248/27925654-81cd390e-627d-11e7-9a31-469a9f1113de.png)
https://en.wikipedia.org/wiki/Grading_systems_by_country

The major problem is there's a veritable mass of confusing and non-compatible systems.

The EU tries to combat that by using the standard of ECTS to convert the local grading scale (where it takes whatever the original grading scales, divides them into 5 and places them in the equivalent locations on there own scale.)

But the ECTS is still not accepted in all EU countries, and is rarely used outside of the EU.

https://en.wikipedia.org/wiki/ECTS_grading_scale

![image](https://user-images.githubusercontent.com/5931248/27926139-4fa3db66-627f-11e7-8235-c69f83fc9bb1.png)

**Comment by stp-ip** [comment]
Hey thanks for reaching out. Yes we are already considering that. Hopefully we will have something tangible soon.

**Comment by GeorgeWL** [comment]
The simplest (but probably not exactly future-proof) is to just rename the field to Grade.
