### ISSUE TITLE
Add Contact and Position fields to references

### ISSUE THREAD

**Issue by mesquka** [jsonresume/resume-schema#290]
I use 'name', 'phone', 'email', and 'position' but not reference (via custom renderer). This should be added to the formal spec as the norm in some places is to provide a verbal reference (i.e. Australia where I live)

**Comment by stp-ip** [comment]
Hey thanks for reaching out. Happy to consider it in more detail. Could you give a bit more details on the actual implementation you use and the specific requirements you try to solve in comparison to the current schema ideas (from your viewpoint).

Thanks

**Comment by NewAlexandria** [comment]
In he US it is not typical to give references without specific request.  The idea makes more sense of that is common elsewhere.  I see these fields being more valuable to recruiter/ATS systems

**Comment by stp-ip** [comment]
In Germany you might give references, but you wouldn't include any details about the person without request. That came up the last time we discussed adding references. The suggestion then was to basically add address, phone, mail of all references too, which I still decline to add due to privacy concerns.

**Comment by keremcankabadayi** [comment]
In my country, Turkey, we can give reference with permission from that person. we add

> John Doe / IT Manager
> John's Company
> some-email@mail.com, +49 111 111 111

**Comment by wayneamurphy** [comment]
I would agree about not including them in the initial resume, to easy for a bot to see them and spam the people you normally request a reference from.
Having said that, if one day somebody creates a resume-references.json schema, it should include preferred contact method, preferred time of day, and what time-zone the reference is in.

**Comment by wayneamurphy** [comment]
Was this issue closed because it was resolved (with another issue number), or because it was deemed not worthwhile?
