### ISSUE TITLE
Any way to include formatting & links in fields?

### ISSUE THREAD

**Issue by dzg** [jsonresume/resume-schema#292]
Wow, this is awesome! Just what I was looking for!

Is there any way to have formatting and links within "fields"? E.g., what if I want some words italic within a job summary, and some words to link to websites?

(Sorry if this is a stupid question, I'm a bit of a noob)

And is this project still alive? I hope so...

**Comment by stp-ip** [comment]
There is a lot going on behind the scenes, so not dead yet. The idea is to have all your data in the schema, but not any formatting. There is a proposal to have an overlay formatted string available, but that's something for the long term.
In theory you could add markdown in your data fields, but that needs to be supported by the theme itself.

**Comment by dzg** [comment]
I see, thanks.

Sorry, how could a template support markdown? Wouldn't that have to be part of the js?
Maybe there is a js module that would parse & expand any markdown? I'll Google it.

**Comment by stp-ip** [comment]
A plain jsonresume template doesn't support it by default, but one could make it work with js or use another static site generator to use the schema data.

**Comment by chrisdotcode** [comment]
Hey @stp-ip, I've been out of the loop for sometime now (as you can probably tell), any pressing issues that need some more help that I can dive into?

Apologies for hijacking your thread, dzg, but stp-ip seems to have answered your question, and I didn't want to create a whole issue for noth.

**Comment by stp-ip** [comment]
Nothing completely pressing I can think of.

**Comment by evanplaice** [comment]
This doesn't really affect the schema. It would either need to be integrated into the template or into `resume-cli` itself.

I'm going to close this. If you're still interested in this feature file a new issue on the `resume-cli` repo.
