### ISSUE TITLE
Live schemas vs v1.0.0

### ISSUE THREAD

**Issue by XuluWarrior** [jsonresume/resume-schema#296]
While writing my new template, I am coming across a number of inconsistencies with the schemas used.

In **master**, [schema.json](https://github.com/jsonresume/resume-schema/blob/master/schema.json) uses the property **url** for all website urls in all sections. (https://github.com/jsonresume/resume-schema/commit/fb50a87ad0e22d9d4e73bb7cc637b4dcecb38711)

However [resume.json](https://github.com/jsonresume/resume-schema/blob/master/resume.json) in the same folder still uses the property **website**.  I believe that this is version that [registry.jsonresume.org](http://registry.jsonresume.org) uses and the schema definition at [jsonresume.org/schema](https://jsonresume.org/schema)  is based on.

To confuse things even more, the default branch shown on the [github page](https://github.com/jsonresume/resume-schema) for resume-schema is v1.0.0.  This has more changes such as changing work.company to work.name and so using the [example schema](https://github.com/jsonresume/resume-schema/blob/v1.0.0/examples/valid/complete.json) from GitHub (as I did for developing my template) results in incompatibility with the data used in registry.jsonresume.org.

Which schema is considered canonical?
What is the status of v1.0.0? Is it likely to be released any time soon?

**Comment by stp-ip** [comment]
v1.0.0 is not yet ready and registry.jsonresume.org uses the last release, which should be https://github.com/jsonresume/resume-schema/tree/0.0.0.
Hope that helps. But this definitely needs to be cleaned up soonish. Thanks for bringing it up.

**Comment by XuluWarrior** [comment]
If v1.0.0 isn't ready yet, would it be possible to change the default branch for resume-schema so that the first thing a developer sees is not the wrong scheme to use?
Or at least have a bold message pointing them in the right direction.

**Comment by XuluWarrior** [comment]
There is also the issue that in master, schema.json and resume.json are inconsistent with each other.

**Comment by XuluWarrior** [comment]
@stp-ip I should also add a thanks for your prompt response :)

**Comment by stp-ip** [comment]
The reasoning for the default branch was that devs tried submitting issues and PRs for thing we already "fixed" in the new version. To prevent that the default branch was switched. It has the side effect, that user-devs consult both the docs and the branch for things, it breaks for them. Not sure how to optimally fix that. @thomasdavis

**Comment by stp-ip** [comment]
For the issue difference in schema.json and resume.json the idea was first to get a new spec ready and then fix the resulting resume example I think.
There is a cleaned up version of the schema, but without any tooling yet at github.com/resumic/resumic

**Comment by XuluWarrior** [comment]
So what is the relationship between resumic and jsonresume?  
Will one eventually subsume the other?

**Comment by stp-ip** [comment]
That's not determined yet. Hopefully they will agree on the same schema later on and then the main difference is branding and tooling.
Resumic will recreate tooling in Go and use Hugo for themes in the future. The schema itself is based on jsonresume, but it added all current discussions already into the schema. Might be a bit more opinionated for now, but we wanted to move forward.

**Comment by stp-ip** [comment]
Disclaimer: Launching Resumic was done on my account and I'm supporting it via Okkur Labs. I'm also a maintainer here. So it's not so much competing, it is trying to move faster and improve tooling without the need to care about legacy for now.

**Comment by evanplaice** [comment]
The current `schema.json` uses `url` consistently and `resume.json` no longer exists in this repo. This issue should be resolved as long as you use `url` instead of `website.
