### ISSUE TITLE
Work position should be positions (an array)

### ISSUE THREAD

**Issue by harlowja** [jsonresume/resume-schema#297]
I've worked at the same place under multiple positions (as I would suspect most have); so it seems like the position entry in a work entry should really be an array (or is it expected that each new position in the same company is a new work entry?)

**Comment by stp-ip** [comment]
For now we would keep yeah position as separate work entry. A theme could still show it differently so. Will take that into consideration for a new schema.

**Comment by heylookltsme** [comment]
I agree with this. It is redundant to list the company multiple times. I think an improvement to the schema would be something like, 

```json
"work": [
  {
    "company": "Initech",
    "website": "https://initech.com",
    "positions": [
      {
        "title": "Engineering Manager",
        "startDate": "2006-08",
        "endDate": "2008-09",
        "summary": "",
        "highlights": []
      },
      {
        "title": "Senior Engineer",
        "startDate": "2004-08",
        "endDate": "2006-08",
        "summary": "",
        "highlights": []
      },
    ]
  },
  {
    "company": "Conglomo",
    "website": "",
    "positions": [
      {
        "title": "Engineer",
        "startDate": "",
        "endDate": "",
        "summary": "",
        "highlights": []
      }
    ]
  }
]
```

Does anyone know offhand of any themes that show multiple positions under a single company heading? I haven't seen any. It's hard to tell though because the example resumes never include multiple positions at the same company. :( 

If themes can be written to not repeat company information with the current schema, then I don't feel super strongly about this. But I do think a schema like the above makes more sense. 👍

**Comment by michaltalaga** [comment]
any chance this gets done?

**Comment by effrenatus** [comment]
> I agree with this. It is redundant to list the company multiple times.

Another year on, and I just wanted to say I also agree. Just made my own for a small personal project and included a positions array. Redundant company data isn't ideal. 

Two obvious use cases here include:
1. getting promotions or other changes of title within Company A during one period of employment and 
2.leaving Company A and then returning to it some time later.
 
Both seem better served by a positions array. Is there a case I'm not considering where the current schema is a better representation of an individual's work history?

**Comment by veeravn** [comment]
I would like to see the position become array.  I just got a promotion at my company but the only that changed was my title.

**Comment by thomasdavis** [comment]
This suggestion is obviously reasonable, as of now, it is really just dictated by the theme developers. 

They don't seem to get much push back on the idea that you can just simply create a duplicate entry for that company and list your role and highlights again. 

There isn't enough pressure to put this into `v1`
