### ISSUE TITLE
Suggestion: Project simplification and clutter removal

### ISSUE THREAD

**Issue by hacksalot** [jsonresume/resume-schema#300]
Hello all,

So, the key artifact in the resume-schema repository is the resume schema itself, `schema.json`. Everything else is supporting boilerplate. For cleaner `npm install` behavior and dependencies and general DRYness, the project organization should reflect this.

Suggestion 1: Move the validator and all other non-essential code to an external project. Lose the sample resume document, etc. This repo should be about the management and versioning of the resume schema document itself, as a timeless artifact, punctuated by official releases. Those other aspects and functionality can be addressed through documentation and the general context.

Suggestion 2: Change the `main` entry in package.json to return the official JSON resume schema and nothing else. Currently it exposes an intermediate object containing the schema JSON alongside the validator. If suggestion 1 is implemented, there will be no validator to expose (not in this project, anyway), so the `package.json` can have its `main` set cleanly as `schema.json`.

Just a couple suggestions that would make life slightly easier for us tool builders and make it slightly easier to justify including `json-resume` as a formal dependency in tools that may be a bit OCD about clean dependency trees.

Thanks!

**Comment by hacksalot** [comment]
Just as an addendum to that last point. Here's the output after `npm i resume-schema`:

```
`-- resume-schema@0.0.16
  `-- z-schema@2.4.10
    +-- bluebird@3.5.1
    `-- request@2.83.0
      +-- aws-sign2@0.7.0
      +-- aws4@1.6.0
      +-- caseless@0.12.0
      +-- combined-stream@1.0.5
      | `-- delayed-stream@1.0.0
      +-- extend@3.0.1
      +-- forever-agent@0.6.1
      +-- form-data@2.3.1
      | `-- asynckit@0.4.0
      +-- har-validator@5.0.3
      | +-- ajv@5.5.2
      | | +-- co@4.6.0
      | | +-- fast-deep-equal@1.0.0
      | | +-- fast-json-stable-stringify@2.0.0
      | | `-- json-schema-traverse@0.3.1
      | `-- har-schema@2.0.0
      +-- hawk@6.0.2
      | +-- boom@4.3.1
      | +-- cryptiles@3.1.2
      | | `-- boom@5.2.0
      | +-- hoek@4.2.0
      | `-- sntp@2.1.0
      +-- http-signature@1.2.0
      | +-- assert-plus@1.0.0
      | +-- jsprim@1.4.1
      | | +-- extsprintf@1.3.0
      | | +-- json-schema@0.2.3
      | | `-- verror@1.10.0
      | |   `-- core-util-is@1.0.2
      | `-- sshpk@1.13.1
      |   +-- asn1@0.2.3
      |   +-- bcrypt-pbkdf@1.0.1
      |   +-- dashdash@1.14.1
      |   +-- ecc-jsbn@0.1.1
      |   +-- getpass@0.1.7
      |   +-- jsbn@0.1.1
      |   `-- tweetnacl@0.14.5
      +-- is-typedarray@1.0.0
      +-- isstream@0.1.2
      +-- json-stringify-safe@5.0.1
      +-- mime-types@2.1.17
      | `-- mime-db@1.30.0
      +-- oauth-sign@0.8.2
      +-- performance-now@2.1.0
      +-- qs@6.5.1
      +-- safe-buffer@5.1.1
      +-- stringstream@0.0.5
      +-- tough-cookie@2.3.3
      | `-- punycode@1.4.1
      +-- tunnel-agent@0.6.0
      `-- uuid@3.2.1
```

Output after the comparable `npm i fresh-resume-schema`:

```
`-- fresh-resume-schema@1.0.0-beta
```

I think the majority of `require()s` of `resume-schema` found in the wild will be people looking for the actual schema document, not validation, documentation, and a sample resume. The primary consumer of this repository is going to be a *tool*, which again points toward having the simpler structure suggested above.

**Comment by evanplaice** [comment]
Work on this is under way. 2 deviations, the sample stays and the tests stay; both are required to test the schema to make sure no regressions are introduced when it's updated.

The validation will be moved out but the exports mapping will stay for backward-compatibility until the next major release. It wouldn't be very user-friendly to break the validation if there is external tooling that depends on it.

To track the progress on this, see #349
