### ISSUE TITLE
Resume Uploaded to registry resolves with 504 error

### ISSUE THREAD

**Issue by reustonium** [jsonresume/resume-schema#302]
My resume that I uploaded to the registry resolves with a 504 error from cloudflare.  Is there a known issue with resumes hosted on the registry?

**Comment by stp-ip** [comment]
paging @thomasdavis as he is in charge of the hosted stuff.

**Comment by thomasdavis** [comment]
This has been resolved, reference https://github.com/jsonresume/registry-server/issues/98
