### ISSUE TITLE
What about teaching?

### ISSUE THREAD

**Issue by ttben** [jsonresume/resume-schema#305]
Hello there!
I just discovered all your work and effort and found it really interesting and promising.
My question is simple: 
as a teacher, I want to expose the courses I gave during my career.
How can I do that?

More generally, how handling domain/career-specific informations (eg: courses for teachers, game for game developers, ...)?
Is there any thinking in this direction?

**Comment by stp-ip** [comment]
In the evolution of the schema there are projects, which might fit these more domain specific things. https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L381

It's not ready yet, but should map to more domain specific or project based work.
The idea is to have a work item such as "Teacher at School xyz" and supplement this with specific projects, which can relate to the work or not such as "Course abc for School xyz"/"Course abc".

Happy to get a bit of feedback on the idea and structure.

Currently the annoying approach would probably be one work item per course and change the specific resume layout a bit to group them together.

**Comment by wayneamurphy** [comment]
Maybe you had the notion first, but I saw there was also #308 for speaking/panels/etc, maybe it can relate to that?

**Comment by thomasdavis** [comment]
Most learning organisations are also companies, you can list it as so. If there was NGO or non-profit behavior, just describe it in `summary`
