### ISSUE TITLE
Add _Speaking Engagements/Talks/Panels_ to schema

### ISSUE THREAD

**Issue by AlexanderMann** [jsonresume/resume-schema#308]
# Motivation

For many, a lot of what makes their cv important is their public engagement. Whether that be along the lines of speaking at a conference, appearing on a panel, etc.

Presently, there's not a clear cut section where these types of engagements should live (similar to the [Publications](https://github.com/jsonresume/resume-schema/issues/307) issue).

# Thoughts

The two thoughts I have here:
- adding these sections into the resume schema seems worthwhile and pretty striaghtforward
- maybe a generic "other" section which allows for some formatting would be beneficial?
  - Is encouraged to support Markdown?
  - Allow for labelling section headers and making lists etc.?

# Contributing

I'd be happy to make a pr to add this in, very new here, but I'm unsure as to whether this'd be supported/which path to take and then how theme admins go about getting their changes in etc.

# Thanks

Love JSON Resume and what it's about. Also hate making/keeping resumes up to date, so thanks for making it programmatic and straightforward!

**Comment by shamoons** [comment]
Would love to see this!

**Comment by thomasdavis** [comment]
For now, the best chance is to add to `awards` or `certificates` with descriptions that broach on your accomplishments.
