### ISSUE TITLE
Could use 2 more basic fields

### ISSUE THREAD

**Issue by jphellemons** [jsonresume/resume-schema#317]
I would like to add birthday and (place of birth or hometown) to the basic part of the schema.
I am building a custom theme and manually adding the fields in the resume.json and using them in the theme does not work, so please update the readme.md with info how to add "custom" fields or propose fields for the schema.

**Comment by wayneamurphy** [comment]
I just found this project yesterday, so I cannot comment on the quietness or solve everything.

But I will comment that the request seems odd? It is for a resume not a life story :-) and it would seem rare for a resume to include a birthplace/hometown. A potential employee just wants to know where you live (and often it doesn't include an address but just the city).

As for DOB I'd think people would say that is a privacy issue. Only give people the information they need to know, when they ask. Similar to the fact that you might need to provide a social security number or driver's license on a hiring form, but it shouldn't be on a public resume.

**Comment by phoinixi** [comment]
Unfortunately this doesn’t apply worldwide. It’s not a privacy issue in Europe for example. Some countries “require” a picture too. They would be optional fields anyway.

**Comment by LucaBernstein** [comment]
Stumbled upon this issue since I am also missing a `birthdate`. It would enable rendering an age for instance. Would also appreciate that in the schema.

**Comment by thomasdavis** [comment]
The schema tries its best to support culturally differences, but trying to include them all makes it impracticable. 

Create extra themes/packages until it can be proven that this requirement is common.

**Comment by lassegs** [comment]
Here's proof that this is common practice in Norway. It's the Google translated web site of a union for natural science graduates. I could have picked several other sources, in some form or another they all list it the same as this article:

- "Year of birth and country"

https://www-naturviterne-no.translate.goog/cv-og-jobbsoknad/slik-lager-du-en-ryddig-og-oversiktlig-cv-article17310-430.html?_x_tr_sl=no&_x_tr_tl=en&_x_tr_hl=no&_x_tr_pto=wapp
