### ISSUE TITLE
Readme file: The link under research results in 404

### ISSUE THREAD

**Issue by nnyit** [jsonresume/resume-schema#319]
Research
A more professional recruitment process with structured data.
https://github.com/jsonresume/resume-schema/blob/v1.0.0/research/A%20more%20professional%20recruitment%20process%20with%20structured%20CV%20data.pdf

**Comment by stp-ip** [comment]
https://github.com/jsonresume/resume-schema/raw/0.0.0/research/A%20more%20professional%20recruitment%20process%20with%20structured%20CV%20data.pdf

**Comment by evanplaice** [comment]
Why was that deleted following the v0.0.0 release. Should it be kept in or removed from `README.md` altogether?

**Comment by evanplaice** [comment]
Looks like it was added by @fredsterss in #52 (25735c4af37e69e3808d2796483707a8af8a4c04)

Then removed by @olivif in #239 (d9e0c587697bbf7149a6241725bd8c09b94b457)

**Comment by evanplaice** [comment]
The document has been restored. If it needs to be removed, that can be done during the Cleanup phase later.
