### ISSUE TITLE
Put in a section for standalone courses

### ISSUE THREAD

**Issue by DandyDev** [jsonresume/resume-schema#32]
The `education` section really doesn't lend itself well for things like MOOCs (Coursera, Udacitiy etc.), because there's no degree involved, and only one course etc.
Maybe there should be separate section for courses like that? Just like on LinkedIn :)

**Comment by thomasdavis** [comment]
This hasn't been a persistently requested addition over the years, most users run with the theme developers of which haven't implemented as much detail.
