### ISSUE TITLE
URL elements without uri format definition

### ISSUE THREAD

**Issue by lfbn** [jsonresume/resume-schema#320]
These elements shouldn't have also format URI added:

* profiles > url
* publications > url
* meta > canonical

https://github.com/jsonresume/resume-schema/blob/3bfe84eaddd08ce1bd754920823202560bc6eec6/schema.json#L282

Thanks.

**Comment by evanplaice** [comment]
Fixed in [v0.1.1](https://github.com/jsonresume/resume-schema/releases/tag/v0.1.1)
