### ISSUE TITLE
Add a field for preferred pronouns

### ISSUE THREAD

**Issue by aidan-fitz** [jsonresume/resume-schema#324]
I would like to be able to put my preferred pronouns on my resume. For most users, this will be a bare string (e.g. `they/them/theirs`), but it should also be possible to add more complex data to it, such as:
- pronoun.is link (e.g. `http://my.pronoun.is/they`)
- an array of pronouns to which the theme can apply special formatting
  - example: `["they", "them", "theirs"]` becomes "they / them / theirs" or "they &bull; them &bull; theirs" depending on the theme

For inspiration, [this article][asana] discusses how Asana implemented preferred pronouns in profile settings.

[asana]: https://blog.asana.com/2018/05/product-process-adding-pronouns-asana-profile-settings/

**Comment by thomasdavis** [comment]
Pronouns are not common standard. 

Add to the top level `meta` and ask theme creators to support it. When enough traction, the schema might possibly support it. 

Thank you!
