### ISSUE TITLE
Multiple summaries support.

### ISSUE THREAD

**Issue by punkscience** [jsonresume/resume-schema#329]
People often post for various types of jobs within their discipline -- especially developers. I sometimes apply for a programming job and other times I might be applying for a position looking for more of a management individual. In these cases I often switch between two or more specifically written summaries which would appeal to different types of employers. Another example would be applying to a video game company (less formal, more approachable) vs a stodgy old IT company which wants more formal language. All the experience remains the same but I would like to see the "summary" field become an array of summaries with a default. This is what I am imagining:

"summary": {
"default": "informal_tone",
"summaries": [
  { "id": "informal_tone", "text": "blah blah blah" },
  { "id": "formal_tone", "text": "blah blah blah, Sir" },
]
}

This would allow tools to be built which could help you tailor and select a summary most fitting for wherever you are applying. And tools which do not support it would just refer to the default.

**Comment by wayneamurphy** [comment]
I'll ask how much of the resume would change in tone? Would it just be the summary or where else in the schema?
If it was a lot of places, then it would almost be another copy and the restricting issue is that the tool is looking for one resume.json gist file (versus the ability to use *.resume.json) ?

**Comment by eyesno** [comment]
I only see it as being an issue with the summary. The rest of the data on a resume is typically very factual, detailing experience, dates, tools etc. It's only the summary where the person can outline a specific career objective tailored to a particular company. (I might say "looking for Senior Game Programmer role" if I am applying to a gamedev studio but I might say "looking for a Senior Web Developer role" to a webdev company. A person can be both but the HR department only wants to read what your career expectation is within the context of that company.

I can also see this being useful as hide/unhide tag for certain relevant or irrelevant experience but that's beyond the scope of the change I am proposing here and frankly, it's more than I think is necessary presently.

**Comment by stp-ip** [comment]
There was a bigger discussion about the ability to overwrite content for languages etc. and then filter them. All while having a default source of truth resume. The overwrite would live within the 'meta' section.
One comment from that: 
https://github.com/jsonresume/resume-schema/issues/203#issuecomment-161626244

**Comment by eyesno** [comment]
That solution makes sense for the 'one source of truth' scenario but what I am referring to above is more about tailoring text content. So in a sense, the resume remains the single source of truth but you could look at it like there are multiple truths from which to choose. The clearest example is the difference between saying in the summary:

"Full-stack developer with 20 years experience." when building a resume for IT 

or

"Experienced game developer, having shipped 15 AAA titles in the past 20 years." for games.

I don't think it has to be anything as complicated as metadata -- you simply need to allow for multiple summary tags and configure/select the default one.

**Comment by thomasdavis** [comment]
All variations of a `resume.json` can be handle by a higher level lib, this is one of them.
