### ISSUE TITLE
Company name schema is wrong

### ISSUE THREAD

**Issue by deoxykev** [jsonresume/resume-schema#331]
In the official [schema](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json), the key that renders the value for the company name is `name`, but on the website and almost all theme packages, it is named `company`. All the examples seem to follow the `company` key naming convention. In fact, following the spec exactly will cause all the official themes pulled through the cli to fail.

Therefore, I propose changing the "official" schema to match the observed real world implementation.

### Official Schema
```json
    "work": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": {
            "type": "string",
            "description": "e.g. Facebook"
          },
          "location": {
            "type": "string",
            "description": "e.g. Menlo Park, CA"
          },
          "description": {
            "type": "string",
            "description": "e.g. Social Media Company"
          },
          "position": {
            "type": "string",
            "description": "e.g. Software Engineer"
          },
          "url": {
            "type": "string",
            "description": "e.g. http://facebook.example.com",
            "format": "uri"
          },
          "startDate": {
            "type": "string",
            "description": "resume.json uses the ISO 8601 date standard e.g. 2014-06-29",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "description": "e.g. 2012-06-29",
            "format": "date"
          },
          "summary": {
            "type": "string",
            "description": "Give an overview of your responsibilities at the company"
          },
          "highlights": {
            "type": "array",
            "description": "Specify multiple accomplishments",
            "additionalItems": false,
            "items": {
              "type": "string",
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising"
            }
          }
        }
      }
    }
```

### Actual Observed Implementation
```
"work": [{
    "company": "Company",
    "position": "President",
    "website": "http://company.com",
    "startDate": "2013-01-01",
    "endDate": "2014-01-01",
    "summary": "Description...",
    "highlights": [
      "Started the company"
    ]
```

**Comment by pke** [comment]
Although it makes more sense, that the property is named `name` to be in sync with projects, skills I wonder why it diverged in the themes so badly?
I was just thinking why is no theme rendering the company name? Some privacy issues maybe? The location is also not rendered by any theme.

**Comment by stp-ip** [comment]
Mostly due to v0 being the one implemented in older themes and no huge push was done to change that. :(

**Comment by pke** [comment]
So it would need a little of 22x PRs to get all the themes updated? ;) I think this could be a nice task for a script.

1. `npm find jsonresume-theme-*`
2. `git clone`
3. `sed ...`
4. 'npm t --if-exists`
5. `git commit`
6. `github api to create PR`

Sounds fun :racehorse:

**Comment by evanplaice** [comment]
Not my call but I doubt the schema will change at this point. Since 0.0.0 has been out a while who knows what else builds on top of it. At this point the question isn't if, but how much pain breaking changes will cause.

22 isn't even worth the effort to automate. Got links? I can bang out those PRs in no time.

**Comment by pke** [comment]
@evanplaice nice to see the project getting some traction again.
I just did a `npm find jsonresume-theme-*` to find the obvious themes.
Unfortunately that does not list the GH repos.

**Comment by evanplaice** [comment]
Closing for now, I'll see if I can revisit this to update themes and such after 1.0 drops.

**Comment by antialias** [comment]
> 6. `github api to create PR`

perfect use case for [`hub`](https://hub.github.com/)

**Comment by antialias** [comment]
> @evanplaice nice to see the project getting some traction again.
> I just did a `npm find jsonresume-theme-*` to find the obvious themes.
> Unfortunately that does not list the GH repos.

to get the repo url:
```sh
npm view $packageName repository.url
```

to open the repo:
```sh
npm repo $packageName
```

**Comment by evanplaice** [comment]
Thank you

This'll be the next big research project. If it makes sense to revert 0.x back, we can notify 1.x users to bump major. That should provide a 'good enough' middle ground.


I'll create a new issue to track progress.

**Comment by pke** [comment]
I don't think we need to break anything here. Themes can just support both in a fallback style: `work.company || work.name`.
