### ISSUE TITLE
Adding support for specifying different teams in same company

### ISSUE THREAD

**Issue by armedbeast** [jsonresume/resume-schema#333]
Is there a way to specify team name, duration worked in that team and more highlights for the team for a specific company? If not, are there plans for adding it?

**Comment by stp-ip** [comment]
Not currently. Usually duplicating the same company again is ok and could be concatenated within a resume.
There is ongoing discussions about a new schema version using projects, which make it easier to reference the company and have multiple roles and or teams: https://github.com/resumic/schema/blob/master/schema.json#L497

Always happy to get ideas, PRs over there as well.

**Comment by Suncatcher** [comment]
@stp-ip where I can find sample for projects section? What are the available attributes? We need samples on the webpage, currently [in schema](https://jsonresume.org/schema/) there is no project section

**Comment by Suncatcher** [comment]
Is this the correct format for project array element?

		{
			"name": "Developing tetris",
			"description": "a smal side project",
			"startDate": "2017-10-01",
			"endDate": "2017-10-01",
			"entity": "HomeOffice",
			"location": "Jakarta",
			"roles": [
				"C++ Developer"
			],
			"type": "C++",
			"url": "https://yadayada.com",
			"highlights": [
				"C++",
				"STL Library"
			],
			"keywords": [
				"tetris",
				"gsmes"
			]
             }

**Comment by wayneamurphy** [comment]
Although having Projects is good, I would say it is different than being in different teams/roles within a company.
Whether a person goes from a Jr QA role to Lead QA role, or from QA to Dev - the roles are different and ideally we have something cleaner than having multiple Work entries.

**Comment by wayneamurphy** [comment]
Similar to #297

**Comment by Suncatcher** [comment]
Can anybody provide the sample fro projects section?

**Comment by evanplaice** [comment]
Here's mine https://github.com/evanplaice/resume

Under `resume.json` you'll find a projects section.
