### ISSUE TITLE
Allow $schema key in resume.json

### ISSUE THREAD

**Issue by pke** [jsonresume/resume-schema#334]
Add `$schema` as a key on the root object to enable specifying the schema inside the `resume.json` like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json"
}
```

**Comment by evanplaice** [comment]
Added in [v0.1.2](https://github.com/jsonresume/resume-schema/releases/tag/v0.1.2)
