### ISSUE TITLE
Advice: What is the correct way to handle complicated timelines?

### ISSUE THREAD

**Issue by DSchroer** [jsonresume/resume-schema#342]
I am in the process of updating my JSON resume and feel that it is difficult to represent timelines concisely. For example I have had 3 internships at the same company for a period of a few years. Afterwards I joined them full time. I feel like I should not put 4 blocks in the work experience section. Is there a recommended way to represent this situation within the format?

**Comment by evanplaice** [comment]
Put 2. One for internships, one for the FTE role. Break them down into timelines and reaponsibilities in the `job.highlights` section.

**Comment by DSchroer** [comment]
Thanks. Ill try that.
