### ISSUE TITLE
.well-known uri?

### ISSUE THREAD

**Issue by iptq** [jsonresume/resume-schema#350]
Hi, I'm interested in setting up a JSON resume on my website as an alternative to having a Linkedin, and I think JSON resume would massively benefit from having a standard .well-known uri for clients to look for, say, if I only provided a hostname.

Would this be a good idea to add? This is the biggest thing that's keeping me from using JSON resume at this point.

**Comment by evanplaice** [comment]
What's wrong with `resume.yoursite.com` or `yoursite.com/resume`?

I call mine 'vitae' as in short for CV. Here's a link https://evanplaice.com/vitae

**Comment by iptq** [comment]
The point would be to standardize it, so it would be at the same place on everyone's site. If I were to host it now, it would be under something like `/static/resume.json`, so I would have to link to it from the homepage and now that requires actually looking through the homepage for the resume link.

Instead, if a standard JSON resume location is decided on, I could just say "here's my domain, I'm hosting a resume: abc.xyz". There could also be clients that implement this.

This would be difficult for people who host their sites on shared hosts, but I think for many people who are running on their own domains or even using Github pages, standardizing the location as well as the format would be a really nice addition.

**Comment by evanplaice** [comment]
Gotcha. It's a good idea. Maybe if/when v1.0 is published. There's a lot of work that still needs to be done between now and then.

**Comment by antialias** [comment]
@iptq : are you thinking of something similar to how `/favicon.ico` sets the favicon for a website? One limitation I think of is that any particular path (or pattern of a path) that we can come up will eventually conflict with some other website's path scheme. Another consideration is how to deal with websites for multiple people. How do you know when the standard applies or not?

In any case, I don't see how we could accommodate this request by changing the jsoneresume _schema_, so what would be the next action here _if we were_ to go ahead with this idea?

My recommendation: pitch the idea as a new directive to either robots.txt or the sitemap spec where a directive defines the path to the resume per-site or per-page

* https://www.robotstxt.org/
* https://www.sitemaps.org/

Of note: I can't find anything in [the `robots.txt` spec](https://www.robotstxt.org/norobots-rfc.txt) that says that unsupported directives are invalid, so maybe you could start the trend by adding this to your site's `robotx.txt`:

```txt
Resume: http://www.example.com/resume.json
```

**Comment by antialias** [comment]
I just remembered [microformats](http://microformats.org/). While microformats appears to have [their own format for embeddeing a resume directly into an HTML page](http://microformats.org/wiki/h-resume), you could probably get away with linking to your json resume with [a variant of the rel attribute](http://microformats.org/wiki/existing-rel-values), like rel-resume for example.

**Comment by iptq** [comment]
@antialias Thanks for your thoughts!

> One limitation I think of is that any particular path (or pattern of a path) that we can come up will eventually conflict with some other website's path scheme.

That's the point of standardizing it. I suggested using `.well-known` since it's a protocol for standardizing URIs. As far as I know, there isn't already a well-known URI for resumes specifically.

> you could probably get away with linking to your json resume with a variant of the rel attribute, like rel-json-resume for example.

This is also an interesting idea and solves the "1-resume-per-host" problem at the cost of an extra hop (you'd have to hit the index page first).

> In any case, I don't see how we could accommodate this request by changing the jsoneresume schema, so what would be the next action here if we were to go ahead with this idea?

The way I see it, the jsonresume project could officiate the process of locating resumes as well as the contents of the resume.json itself. That's why I want to get the jsonresume team involved.

**Comment by antialias** [comment]
Ah, I thought the dot was a typo. I just spent a few minutes reading the RFC and a few other sources. The RFC suggests that .well-known resources contain `site-wide metadata`, and to me it seems like a bit of a stretch to apply this to one's resume, but if it's what you want... why not?

(Also, looking at https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml, the currently registered well-known URIs seem to be more focused on the web host than the person behind the website.)

In any case, I don't see any reason _not_ to do this. Since this is an open-source project, and registration is done by sending a request to 'the wellknown-uri-review@ietf.org mailing list for review and comment, with an appropriate subject (e.g., "Request for well-known URI: example").', it seems the next action here is for you to draft such a proposal and send it to them.

BTW, I'm not endorsing this idea in any way on behalf of the jsonresume project – my response here is just a summary of my research that you may (or may not) find helpful for taking the next step on what you've requested.

**Comment by thomasdavis** [comment]
This is a great suggestion, I hope to revive one day. 

JSON Resume doesn't have enough traction to make this worthwhile just yet. 

Closing now (for clarity) , but when the time comes, this issue will be referenced.
