### ISSUE TITLE
Multiple resumes from same github profile in registry? 

### ISSUE THREAD

**Issue by pedrohba1** [jsonresume/resume-schema#358]
I would like to have multiple resume.json on my gists, so I can have one to send to people that speak portuguese, and another one to send to international companies that might want my services. But as far as I know, the registry only gets the gist named resume.json. Is it possible to do something like: 

https://registry.jsonresume.org/pedrohba1/international to display my international resume and 
https://registry.jsonresume.org/pedrohba1/portguese to display my national one?

**Comment by antialias** [comment]
Hi @pedrohba1, this repository is only for the schema and validation function. You may have better results by re-posting this issue over at [resume-website/issues](https://github.com/jsonresume/resume-website/issues).

**Comment by pedrohba1** [comment]
Understood, thank you!

**Comment by antialias** [comment]
@evanplaice this can be closed.
