### ISSUE TITLE
Add a toolsUsed under work properties

### ISSUE THREAD

**Issue by lostphilosopher** [jsonresume/resume-schema#37]
This may be too "tech specific" for a general standard, but any resume I've written (and most I've reviewed) have included a section for listing out the tools / technologies used in a previous position. 

This is helpful for passing resume filters, and gives the reviewer an at glance "have they used X random tool professionally" without eating up valuable page space.

Example:

__Tools Used__: GitHub, Zend Framework 2, Stripe, Bootstrap 3, PHPUnit

**Comment by olivif** [comment]
There doesn't seem to be much support for this currently. I propose we add the revisit tag and close for now.

**Comment by aloisdg** [comment]
I am against for the original reason. It is a bit too "tech specific". By the way, I used python 4 years ago. I dont think It is relevant to write it. Tools will rise in the project section: "I made a tools to create themes with nodejs, nunjucks, ava and babel. I also used some bash scripts to build it."

**Comment by olivif** [comment]
@aloisdg I agree, it seems very tech specific. I am not saying I don't want people to have it in their resumes if they want to, but I don't think we need a special field for it. As @thomasdavis mentions, this can easily be done in the work description section. Or the future projects section.

**Comment by aloisdg** [comment]
@olivif Yes! I agree to close it for now.

**Comment by stp-ip** [comment]
I'm with the reasoning here. Tell the story via projects and work sections instead of having tools as a non usable keyword list.
