### ISSUE TITLE
firstName and lastsName

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#374]
![Screen Shot 2020-04-24 at 11 28 56 am](https://user-images.githubusercontent.com/416209/80165474-e78ade00-861e-11ea-9481-663df418d738.png)

@evanplaice Just looking at the last release, why does it have under additions that the `name` property was changed, but doesn't seem to be reflected in the schema. (Nor do I think we should change `name`)

**Comment by evanplaice** [comment]
Look at the tag for the release (ie v0.0.6). I'm back-filling the releases and updating the CHANGELOG with every edit that has been made to the schema.

Just maintenance stuff...

**Comment by thomasdavis** [comment]
All good, thanks for that.
