### ISSUE TITLE
Add a projects section

### ISSUE THREAD

**Issue by lostphilosopher** [jsonresume/resume-schema#38]
This might be redundant with hobbies? If that is the case I'd argue that hobbies should be renamed to projects. It makes a stronger impression. 

Proposed projects section would be a place to add work done outside the "work" (paid) context. For example, assuming JSON Resume isn't something being made for an employer, it doesn't have a clear place in the current format.

Potential properties:
projectName
startDate
endDate
url
description

**Comment by dannief** [comment]
I like @extrajordanary's idea off adding an optional section name. This would be relevant to most sections actually and is really a separate issue.

Regarding projects, I think this is very much needed. I tend to add a section like this to my resume under "Other Work", implying things I've done that might not directly relate to my current career or the job I'm applying to, but I'd still like to highlight.

So I'm all for having the schema add this section **and** also add sectionName property added to all sections. (This would make templates more generic and I wouldn't have to customize a template just to give the section a different name)

If this ends up being called "projects" though, I'm not sure if it would really convey that I am really highlighting other work experience. E.g. supposed I was a lawyer and then decided to become a programmer. I might want to still highlight some of my law experience under "Other Work Experience". Projects would seem to imply stuff I've done on my own time. Maybe we also need "Other Work Experience"?

**Comment by DandyDev** [comment]
So where are we with this decision (I've been out of the loop for a while)? It seems that we still want to add projects, right?

**Comment by mudassir0909** [comment]
How about an optional `category` label. Now the themes might wish to display all of them under **Projects** section or might wish to group by `category` & list them. Something like the following
 
```json
projects: [{
   "name": "json-resume",
   "category": "Open Source",
   "highlights": [],
   "summary": "",
   "url": ""
},
{
   "name": "some cool portfolio",
   "category": "Portfolio",
   "highlights": [],
   "summary": "",
   "url": ""
}]
```

**Comment by mudassir0909** [comment]
Agree with @extrajordanary's approach of adding a `sectionName`

**Comment by matiassingers** [comment]
Any movement on the `project`/`portfolio` property?

**Comment by roadmanfong** [comment]
+1 project and portfolio

**Comment by camilleriluke** [comment]
+1 to `project` / `portfolio` section

**Comment by chris-barry** [comment]
+1

**Comment by DandyDev** [comment]
+1 for `projects` section

**Comment by dbkaplun** [comment]
+1

**Comment by nihey** [comment]
+1 to <code>project</code> / <code>portifolio</code>

**Comment by evanplaice** [comment]
@thomasdavis

Why not add `projects`, `portfolio`, and `opensource`?

These should carry the same structure as `volunteer` so the implementation shouldn't require extensive changes to the html generation code.

Justification:

 - `projects`
  Pertains to projects that may not be directly related to work, open source, or design. Think hardware. Not all work is done in code. For example, somebody writing a resume is a member of a local hackerspace. The members of the hackerspace are building an experimental rocket + sensors to capture data at high altitude.

 - `portfolio`
   Portfolios usually refer to design/asthetics. Ie visual elements. For example, logo designs, web page designs, photo collection, videos, engineering drawings, etc.

- `open source`
  Open Source refers specifically to contributions to software projects that are released under an OSI approved license. These could be added under `projects` or `portfolio` (ie if you ignore semantics) but it's important to consider the audience.

  It's pretty common for applications to be passed on to a HR (read non-technical barrier-of-entry) who will blindly filter based on keywords. The term `Open Source` carries a lot of weight and may be essential for an applicant who lacks formal education and/or extensive work experience.

**Comment by stp-ip** [comment]
I think that both ```opensource``` and ```portfolio``` could be done in the ```projects``` section. We want to be generic and not too specific on a profession. Splitting it up complicates the spec and does not really add value, especially when the projects section has enough attributes to be generic enough to be used for ```foss``` and design work.

**Comment by hacksalot** [comment]
Agree with @stp-ip and with our friend Occam and his razor. Has anybody experimented with adding an optional `flavor` or `type` field to the base item record as a distinguisher?

```javascript
projects: [
  {
    /* ... */
    flavor: 'foss'
  }.
  { 
    /* ... */
   flavor: 'portfolio'
  }
]
```

**Comment by aloisdg** [comment]
Agreed with @stp-ip and @hacksalot.

As an alternative to `flavor` and `type` that I like, I propose `category`.

**Comment by evanplaice** [comment]
Disregard my last comment.

:+1: to the proposal by @hacksalot

**Comment by brpaz** [comment]
HI. I found out JSON resume today and  looks really awesome but yeah, as a developer "projects" section is a must have.

**Comment by sosukeinu** [comment]
+1 for `projects/portfolio`. As for the reasoning, the ability to highlight personal projects (which many developers use to try out new technologies) seems perfectly in-line with JSON Resume's stated purpose of  being "For developers, by developers."

**Comment by zvory** [comment]
+1 for projects, I was very surprised when there was no section for projects.

**Comment by aloisdg** [comment]
For now, I use "volunteer" for this. I am a volunteer on my own project.

**Comment by StevenBlack** [comment]
Reference for scope and nomenclature:  [CreativeWork](http://schema.org/CreativeWork) at schema.org.

**Comment by mateusfreira** [comment]
+1

**Comment by chrisdotcode** [comment]
Are we discussing this in some other issue? Or is *this* the definition discussion about it?

**Comment by evanplaice** [comment]
@chrisdotcode *this* is the discussion.

**Comment by stp-ip** [comment]
Some of the discussion for projects was done in #201 as we wanted to make a clear distinction between work, project and events. So there is at least a few nice pointers and results in #201.

**Comment by chrisdotcode** [comment]
Yes, #201 was the issue I was thinking of.

**Comment by olivif** [comment]
Create a new issue to aggregate old discussions. I think everything discussed here is covered, but please re-open if I missed anything :smile:

**Comment by olivif** [comment]
Create a new issue to aggregate old discussions. I think everything discussed here is covered, but please re-open if I missed anything :smile:
