### ISSUE TITLE
Research for #331

### ISSUE THREAD

**Issue by evanplaice** [jsonresume/resume-schema#382]
Should `work.name` be reverted back to `work.company`?

This was an undocumented breaking change introduced in #270 that had the unfortunate impact of breaking a LOT of existing JSONResume template projects. This issues exists to search for, and discover how big that impact was and whether the change should be reverted.

If it is reverted, the change will be re-introduced in the planned v1.0 release so users who require the change can bump major to use it.

Template

- [jsonresume-theme-material](https://github.com/adamjmoon/jsonresume-theme-material/blob/master/resume.json) - work.company 
- [jsonresume-theme-macchiato](https://github.com/biosan/jsonresume-theme-macchiato/blob/master/resume.json) - work.name
- [jsonresume-theme-randytarampi](https://github.com/randytarampi/me) - work.company
- [jsonresume-theme-orbit-original](https://github.com/XuluWarrior/jsonresume-theme-orbit-original/blob/master/example-resume.json) - work.name
- [jsonresume-theme-eloquent-ru](https://github.com/asm0dey/jsonresume-theme-eloquent-ru) - work.company
- [jsonresume-theme-orbit](https://github.com/XuluWarrior/jsonresume-theme-orbit) - work.name
- [gatsby-theme-jsonresume](https://github.com/EmaSuriano/gatsby-theme-jsonresume) - work.company
- [jsonresume-theme-moon](https://github.com/adamjmoon/jsonresume-theme-moon) - work.company
- [jsonresume-theme-stackoverflow2](https://github.com/hearsid/jsonresume-theme-stackoverflow2) - work.name
- [jsonresume-theme-elegant](https://github.com/mudassir0909/jsonresume-theme-elegant) - work.company
- [jsonresume-theme-even](https://github.com/rbardini/jsonresume-theme-even) - work.name
- [jsonresume-theme-samk](https://github.com/samkasman/jsonresume-theme-samk) - work.company
- [kcv-theme-print-flexbox](https://github.com/karmacv/kcv-theme-print-flexbox) - work.company
- [jsonresume-theme-standard-resume](https://github.com/EmaSuriano/jsonresume-theme-standard-resume) - work.company
- [jsonresume-theme-apage](https://github.com/ricosmall/jsonresume-theme-apage) - work.company
- [kcv-theme-rocketspacer](https://github.com/karmacv/kcv-theme-rocketspacer) - work.company
- [jsonresume-theme-standard-resume-de](https://github.com/hkrone74/jsonresume-theme-standard-resume-de) - resume.company
- [jsonresume-theme-elegant-jali](https://github.com/jaliborc/jsonresume-theme-elegant) - work.company
- [kcv-theme-simple-red](https://github.com/karmacv/kcv-theme-simple-red) - work.name
- [@tjscollins/jsonresume-theme-streamline](https://github.com/tjscollins/jsonresume-theme-streamline) - work.company
- [jsonresume-theme-macchiato-ibic](https://github.com/houtianze/jsonresume-theme-macchiato-ibic) - work.name
- [jsonresume-theme-nl-flat](https://github.com/nickimola/json-resume-theme) - work.company
- [jsonresume-theme-pumpkin](https://github.com/bvosk/jsonresume-theme-pumpkin) - work.company
-

**Comment by evanplaice** [comment]
On a positive note, this research will provide a big ass list of JSONResume template projects 🤣

**Comment by pke** [comment]
I am not sure the normalisation intend is clear: It should be "work.name" instead of "work.company" to be conistent across work, project etc., shouldn't it?
Also this does not have to be a breaking change. 
In true REST hypermedia format philosphy we should try to evelute the format instead of breaking it. So all themes could recognize `work.company || work.name`.

**Comment by thomasdavis** [comment]
Maybe I should spend time building a bot that finds all `jsonresume-theme-*` repos and it creates an issue for the new breaking change. 

I think we can manage a bit of turmoil for a proper release e.g. v1

**Comment by thomasdavis** [comment]
And maybe a script that can comment on everyone's gist to do the updates too > https://gist.github.com/search?l=JSON&o=desc&q=resume.json&s=updated

**Comment by evanplaice** [comment]
IMO, it would be a good idea to notify all template repos that need to be updated to use `work.name` once v1 drops.

The bigger issue here is the schema is not a lib. Template repos don't import `resume-schema` as a dependency so there's no way to signal -- via SemVer -- that an update to the schema has happened.

That's why I'm taking a hard stance against introducing breaking changes. They do more harm than good. The exception being, breaking changes requested by the community.

> Maybe I should spend time building a bot that finds all jsonresume-theme-* repos and it creates an issue for the new breaking change.

This would be a big help. Aside from manually checking each template implementation (which is what I've been doing) there is no way to tell what a template does and does not implement.

For example, most were never updated to include the additional `projects` section.

**Comment by pke** [comment]
I think such bot could come in handy in the long run then exactly for the reason to inform theme creators to support new changes to the spec like `projects`. 
Who knows, if its sophisticated enough it might even suggest a PR with the changes (ML ftw haha).

**Comment by thomasdavis** [comment]
@evanplaice Yeah I woke up this morning and I've changed my mind. Maybe, let's not do breaking changes.

**Comment by DandyDev** [comment]
I think having a script to check for theme's adherence to specific current and future versions of the JSON Resume schema is useful. And maybe even a bot that automatically creates an issue on the repo of a particular theme as @thomasdavis suggested.

But aside from that, have we now converged on `work.name` or `work.company`? The cat is out of the bag it seems, and both versions are now "breaking" for a subset of the themes out there.

**Comment by pke** [comment]
imho it should be `work.name` to be consistent and expected naming. What if your workplace is not a company but a youth club, church or the army?

**Comment by DandyDev** [comment]
@evanplaice @thomasdavis can we make a decision about this?

**Comment by thomasdavis** [comment]
@evanplaice Whats your your vote on this? 

I'm still in both camps, trying to figure it out..

**Comment by DandyDev** [comment]
After reading this issue more closely, I've interpreted it as follows: we introduced a breaking change (going from `work.company` to `work.name`, and the proposal is to revert this change and reintroduce it for 1.0.0.
Given that we're now making a last push to 1.0.0, it seems silly to revert the change because we would be bringing it back very shortly.

Another point to consider, is that quite some themes have moved to `work.name` already and it's not at all clear that the majority is still on `work.company`.

And lastly, given that we're not at 1.0.0 yet, breaking changes are to be expected, so let's not confuse the community even more by reverting back and forth.

So conclusion (as far as I'm concerned): `work.name` is the way to go, which is already in the schema, so let's keep it like that and change this issue to track which themes need to change and help them by creating issues/PRs on their repos. Agree?

**Comment by thomasdavis** [comment]
@DandyDev Thanks for that response, you've convinced me to leave it as `work.name` 

Happy to go with it unless anyone has any final objections.

**Comment by aegershman** [comment]
I feel like "work.name" makes sense; "work" is quite abstract and covers plenty of areas of focus which might not necessarily be covered by the descriptor of a "company". And as others have said, "company" on it's own doesn't imply the field should be the company _name_. So `work.name` is conceptually sound, it's already in the schema, rock and roll, etc. Maybe we close this issue down? (unless there's more to discuss or another issue to build off of this?) 👍

**Comment by DandyDev** [comment]
I've created [an issue](#394) to notify themes that are incompatible with this change. We can close this issue now.
