### ISSUE TITLE
"Open Source Contributions" section

### ISSUE THREAD

**Issue by eeshugerman** [jsonresume/resume-schema#383]
Just wondering if there's any interest in adding this to the spec and/or if there are any known existing solutions (ie themes that already implement this)?

Thanks!

**Comment by stp-ip** [comment]
A separate section is too specific, but it can be showcased via 2 sections already.
Either `volunteer` or `projects`. Projects are probably more elaborate and showcase a specific bigger thing aka your own open source project. Volunteer could show general contributions or 

In the v0 aka master of the schema no projects section is available. v1 is a WIP so might change, but it already has a projects section. There is also ongoing discussion on the v1 iteration.

**Comment by eeshugerman** [comment]
Thanks again
