### ISSUE TITLE
Why is schama.json not match the CLI and website?

### ISSUE THREAD

**Issue by pcolby** [jsonresume/resume-schema#386]
Sorry if this has already been asked, but I find it quite confusing.

This report contains a [schema.json](https://github.com/jsonresume/resume-schema/blob/master/schema.json), which I expected would be the source of truth, but its different the one show on the [JSON Resume](https://jsonresume.org/schema/), and also not the same as the one used by the current [resume CLI](https://github.com/jsonresume/resume-cli).

For example. the personal website property path is `basics.url` in this repo, but `basics.website` in both the website and CLI.

Is this repo just out of date?  Or is this repo's `schema.org` just not used anymore?  What is the source of truth for the schema?

Thanks :)

**Comment by stp-ip** [comment]
CLI and the one on the website are accurate from the v0 perspective.
Master had a few changes merged, before development moved to v1.

Source of truth in terms of what is most widely used is the v0.0.16 version: https://github.com/jsonresume/resume-schema/blob/a6d1ae5c990e3370de6ca305ef32477b9516391b/schema.json

**Comment by pcolby** [comment]
Thanks @stp-ip :)
