### ISSUE TITLE
Status of JSON Resume

### ISSUE THREAD

**Issue by DandyDev** [jsonresume/resume-schema#388]
Hey all! I haven't been active in this project for years now, but I'd love for it to reach 1.0 status. It seems there is [a roadmap](https://github.com/jsonresume/resume-schema/issues/372), but it isn't very active (last comment in May). Meanwhile, jsonresume.org is down, and that is not the first time.
There are _a lot_ of themes and projects that sprung up around jsonresume, so it would truly be sad if we cannot pull it over the (first) finish line.

I'm willing to chip in again. So what needs to happen for 1.0? And how can I help get the various websites up and running again?

As a sidenote: I came back to this project because I'm in dire need of updating my resume. Some parts of jsonresume still keep me from using it, most notably `eduction.gpa` not being something less US-centric.

edit: tagging @thomasdavis @evanplaice

**Comment by stp-ip** [comment]
Welcome back even under these circumstances aka updating your resume.

**Comment by thomasdavis** [comment]
Ahh shit, the domain expiring was getting spam foldered for me. Just paid it for a few more years. 

There have some been great people contributing to the schema this year, pretty sure we can do this v1.

**Comment by DandyDev** [comment]
I love that more people are involved now. Let's see if we can fix the last remaining "big" issues and push for v1 soon.
And @thomasdavis thanks for bringing back the website!
