### ISSUE TITLE
Maintainers left the building?

### ISSUE THREAD

**Issue by Velua** [jsonresume/resume-schema#389]
Is this project still maintained? Seeing some PR's sitting there and no new commits in the past few months

**Comment by jkga** [comment]
Hi @Velua , I am not really the one who answer this but I think they are just finalizing what should be included and amended on the next release.  Like this one. This is their [discussion](https://github.com/jsonresume/resume-schema/issues/382) about using `work.company` or `work.name`

**Comment by thomasdavis** [comment]
There is active development at the moment, discussion shifts between different repos but the schema and cli are moving ahead.
