### ISSUE TITLE
Add PGP/GPG field

### ISSUE THREAD

**Issue by heitorPB** [jsonresume/resume-schema#393]
It would be nice to have a field to add the PGP/GPG fingerprint and link to the public key.

My thoughts are to have two ways for the email field:
- a string
- an object with `email`, `fingerprint`, `url`

What do you think?

**Comment by virtadpt** [comment]
If it's not signed, it didn't come from me...

**Comment by thomasdavis** [comment]
It's a cool idea, but you should sign your `resume.json` much earlier.

**Comment by heitorPB** [comment]
Not sure I follow you, @thomasdavis. The use case I have in mind is to have a field for the PGP key in the `resume.json` so it can be displayed easily, e.g., when generating an HTML or pdf. Signing the `.json` is a good idea, but does not address this.

**Comment by johntdyer** [comment]
I agree, this is needed
