### ISSUE TITLE
Only specify one name

### ISSUE THREAD

**Issue by pserwylo** [jsonresume/resume-schema#4]
I notice that you have both "firstName" and "lastName" as entries in the scehma. May I propose that this be amended to just a single name? This is in the spirit of ["Falsehoods Programmers Believe about names"](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/).

In this case, the assumption that people have a first name and a last name is probably not suitable for resumes. If the goal is to have the ability to output a resume which uses their full name, and also only their first name, then perhaps a different solution is required. For example, a "name" (e.g. Peter Serwylo) and "preferredName" (e.g. Peter or Pete). 

The final case which I think people may want to have separate first/last names would be so that resumes can be output with the surname first (e.g. Serwylo, Peter). I'm not quite sure of how to achieve this with only a single name unfortunately.

At any rate, the points in the article linked above are worthwhile considering, as are many of the comments people have posted to that article. Cheers.

**Comment by g13013** [comment]
Doesn't make sens at all
