### ISSUE TITLE
Extend schema to full job application

### ISSUE THREAD

**Issue by mwaclawek** [jsonresume/resume-schema#40]
The vision for this project is clear, and I find it incredibly exciting.

But I could see a much bigger impact and lots of tools emerging if the schema offered the *option* to extend the records beyond a CV to become a full job application.

I see that the other parts of a full job application, notably cover letters, don't really fit in, as they are always-changing.

But if you consider the practical use, what people could do with the schema and what tools could develop around this project (e.g. GUIs for creating job applications from scratch), the schema requires support for the remaining parts of a job application.

You don't have to use those parts, of course. But if they don't become part of the schema, all the tools being developed will lack support for those parts as well.

The world has a great richness of cultures, countries, industries and people. And if you don't support a variety of needs, the schema is never going to be universal.

Just imagine the following additions:

```
cover_letter {
	job_title: string, // e.g. caretaker
	date_line: string, // e.g. London, 01/01/2001
	salutation: string, // e.g. Dear Sir/Madam
	text: string, // e.g. I would like to apply to ...
	company_name: string, // e.g. Example Inc.
	company_contact: string, // e.g. Jane Doe
	company_street: string, // e.g. 123 Example Street
	company_city: string // e.g. Example City 54321
},
location: {
	street: string // e.g. 123 Example Street
},
references: [{
    file_path: string // e.g. http://www.example.com/images/scanned_reference.jpg
}]
```
The schema would instantly support cover letters as an *optional feature* as well as scanned references that could be displayed full-page.

We should leave the specific arrangement and implementation up to users and themes, but we should provide support for features that are truly universal.

Considering the share of users who create CV and cover letter in combination every single time, I can see huge numbers go off the boil when they see that they're not able to create both parts in a consistent design.

**Comment by olivif** [comment]
sounds like a very interesting idea which we should talk about. But probably a post v1.0.0 discussion. I've created a *Revisit* tag, and this sounds like a great candidate for it. 

@stp-ip @chrisdotcode @PeterDaveHello

**Comment by stp-ip** [comment]
I think this could or should be discussed before v1.0.0 even. 
So 2 out of the 3 suggestions will already be in v1.0.0 as far as we can say. These include ```references``` and ```location```.
So the missing piece would be the cover letter.
Concerning the cover letter. It seems that some data would already be available in the resume data. So I would probably go for letting the cover letter just reference some fields from the schema. This referencing should be done in tooling.
Furthermore with the suggestion of filtering in #203 the data could be tailored to different applications.
Every data, which is not about yourself, should not be in the schema I feel.

So +1 for ```references``` and for ```location```, -1 for cover letter within the schema, -1 for individual data such as letter of motivation etc. These are things, which should be added via tooling or afterwards in my opinion. Not saying that there is no place for recommendations or guidelines for these cases, but nothing I would want in the schema. (+1 for adding some recommendations/guidelines for tooling/use-cases etc.)

**Comment by chrisdotcode** [comment]
@stp-ip  said:
> So I would probably go for letting the cover letter just reference some fields from the schema. This referencing should be done in tooling.
Furthermore with the suggestion of filtering in #203 the data could be tailored to different applications.
>
> Every data, which is not about yourself, should not be in the schema I feel.

This is correct -the schema is, well, only about a schema. Anything addition is by definition, outside the scope of a person's resume/CV. Not all jobs require a cover letter, or even anything additional.

Therefore, I'm going to close this, but if anyone has any strong disagreement, just comment, and I'll re-open.
