### ISSUE TITLE
Missing personnel master data

### ISSUE THREAD

**Issue by ocram** [jsonresume/resume-schema#41]
At least in Germany, it's standard practice to include a short section of personnel master data at the top of the CV.

Example:

```
Name = John Doe
Birth = 6th December 1980 in Berlin
Citizenship = German
Family status = married
Children = two (6 and 12 years)
```

Although that might not be common in other countries, could this be added as an optional section?

Example:

```
master_data: {
    name: string,
    birth: {
        date: integer,
        place: string
    },
    citizenship: string,
    family_status: string,
    children: [{
        gender: string,
        birth_date: int
    }]
}
```

**Comment by DandyDev** [comment]
I haven't seen any +1s for almost 2 months now, which gives me the feeling that there's not so much need for this after all? Can we close this @thomasdavis?

**Comment by ernstkui** [comment]
+1, In the Netherlands its pretty much mandatory. Just google ["nederlands cv"](https://www.google.nl/search?q=nederlands+cv&source=lnms&tbm=isch&sa=X&ei=33JpVd2MCIb1UueigfgC&ved=0CAcQ_AUoAQ&biw=1843&bih=969), first 13 image hits contain this data.

**Comment by thomasdavis** [comment]
@DandyDev I feel like we might include a new dynamic field type to support specific use cases like this and call it _extensions_ or something. Obviously it will solve a bunch of our other problems too.

**Comment by DandyDev** [comment]
I have been thinking some more on this, and I feel that:
> But should it be this open-source project's task to fight social issues?
Yes, open source is about pushing boundaries outside of the confines of corporate and societal constraints.
I might be opening a can of worms here, but I feel it is _really bad_ if we start providing companies with tools that are there for the sole purpose of discrimination. Providing birthdate and gender for instance, serves no other purpose than giving employers a way to "pre-select" candidates.

So I stand by my original reasoning:
> We could make them optional and make it very clear in the description that in some countries it's illegal for an employer to ask about this.

That means, whatever form we give it, I feel a warning is in order :)

**Comment by opensourcegrrrl** [comment]
+1, @DandyDev

**Comment by aloisdg** [comment]
+1 @DandyDev

**Comment by JD-Robbs** [comment]
+1 @DandyDev 

Albeit I utterly disagree with this practice, it sadly is how CVs work in Germany (and, to my knowledge, Austria, Switzerland and Netherlands as well).

**Comment by JD-Robbs** [comment]
@mwaclawek Just to extend on that - this would also need to be able to account for dual citizenship. I.e. turning that property into a collection of 1-n citizenships. While that may not be necessary for most - I know a number of people falling into this group.

**Comment by chrisdotcode** [comment]
The schema only cares about data. A warning, if provided, isn't necessarily the job of the schema. That responsibility should be pushed to the consumers of the schema, that is, the theme creators. Again considering that some of this is locale specific, we shouldn't necessarily add it for those locales that *don't* need this sort of information.

What I do propose, however, is an optional schema section that can consist of any values, that theme implementors can use when generating locale-specific themes. This is isomorphic to @thomasdavis's extensions suggestion.

**Comment by stp-ip** [comment]
A warning in the schema just makes it easier for theme developers to notice, which might be a good idea. Nothing too fancy for such a notice so.

As local data is just additional data, which is still available in other locales, I would use an additional info section, which can be extended, but has some predefined items available.

**Comment by aloisdg** [comment]
As suggested by @dionysius, we should add a field for:

> mobility (driving licence [category xyz], train season ticket, ...)

[source](https://github.com/jsonresume/resume-schema/issues/221#issue-126661770)

**Comment by dionysius** [comment]
ty for mention me @aloisdg 

to make the use case a bit clearer i suggest as example:

```
"mobility": [
  "Driving licence XYZ",
  "Train 1/2-price yearly ticket"
]
```

I see this field as an array of strings: 0..n elements

**Comment by StevenBlack** [comment]
schema.org may provide helpful taxonomy here.

* [Person](http://schema.org/Person)
* [Permit](http://schema.org/Permit)

And [others](http://schema.org/docs/full.html).

**Comment by mudassir0909** [comment]
+1 for

> I feel like we might include a new dynamic field type to support specific use cases like this and call it extensions or something. Obviously it will solve a bunch of our other problems too.

This way we can keep the original schema lean & provide these additional add-ons on demand

**Comment by dionysius** [comment]
-1 for

> I feel like we might include a new dynamic field type to support specific use cases like this and call it extensions or something. Obviously it will solve a bunch of our other problems too.

Might be true for the "problems" part, but for the "standards" part this might be a problem. Because resume-schema is supposed to be **JSON-based standard for resumes**, so when there is a "well" standard, its easy to write tools to filter data on these json data.

If you have thousand of different "add-ons", how do you filter or sort them? It's nearly impossible to address the definitions which come by these add-ons.

resume-schema has only a chance to really become a "standard", if it addresses exactly this issues well

**Comment by aloisdg** [comment]
-1 for extension too. You can choose to not fulfill everything. It should be enough.

**Comment by stp-ip** [comment]
There is always the possibility to add fields somewhere and try to get it upstream, if it is actually useful for the standard. With extensions you don't need to get the change upstream as this would kill the extension. So I would try to close down the standard for v1 as best as we can without killing of generic uses. In addition enable workarounds, which work, but make it clear that, if actually necessary going upstream would be best.

Hope that makes sense.

**Comment by aloisdg** [comment]
@stp-ip I agree with this.

**Comment by dionysius** [comment]
agree
> try to close down the standard for v1 as best as we can without killing of generic uses

**Comment by aarnaud** [comment]
+1 for birth

**Comment by alisterlf** [comment]
+1 for add birthdate on schema.
In Brazil is extremely common to resumes have birthdate in it.
