### ISSUE TITLE
GDPR clause at the bottom of resume

### ISSUE THREAD

**Issue by Solidogen** [jsonresume/resume-schema#414]
In some countries in Europe we need a clause at the bottom of resume to be processable.

`I hereby give consent for my personal data included in my application to be processed for the purposes of the recruitment process under the European Parliament's and Council of the European Union Regulation on the Protection of Natural Persons as of 27 April 2016, with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (Data Protection Directive)`

I don't see any fitting way to include this, any section I would paste this in looks cringy. Any help?

**Comment by thomasdavis** [comment]
A little too specific, better to make templates that can handle it. 
Fork the one you use, and add it to the bottom.

**Comment by Solidogen** [comment]
How is it specific, this is just a possibility to add any text on the bottom.

**Comment by samupl** [comment]
@thomasdavis  Could we consider reopening it?

The GDPR clause might sound different depending on where you're applying and what you want. The one given by the issue author is generic and allows anyone to process your application. Some people might be more concerned about how their data is being processed, and they might want to add "Company-specific" footers (e.g. give consent only for one specific company to process your personal data).

On top of that, the clause itself might change over time, or candidate might want to re-use the same resume theme across different applications (case above, or EU/non-EU job market). Themes will get outdated quickly. An ability to add a custom footer would be very helpful here.

I think such option is very relevant for european job market right now.
