### ISSUE TITLE
Schema.org Vocabulary

### ISSUE THREAD

**Issue by smizell** [jsonresume/resume-schema#42]
This may have been suggested already, but any thoughts on using Schema.org vocabulary?

http://schema.org/docs/full.html

**Comment by olivif** [comment]
seems like a new feature to me and a massive change. also no updates in more than a year. Is this still relevant?

**Comment by stp-ip** [comment]
Definitely a bigger change and most likely something for the fine tuning stage? If we know what data goes into the next release, changing the wording/vocabulary etc. is easier than trying to incorporate that right now. At least that's my feeling.

**Comment by StevenBlack** [comment]
Suggestion to focus conversation:  the [`Person` schema from schema.org](http://schema.org/Person) ought to be supported *In toto* here.

If you scroll that [Person page]((http://schema.org/Person), you come to this fascinating table. Preview below.  It's especially the `On Types` column that's interesting.

* `resume-schema` needs to support `CreativeWork` for `author`s and `collaborator`s and **many** of such types (some highlighted yellow below).

* `resume-schema` needs to support `Event` and `Action` pretty soon for those who have been 'organizer` or 'participant' or 'competitor' or `candidate` or `winner` or `recipient` and `performer` of things.

See how vocab focuses discourse?  

Just knowing the lexicon-space clarifies that `resume-schema` needs to support drastically more diverse Types.

(This shows half the list) 

![2016-01-03_22-23-05](https://cloud.githubusercontent.com/assets/80144/12083123/0c853962-b26b-11e5-9645-fdbccb32c515.jpg)

**Comment by chrisdotcode** [comment]
Let's revisit this post-v1.0.0.

**Comment by thomasdavis** [comment]
Have read all your comments, thought about it and read my previous comments. JSON Resume will remain a simple implementation, converting anything to a format on schema.org will just copy what it can.
