### ISSUE TITLE
This is not a valid Github username

### ISSUE THREAD

**Issue by wayneamurphy** [jsonresume/resume-schema#428]
It was working last week, but this week when I went to my resume I got "This is not a valid Github username"
I was wondering what I did wrong, but then I saw the example URL of https://registry.jsonresume.org/thomasdavis
also doesn't work - so maybe a server config was changed?

**Comment by jwko** [comment]
https://github.com/jsonresume/registry-functions/blob/master/functions/index.js

I can fetch by hand these urls from a browser

https://gist.githubusercontent.com/${username}/${gistId}/raw?cachebust= 
https://api.github.com/users/${req.params.username}/gists

Maybe the trouble is from axios library ?
cf https://lifesaver.codes/answer/axios-catch-error-returns-javascript-error-not-server-response

**Comment by thomasdavis** [comment]
Sorry @wayneamurphy and @jwko and everyone else.

It was a billing issue and I was away from the computer for a bit.

It's back up now and I've added enough funds to support it for 2 years.
