### ISSUE TITLE
Resume json invalid - [{"code":"INVALID_TYPE","params":["object","string"],"message":"Expected type object but found type string","path":"#/","title":"Resume Schema"}] - Please visit https://github.com/jsonresume/registry-functions/issues/27

### ISSUE THREAD

**Issue by khanjeee** [jsonresume/resume-schema#430]
facing this issue while creating my resume.

**Comment by thomasdavis** [comment]
@khanjeee Could you link your resume.json?

**Comment by IslamSakrak** [comment]
@khanjeee Just use this as your starter than adjust 


https://registry.jsonresume.org/thomasdavis

**Comment by khanjeee** [comment]
@thomasdavis 
here is the [link](https://gist.github.com/khanjeee/cc6770d00c1546b0584fb9406856acf6) 
Thanks in advance.

**Comment by khanjeee** [comment]
I have generated JSON via Json Resume Exporter Plugin through LinkedIn.

**Comment by khanjeee** [comment]
i have used the sample json and it fixed, Thanks.
