### ISSUE TITLE
Need first name +middle name + last name

### ISSUE THREAD

**Issue by hankconn** [jsonresume/resume-schema#433]
Providing these as separate fields is really helpful for name deduplication. I would suggest:

```
name: {
  full_name: "",
  first_name: "",
  middle_name: "",
  last_name: ""
}
```

**Comment by SethFalco** [comment]
Think you could elaborate on why this might be useful?

In my opinion, just having a single field for name is appropriate for the standard.
This is a pretty good read: https://www.w3.org/International/questions/qa-personal-names

I'd imagine it could be useful for working with third-party websites that force users to split their name up, but overall, I think the sites should change, not the schema. 🤔 (Just my opinion, though.)

Meanwhile, if we did follow your suggestion as closely as possible, I think `middle_name` would have to be `middle_names`.

**Comment by thomasdavis** [comment]
Yeah, this one won't likely change. `name` is just easier for the ecosystem to support. 

See the original discussion here -> https://github.com/jsonresume/resume-schema/issues/4
