### ISSUE TITLE
Resume date & label

### ISSUE THREAD

**Issue by hankconn** [jsonresume/resume-schema#434]
A given person might have multiple resumes, whether over time or different versions for different job titles / position sought. I would add a top level "resume_date" key and "resume_label" key.

**Comment by SethFalco** [comment]
Does this make much sense, though? 🤔 
I'm not sure what your use-case is, but on the surface it sounds like it'd be easier to make 2 separate files?

i.e. `engineer.resume.json` for Software Engineer positions and `writer.resume.json` for Technical Writer positions.

**Comment by thomasdavis** [comment]
Agree with Seth. 

Users can manage that information with their own local setups.
