### ISSUE TITLE
Person-Job Fit

### ISSUE THREAD

**Issue by dmaurath** [jsonresume/resume-schema#44]
Ever since I worked for a recruitment startup, I have pushed for standardization of resumes but for this to catch on, I think job descriptions need to also be standardized. And if both are standardized, you would want to make some changes according to the theory of Person-Job fit. 

In Industrial-Organizational Psychology we determine how a person fits with a job by first determining the KSAOs, or Knowledge, Skills, Abilities and Other Characteristics (e.g. personality), needed to complete all tasks of the job. Then we design tests, interviews, and other selection tools to assess applicants on their level of each KSAO. Thus, for each job description and resume, you would be able to best predict fit, if the JD and resume each had matching KSAOs. 

P-J fit is only one aspect of selecting a candidate. You could also try to match an applicant to a job based on shared values with an organization (Person-Organization fit), how their skills complement their immediate working group (Person-Group fit), or how their work style and norms align with their immediate supervisor (Person-Supervisor fit). 

Takeaways:
1. Create a complementary JSON Job Description
2. Include fields for Knowledge, Abilities and Other Characteristics in addition to Skills
3. Include a field for values.

**Comment by kbdavis07** [comment]
I do think there should be some Universal standardize job description or title.

Example of this is in the web development field.

Searching through job posts the description and skills required for a 

"Web Developer"

Can be very different from one company to another.

May be not part of the Resume-Schema directly but maybe pull in data from a Universal Source used by all world wide.

Within the Resume-Schema provide an URI to the Job Title/Description

JobTitle: http://SomeUniversalSource/WebDeveloper


This way if employer or job seeker has any question about the job description for a title is there is one source of information to go to get it.

Sort of like an Dictionary for Job Titles with Descriptions.

Just a thought :)

**Comment by aloisdg** [comment]
As a test, I wrote a project called JSONHire. It is a draft to create schema for hire post. It is a kind of nemesis of JSONResume. I could explain more, but a read will be better. It is short. You can find [here](https://github.com/aloisdg/JSONHire/blob/master/hire.json).

**Comment by kbdavis07** [comment]
Hi @aloisdg good start on jsonhire.

I think it is a good idea which should go hand and hand with JSON resume :)

I believe if we can tie together the Resume and Hire JSON formats with a Global Universal Job Title/Position dictionary would be helpful in having universal job titles/positions from one company to another.

I have some ideas in the works :)

Starting first with a Resume Repostory at http://ResumeRepo.com

Thanking of putting features to upload json format Resumes and Hire posts.

An editor that is connected to a dictionary for drop down menu
s and search features for job titles.

An employer can select skills from a drop down or from a search.

**Comment by aloisdg** [comment]
@kbdavis07 It is exactly what I would love to see and to use. If JSONHire is going to grow, I will open a organisation with the same model than JSONResume.

**Comment by villasv** [comment]
I wanted to bump up this discussion. Recently I'm using the [Job Posting from schema.org](https://schema.org/JobPosting) but it certainly isn't ready for this kind of qualitative analysis proposed by @dmaurath.

**Comment by aloisdg** [comment]
@villasv I will look into this schema. What do you think of [JSONHire](https://github.com/aloisdg/JSONHire/blob/master/hire.json) as a draft. Feel free to add any comments/improvements in this project.
