### ISSUE TITLE
certificates date definition is inconsistent with other date fields

### ISSUE THREAD

**Issue by francis-fong** [jsonresume/resume-schema#448]
`certificates` `date` is defined with formate `date`, whereas all other date fields reference `iso8601` as defined locally with a pattern.

**Comment by thomasdavis** [comment]
This is a great find, it should definitely be consistent, thanks!

**Comment by SethFalco** [comment]
This has been addressed in the following PR:
* https://github.com/jsonresume/resume-schema/pull/456
