### ISSUE TITLE
Placeholder for specifying published work..

### ISSUE THREAD

**Issue by infysuresh** [jsonresume/resume-schema#45]
If there are publicly available links (apart from Blog) like Tableau Public, etc., having a placeholder for that will help. We can call this as LiveLinks, which can be used by the employers to click and see the kind of work that have been done by the job seeker.

**Comment by stp-ip** [comment]
I like the idea to showcase projects via urls. Could be easily combined with the project proposition #11.

**Comment by vidia** [comment]
+1 on this. It would be nice to have a "Projects" heading. I would like to see this as it;'s own heading and not inside of a job or org. I have a lot of personal projects on my resume for example that don't fall under a job or company.

**Comment by olivif** [comment]
Moving the conversation over to the new issue. Closing this.
