### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by willm** [jsonresume/resume-schema#455]
Hi,

It would be great to have the option to define your resume in multiple languages. Users could then pick which language they are generating when outputting to pdf.

An even nicer step would be to integrate with some kind of translation system to automatically generate a resume in a target language without having to re type everything.

**Comment by thomasdavis** [comment]
Re-opened an old issue in favor of this one 

https://github.com/jsonresume/resume-schema/issues/35

The discussion can continue, I still think that a user can build the tooling required for this.
