### ISSUE TITLE
Add end date or expiry date to certificates section

### ISSUE THREAD

**Issue by hugginsio** [jsonresume/resume-schema#457]
Many professional certificates expire after a certain period of time and require a recertification process. Some certificates that expire include:

- [All Google Cloud certificates](https://support.google.com/cloud-certification/answer/9907853)
- [All CNCF Certified Kubernetes certificates](https://docs.linuxfoundation.org/tc-docs/certification/faq-cka-ckad-cks#how-long-is-my-certification-valid-for)
- [Many Microsoft certificates](https://learn.microsoft.com/en-us/certifications/certification-expiration-policy)

Adding a field to capture the end date or expiry date would make it clear which certificates are up-to-date without forcing the user to go to another site to view additional certificate details.

**Comment by thomasdavis** [comment]
Closing in favor of #468
