### ISSUE TITLE
#jsonresume - Freenode - IRC

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#46]
Anyone wanting to discuss issues in further details should join the chat

**Comment by olivif** [comment]
Could we use [gitter](https://gitter.im/)? Seems like a lot of people on GitHub are using it, I believe it's slack-like and I *believe* it supports public access (according to [this](https://gitter.zendesk.com/hc/en-us/articles/200176672-Authenticating-with-GitHub)).

**Comment by chrisdotcode** [comment]
I much prefer #freenode - one less account to have.

There already *is* a gitter, and I'll signup if I'm forced; but whereever we go, we need to choose a centralized location.

**Comment by olivif** [comment]
I think you could log into gitter with a GitHub account :smile: 

I agree we should centralize this, slightly off topic, but while we're at it, we could also add a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) and update our docs on how people collaborate and contribute.

**Comment by chrisdotcode** [comment]
Let's get a non-negligible amount of changes actually merged first, then work on the contributing guidelines based on the contributions we did make.

**Comment by olivif** [comment]
@chrisdotcode good point :smile: are we aiming for a specific date on the v1 milestone?

**Comment by PeterDaveHello** [comment]
We have gitter room, invited @stp-ip @olivif and @chrisdotcode

**Comment by chrisdotcode** [comment]
@olivif Nope - just enough contributions such that we can formalize the process we would have been using.

**Comment by PeterDaveHello** [comment]
Let's talk here: https://gitter.im/jsonresume

**Comment by chrisdotcode** [comment]
Thanks, @PeterDaveHello!

**Comment by chrisdotcode** [comment]
@olivif: Sorry, misread your question above. `v1.0.0` will be done once we finish a substantial amount of the v1.0.0 issues. No specific "big one" in particular.

**Comment by olivif** [comment]
@chrisdotcode seems reasonable, we're going at a pretty good pace I feel :smile: 

thanks @PeterDaveHello , now I just need to learn to use this haha!

**Comment by PeterDaveHello** [comment]
We have the gitter room for awhile, it's integration with GitHub is great, no addtional reason to use irc.

**Comment by chrisdotcode** [comment]
I'm going to re-open this to remind us to sketch up a CONTRIBUTING.md.

**Comment by olivif** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Oh I closed a wrong issue haha ...

**Comment by PeterDaveHello** [comment]
@chrisdotcode I will like to creat another issue about the contribution guide like, that's different issue.

**Comment by aloisdg** [comment]
I second @PeterDaveHello . I am doing it.
Can you come back to the old title here? (#jsonresume - Freenode - IRC)

**Comment by PeterDaveHello** [comment]
Thanks you @aloisdg

**Comment by aloisdg** [comment]
@PeterDaveHello You are welcome!
