### ISSUE TITLE
Custom avatar is not loaded into the JSON resume (Elegant theme)

### ISSUE THREAD

**Issue by lananolana** [jsonresume/resume-schema#469]
## Description
The default image is displayed in place of the avatar instead of the actual image that is added into the `resume.json` file. The problem is only in the Elegant theme.

## Steps
**Preconditions**: JSON resume with Elegant theme is uploaded as a gist without an image link.

1. Copy the avatar URL, for example [my GitHub avatar](https://avatars.githubusercontent.com/u/107322490?v=4)
2. Paste the URL into `resume.json` file and update the public gist.
4. Refresh the resume page ([https://registry.jsonresume.org/](https://registry.jsonresume.org/)`{your_github_username}`)

## Actual result
The default image is displayed in place of the avatar.
### Image URL in the `resume.json`: 
![Actual link](https://github.com/jsonresume/resume-schema/assets/107322490/2827221a-2c88-455a-89a2-426cbf3efb53)
### Actual image URL on the page: 
![Error link](https://github.com/jsonresume/resume-schema/assets/107322490/e901c2d6-bf34-4729-91df-58940acbb29e)

## Expected result
The picture whose link is added to the `resume.json` file is displayed in place of the avatar.

## Additional links
- Link to [my resume.json file](https://gist.github.com/lananolana/2b3f0a128cda86e99028654f029d841f)
- Refer to JSON Schema:
https://github.com/jsonresume/resume-schema/blob/8996c2c99426ffc2606f592aad02a9038fbde692/schema.json#L30

**Comment by IodizedSalt** [comment]
I've had the same issue with the same theme. Switching to other themes resolved the issue, but I still wish to use Elegant as it is simply better than the others I have found.

**Comment by lananolana** [comment]
> I've had the same issue with the same theme. Switching to other themes resolved the issue, but I still wish to use Elegant as it is simply better than the others I have found.

Thanks for the detail, I've added it to the issue.

**Comment by thomasdavis** [comment]
Thanks for the issue @lananolana 

Though, the theme developers have control over the rendering. 

Consider creating an issue at https://github.com/mudassir0909/jsonresume-theme-elegant
