### ISSUE TITLE
Add URL links, paragraphs, formatting within fields? (HTML? Markdown? Latex?)

### ISSUE THREAD

**Issue by jpe42** [jsonresume/resume-schema#47]
Is it possible to embed href tags anywhere?

**Comment by howardroark** [comment]
Any updates on this?  I think @DandyDev's last suggestion to just assume Markdown makes the most sense.  Markdown is designed with common sense in mind and is completely readable by humans in plain text form.  Dialects aside the original implementation caught on because no one ever needed a manual to grok it.  You just look at an example and run.

I feel this project is lacking if I can't apply any basic formatting.  The point of a resume is to convey information to other humans and basic formatting is a necessary part of this process.

**Comment by dy2288** [comment]
+1 howardroark

**Comment by opensourcegrrrl** [comment]
Quickly looking into CommonMark at http://spec.commonmark.org/dingus, the following markdown examples do not render properly:

```
1. item one
1. item two
   a. sublist item one
   a. sublist item two
```

```
1. item one
2. item two
   a. sublist item one
   b. sublist item two
```

As a technical writer, I find Markdown quite limiting and would prefer HTML support in addition to Markdown.

**Comment by stp-ip** [comment]
I would say we should strive to first get the data only representation working and having a representation language possibility in the spec seems unreasonable for now. If this is added, it should definitely be some sort of meta, hidden tag. But I think that all the representation could be done with custom fields and data only in conjunction with a specific theme.

**Comment by stp-ip** [comment]
My proposition is probably to have the data without any representation, but make it possible later on to overwrite text only fields via the meta data section.

Would could write something like the following in the data section:
```json
...
"work" : {
  "name": "gardner AG",
  "description": "Gardening for the millenials"
  }
...
```
And in the meta data section one could add:

```
...
metadata.substitute = [{
  work.name["gardner AG"]: {
    "description.markdown" : "Markdown enabled description."
    },
  }],
...
```

This is only a rough idea on how this could be done in the metadata section and needs to be revisited, when v1 is finalized and the metadata section is available.

**Comment by aloisdg** [comment]
Nice idea! I would love see this because it could enable a lot of formatting. We could use a tag like the one in http request or an enum.

Each template will have to use a flag with support : "markdown", "html", "asciidoc", "plain text", etc.

**Comment by stp-ip** [comment]
Great thing about having a plain-text data source as truth is, that themes not supporting markdown etc. could just fallback to the plain-text source.

**Comment by aloisdg** [comment]
Plain text is already the default and it should stay like this.

**Comment by phumke** [comment]
@stp-ip +1 

It's a neat idea, but let's stick to the basics for v1

**Comment by aloisdg** [comment]
@phumke Indeed. This issues has the tag post-v1. :wink: 

Also, this one wont break the compatibility. It will be for a v1.x ! We can hope for v1.1. \o/

**Comment by thomasdavis** [comment]
After consideration, all fields should remain plain text and thus rely on the theme/converter for alternative formats.
