### ISSUE TITLE
Resume.json should have revision history

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#49]
We eventually want people to edit their resume's using a UI on the registry website etc

But we will run into problems with keeping resume.json's in sync.

e.g. If you edit it online and then publish from your local copy on your box you will override the changes you did on the registry.

We were thinking of adding a revision property which auto increments whenever you publish.

**Comment by stp-ip** [comment]
+1

**Comment by aloisdg** [comment]
Nice idea. I think it could be nice to have a kind of semver for resume.json, something in a metadata.

**Comment by olivif** [comment]
+1

**Comment by chrisdotcode** [comment]
Sounds good.  We'll add a top level `.version`. field in v1.0.0.

**Comment by stp-ip** [comment]
Decision: Use ```version``` field and have it in the meta data section proposed in #204. Version should follow SemVer

**Comment by phumke** [comment]
Sounds great.

**Comment by stp-ip** [comment]
Version is in: #258

I close this for now as the actual revision history should not be kept within the schema I assume.
