### ISSUE TITLE
Documentation - ReadTheDocs

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#53]
I've setup a ReadTheDocs account

http://json-resume.readthedocs.org/en/latest/

Anyone have much experience with it?

I think it will suit our needs perfectly

**Comment by aloisdg** [comment]
Any news about this? (Maybe useful for the after v1)

**Comment by hacksalot** [comment]
Is there an official ETA for the v1?

**Comment by aloisdg** [comment]
> ETA

Expected/Estimated Time of Accomplishment/Action/Arrival ?

**Comment by hacksalot** [comment]
ETA always means **estimated time of awesomeness**, as in, when will the 1.0.0 be officially released, or unofficially available for tool builders? : )

**Comment by aloisdg** [comment]
AFAIK, there is not. You can look for it or open a new issue around this. The idea is more to fix everything before release it. Check the branch v1.

**Comment by olivif** [comment]
@hacksalot no official date for v1, we are currently going through the feature discussions :smile:

**Comment by chrisdotcode** [comment]
No current date. The plan is thusly (in order):

1. Select and resolve *all* issues for v1.0.0 in resume-schema.
1. Implement all resume-schema=v1.0.0 issues.
1. Select and resolve *all* issues for v1.0.0 in resume-cli.
1. Implement all resume-cli=v1.0.0 issues.
1. Make sure the server hosted on jsonresume.org is *fully* compatible with all changes made to both of the above.
1. Fix compatibility where broken.
1. Mass publish resume-{schema,cli,server}=v1.0.0.

The cli and server might require re-writes, therefore, our ETA for v1.0.0 is an apt **?????**.

**Comment by aloisdg** [comment]
@chrisdotcode I think it would be nice to move this plan to a single issue with ToDo list format. Something like: 

- [ ] Select and resolve all issues for v1.0.0 in resume-schema.
- [ ] etc.

**Comment by opensourcegrrrl** [comment]
+1 for Read the Docs. For more information, [watch the Read the Docs video](https://www.youtube.com/watch?list=PLFDgm_9P62ut5sSOPTMMoiz8Xb2z-nJdz&v=U6ueKExLzSY). 

Since having previously posted, I have attended the (complementary) Write the Docs 2015 conference in Prague and can highly recommend attending.

Also recommendable is the Write the Docs forum at http://forum.writethedocs.org, which is a resource for anyone who can use a hand at writing documentation

**Comment by chrisdotcode** [comment]
(Auto-manually closing because this is so old. If it's still relevant, just give me a holler.)
