### ISSUE TITLE
Add Organizations

### ISSUE THREAD

**Issue by vote539** [jsonresume/resume-schema#54]
Particularly school organizations.  As a college student, this is where a lot of the content in my resume currently lives.  For example,

``` javascript
organizations: [{
    name: "Association for Computing Machinery",
    url: "acm.example.edu",
    type: "academic",
    positions: [{
        title: "President",
        startDate: "1901-01-01",
        endDate: "1901-12-31",
        summary: "Increased membership and brought Ben Franklin to campus"
    }, {
        title: "Treasurer",
        startDate: "1900-01-01",
        endDate: "1900-12-31",
        summary: "Raised $5 billion for regional hackathon"
    }]
}, {
    name: "Jazz Band",
    url: "jazzyjazz.example.org",
    type: "arts",
    positions: [{
        title: "Second Chair Trombone",
        startDate: "1902-06-30"
    }]
}]
```

Acceptable values for `type` could be "academic", "arts", "honorary", "social", "government", "service", "culture", "faith", "athletic", and "other".  The `type` field could also be made into an array.

The "organizations" field should also be accepted at the root level for organizations that are not associated with an educational institution.

**Comment by olivif** [comment]
Hmm interesting. I currently have a similar entry for some Uni work, but I put it in the volunteering section. I think I like the idea of organizations more though. I can see more than school work going there, like being member of a club or anything like that.

**Comment by stp-ip** [comment]
Is it enough to warrant a new section or should we move our volunteering section to be more generic. We sort of tried to find a generic section for projects/volunteering/organizations as far as I see. Discussion is mainly in #201, but some aspects in #138 and #38.

**Comment by aloisdg** [comment]
I am not sure to see the need. I think it can be merge in project.

**Comment by stp-ip** [comment]
I think we can for now use the new projects section https://github.com/jsonresume/resume-schema/pull/254.

If there is a need for another section, please open up a new issue for project section improvements or a completely new section suggestion.
