### ISSUE TITLE
Objects for education area

### ISSUE THREAD

**Issue by vote539** [jsonresume/resume-schema#56]
One thing I dislike about LinkedIn is the lack of a standard for majors and minors within a degree program.  Not all colleges and universities have a major/minor system, but very many do.

For example, the object below is more computer-readable than the string.

``` javascript
education: [{
    institution: "Starfleet Academy",
    area: {
        majors: ["Astrospace Engineering"],
        minors: ["Teleportation Science", "Warp Control"]
    }
}]
```

versus

``` javascript
education: [{
    institution: "Starfleet Academy",
    area: "Majors in Astrospace Engineering with Minors in Teleportation Science and Warp Control"
}]
```

**Comment by olivif** [comment]
related to #91 . is there support to make this PR needed?

**Comment by stp-ip** [comment]
I vote against an array. Multiple education items would work fine and would keep the standard cleaner. Especially minor and major is a non generic term and therefore would not be the best choice in my opinion anyway.

**Comment by olivif** [comment]
@stp-ip I agree with not having the array. The major/minor scenario is already supported in 2 ways: 

* Including major and minor in area (as @vote539 mentioned)

```
education: [{
    institution: "Starfleet Academy",
    area: "Majors in Astrospace Engineering with Minors in Teleportation Science and Warp Control"
}]
```

* Two education items 

```
"education": [
    {
      "institution": "Starfleet Academy",
      "area": "Astrospace Engineering (major)",
    },
        {
      "institution": "University of Oklahoma",
      "area": "Teleportation Science and Warp Control (minor)",
    }
]
```
Both of them seem acceptable to me. The array seems like would be catering for too narrow of a market and I imagine it would complicate things a bit for the theme creators as well.

**Comment by thomasdavis** [comment]
Closing this on my own personal opinion that a) you can convey it in the current fields b) most employers won't read it
