### ISSUE TITLE
Arrays for Social Media

### ISSUE THREAD

**Issue by vote539** [jsonresume/resume-schema#57]
I don't know about you, but on some social media sites like GitHub I have multiple accounts: some for personal use and some for business use.  If my usernames were `thing1` and `thing2`, then in the current schema, I could do:

``` javascript
profiles: {
    drSeussPersonal: "thing1"
    drSeussBusiness: "thing2"
}
```

But this could lead to issues for parsers that look specifically for certain profile keys like "github" or "stackOverflow".  A better solution might be something like:

``` javascript
profiles: {
    drSeuss: ["thing1", "thing2"]
}
```

We could even make them objects.

``` javascript
profiles: {
    drSeuss: [{
        username: "thing1",
        summary: "For my boring personal projects"
    }, {
        username: "thing2",
        summary: "For my sexy business projects"
    }]
}
```

Just a thought.

**Comment by stp-ip** [comment]
One per medium seems reasonable. If any addition, my vote would go to the "twitter" as default and "twitter.work" as addition proposition.

**Comment by aloisdg** [comment]
> I vote for reducing complexity here.

**Comment by olivif** [comment]
+1 to what @stp-ip said

**Comment by olivif** [comment]
Seems like we agree on KISS here. Closing for now, feel free to re-open :smile:

**Comment by chrisdotcode** [comment]
I like "twitter.work", "email.personal", etc. But let's document it somewhere somehow.

Re-opening as a reminder.

**Comment by chrisdotcode** [comment]
Actually, account names are just strings, so you can do something like "Work Twitter".

**Comment by stp-ip** [comment]
No change to the schema required. Just documentation on how it is possible.

**Comment by thomasdavis** [comment]
It's too uncommon to either support or document, but as @stp-ip said, it is still supported if those who wish to build it, do.
