### ISSUE TITLE
Have you heard of HR-XML?

### ISSUE THREAD

**Issue by bouiboui** [jsonresume/resume-schema#58]
I work in HR-related web application development, and there's a pretty thorough standard, free, but not open source, which is already in place. 

They have started writing parts of it in JSON (HR-JSON), and I'm pretty sure you could benefit from having a look at it.

I found an example of its implementation on Github:
https://github.com/zeliboba/HR-XSL/blob/master/lib/hr-xml-2.5/HR-XML-2_5/SEP/CandidateExample.xml

**Comment by calligraphic** [comment]
@osg @thomasdavis can you comment on what the barriers to using HR-XML that you found were? (besides the mid-five-figures membership fee?)
