### ISSUE TITLE
Add an optional 'Location' to all subsections

### ISSUE THREAD

**Issue by aristeia** [jsonresume/resume-schema#63]
e.g. I could add location to my jobs, education, to each of my hobbies, etc.

**Comment by DandyDev** [comment]
+1

**Comment by amorenoc** [comment]
+1

**Comment by dbkaplun** [comment]
+1

**Comment by dbkaplun** [comment]
Seems like everyone's on board. Can we mark this `PR Needed`?

**Comment by stp-ip** [comment]
Seems not yet included right? Any ETA?

**Comment by olivif** [comment]
+1 

@stp-ip  @chrisdotcode @thomasdavis, I see a bunch of issues in similar states. Shall we do a purge of all the issues one of these days? Make sure all issues are tagged properly and inside a milestone. And also a lot of backed up PRs which could also be cleaned up :)

**Comment by stp-ip** [comment]
I think most of the issues are kept open until most of the v1.0.0 discussions are done. After the first draft via small PRs, each issue contributing to a PR would be referenced and closed on merge.

Hope that makes sense.

**Comment by olivif** [comment]
@stp-ip it does, thanks :)

**Comment by chrisdotcode** [comment]
I think we may have discussed this tangentially in another issue? I think we all +1ed this.

**Comment by olivif** [comment]
@stp-ip should we add location to #223 as well?

**Comment by aloisdg** [comment]
Good idea but I will never use this. The result would be a cluttered mess.

Also, I can't image a HR who are looking to know that I love to drive my kayak at the 4 Privet Drive, Little Whinging, England. Feel weird to me.

**Comment by olivif** [comment]
haha @aloisdg! It should be used with caution, I agree :smile: 

I would probably only use it for work entries. I'd like to highlight having worked in various locations/countries.

**Comment by aloisdg** [comment]
It should go into project. For example, for an actor it could be awesome to say that he works in US or Japan or whatever.

Also, Internet is valid location for some kind of works. :p

**Comment by stp-ip** [comment]
Added to #223 and I agree it can be useful, but is something optional. But it might have generic uses for various kinds of artistic work as an example.

**Comment by olivif** [comment]
I agree. We can probably close this then.

**Comment by oupala** [comment]
+1 for adding location to work experiences, education and volunteer, at least.

**Comment by stp-ip** [comment]
Let's delay the PR until we decided on #240 which schema we use. Afterwards revisit this to add it to more sections. Including #55  etc.

**Comment by chrisdotcode** [comment]
Closing, cf. https://github.com/jsonresume/resume-schema/pull/240#issuecomment-653958512.
