### ISSUE TITLE
Add a title / short summary field in the bio section

### ISSUE THREAD

**Issue by anthonyray** [jsonresume/resume-schema#64]
Some people like to describe themselve with a title such as : "Full Stack Software Engineer" or "Pre Sales Engineer". In a complement to the summary field, maybe we could add a title or shortSummary field.

**Comment by stp-ip** [comment]
I would say that this is implemented via the basics.label field.

**Comment by evanplaice** [comment]
Closing as this functionality already exists in the schema.
