### ISSUE TITLE
Multiple projects per position

### ISSUE THREAD

**Issue by redbeard** [jsonresume/resume-schema#65]
The idea is to allow per-project details at the same company. Similar to the new(ish) feature in LinkedIn profiles. 

Structure follows same fields as position schema, but without company name, website, etc.

```json
{
  "work": [{
    ...
    "projects": [{
        "startDate": "string", // resume.json uses the ISO 8601 date standard e.g. 2014-06-29
        "endDate": "string", // e.g. 2012-06-29
        "summary": "string", // Give an overview of your responsibilities in the project
        "highlights": [] // As in position schema
      }]
    }]
}
```

**Comment by DandyDev** [comment]
Can @thomasdavis and @opensourcegrrrl weigh in on this?

**Comment by opensourcegrrrl** [comment]
+1

**Comment by stp-ip** [comment]
There is a definite need for this as was already mentioned consultancy clients or fast moving companies use their employees for more than one project. One could use highlights, but that is not the perfect place and not as accurate and clean.

**Comment by stp-ip** [comment]
Definitely could be combined with #11

**Comment by olivif** [comment]
Moving over the discussion to the new issue. I believe all topics covered here are included in the proposition.

**Comment by nikolay** [comment]
@olivif I don't think you understand the exact idea behind this issue! While working for an agency, which is one employment, I could be working for different clients on different projects and being on different positions on each project. Also, even on a single job, I could have multiple titles (if you gets promoted/demoted, etc.)

Okay, these are edge cases, but if the schema does not allow you to handle 10-20% of the cases, then it's not universal, and many people will fork the tools, and themes to get around this, which is sad.
