### ISSUE TITLE
publications.items.properties.role

### ISSUE THREAD

**Issue by WebReflection** [jsonresume/resume-schema#84]
I've personally been an official technical editor of different books , most of them "Amazon Best Seller" in the field … now, I don't feel like I should put those publications on my own resume because I didn't write those book … but "_hell yeah_" if I contributed to their final result, and I believe this should be part of my _indirect_ publications.

Thanks for considering this

**Comment by olivif** [comment]
are there other scenarios for publications that would require the role field? I'm wondering if it makes sense to capture this in work or projects instead of publications, as that seems to be more for the academic publications (at least in my head).

**Comment by chrisdotcode** [comment]
@olivif If we're switching to bibJSON for v1.0.0, the proper question is does *bibJSON* have a way to do this? :)

**Comment by olivif** [comment]
Based on this - "Record type places no constraint on what can be placed in the record" I believe this would be possible. But, how would our integration with bibJSON work? Would we be able to define fields on top of the bibJSON ones, and potentially add required/type constraints?

**Comment by chrisdotcode** [comment]
I'm not sure if we should. We should treat them as a black-box, and have resume-cli take user input to generate bibJSON as needed - like in my other suggestion, if we include a way to add publications from the cli, this will be made a lot easier.
