### ISSUE TITLE
Version 0.0.0

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/resume-schema#86]
The specification hasn't been touched yet. There are a lot of moving parts already in the ecosystem e.g. registry server, cli, themes. I've got a strategy in my head to glue it all together formally but have yet to document it all down.

The first step will be declaring the original as version 0.0.0 and locking everything that exists to that version.

I will then go around the ecosystem making sure everything is explicitly set to that version.

Once that is done, I will commit/merge the first changes to the spec using semver.org as a guide.

Each change will be logged to the README, with a link to the discussion. Each change will also be accompanied with notes about how updates may be applied, the CLI tool will probably have a new command that can progressively update your CV automatically depending on the fields e.g. name = firstName + lastName

Everything will eventually go in a beautiful readthedocs.org account.

**Comment by stp-ip** [comment]
Time for a new version I reckon ;)

**Comment by olivif** [comment]
Definitely headed for v1.0.0 :smile: shall we close this?

**Comment by chrisdotcode** [comment]
Yeah, I'm going to close this now.
