### ISSUE TITLE
General schema comments

### ISSUE THREAD

**Issue by wbrianwhite** [jsonresume/resume-schema#92]
Why not use a person object?  That can be used in the bio section for yourself, and also in the references section, since a string doesn't seem to be enough to me there.  There's no way to contact Joe Shmoe who recommended you, so the recommendation and even the perons's existence seems questionable.  

You don't have a middle name :(.  I go by my middle name.  I put W. Brian White on my resumes.  

Location:
The region/state division is often solved by using a CountrySubDivision field, which can be a state, province, etc however the country subdivides itself to avoid having two fields.
Location doesn't have an address.  Addresses are common on resumes for some reason.  

The html view (http://registry.jsonresume.org/thomasdavis) truncates start/end date to year.  Why?  Seems like you'd want to either show the full date, or only collect the year in the data.  This is subjective of course

**Comment by olivif** [comment]
`firstName` and `lastName` have been merged into `name` :smile: 

we are discussing adding more info on references in #2 which should cover your scenario.

we are also switching to using address for location - as per #209 

the one thing probably not covered in our discussion so far is using a `person` object. This sounds interesting to me as it could be applied to the person itself, references and projects. I could also see a lot of useful applications for it like search for: people who worked with *John*.

**Comment by chrisdotcode** [comment]
(As of now, I'm against a `person` object, but) if we were to add a `person` object, we need to fully flesh out the fields it could contain.

**Comment by olivif** [comment]
My thinking was that if we are going to add a lot of people fields (in references and in projects) it would be nice to agree on a set of fields and group those into a person object, for more consistency and less redundancy. 

What was your thinking against it @chrisdotcode ?

**Comment by chrisdotcode** [comment]
My stance is to not complicate the schema - which has a default of "don't add anything new". If we can solve an issue with existing fields, we should try that first. If not, let's add, but IMO, it's better to be conservative in what we accept than too liberal (not that we aren't going to accept new changes, just that we scrutinize them a bit more).

**Comment by stp-ip** [comment]
I am against a person object. As usually you are not referencing yourself. If we would allow cross referencing from references to the person giving it, we could easily do that by adding a "url" field, which is more generic.
That being said. I am still in favor of having more detailed personal information within the basics area. See #13 for more details on the discussion.

**Comment by chrisdotcode** [comment]
(Closing auto-manually because after 4 years, this discussion is likely stale. If it needs to be re-opened, give me a holler.)
