### ISSUE TITLE
Use waffle.io for streamlining development and decision making processes

### ISSUE THREAD

**Issue by DandyDev** [jsonresume/resume-schema#95]
Yesterday I discovered [waffle.io](https://waffle.io/) which basically turns your GitHub issues into an agile board. It allows you to customise which columns are shown and on what conditions tickets change columns. It also works the other way around: you can move a ticket, and the GH issue gets updated automatically.

Currently, @thomasdavis applies labels like _Decision needed_ and _PR needed_ manually, waffle.io could do this for us :)

**Comment by olivif** [comment]
given this is an organizational type of task, I suggest we consider this pre-v1. are we happy with our current workflow with issues or do we want to try out waffle or zenhub? :smile: 

cc @stp-ip @aloisdg @chrisdotcode @thomasdavis

**Comment by thomasdavis** [comment]
Always happy to try things, and we did try Waffle. But vanilla Github issues seems to do well enough.

**Comment by olivif** [comment]
any highlights from the waffle experiment? :smile:

**Comment by aloisdg** [comment]
Or we can switch for Gitlab.

**Comment by stp-ip** [comment]
As I am a contributor to Gitlab for a few years. I would love that, but if we ever do switch, we should do that post-v1

**Comment by olivif** [comment]
I think we should be OK with issues for now. If someone comes up with a better proposal, please re-open 😄
